use super::{CommandId, CommandSpec, ExecutionSupport, FlagSpec};

command_id_enum! {
pub(crate) enum CoreCommandId {
    Version,
    Capabilities,
    AgentTriage,
    Help,
    Doctor,
    DoctorCapabilities,
    DoctorHealth,
    DoctorRobotDocs,
    Find,
    FindCapabilities,
    FindRobotDocs,
    RobotDocs,
    RobotDocsGuide,
    Completion,
    CompletionBash,
    CompletionFish,
    CompletionPowershell,
    CompletionZsh,
    Conformance,
    ConformanceCoverage,
    ConformanceCheck,
    Apply,
    ConvertXlsmToXlsx,
    RepairNormalize,
    Template,
    TemplateApply,
    TemplateTokens,
    TemplateProfile,
    TemplateProfileSave,
    TemplateProfileInspect,
    Serve,
    Mcp,
    Inspect,
    Validate,
    Diff,
    Verify,
}}

pub(super) fn command_specs() -> Vec<CommandSpec> {
    vec![
        spec(
            CoreCommandId::Version,
            &["version"],
            "version",
            "Print the version of ooxml.",
            &[],
            direct("read-only metadata command"),
            vec![],
        ),
        spec(
            CoreCommandId::Capabilities,
            &["capabilities"],
            "capabilities [--for <filter>]",
            "Emit the Rust-supported machine-readable command and object inventory.",
            &[],
            direct("read-only self-description command"),
            vec![flag(
                "--for",
                "for",
                "string",
                "filter by command family or object kind; natural plurals and group aliases such as slides, ranges, conditional-formats, and modules are accepted",
            )],
        ),
        spec(
            CoreCommandId::AgentTriage,
            &["agent-triage"],
            "agent-triage",
            "Emit one-call agent triage JSON with quick refs, health, discovery filters, and safe next actions.",
            &[],
            direct("read-only agent mega-command"),
            vec![],
        ),
        spec(
            CoreCommandId::Help,
            &["help"],
            "help [command]",
            "Show Rust-supported command help.",
            &[],
            direct("read-only help command; parent/group help surfaces are not mutation ops"),
            vec![],
        ),
        spec(
            CoreCommandId::Doctor,
            &["doctor"],
            "doctor [--only <checks>]",
            "Run read-only environment checks for agent/release workflows.",
            &[],
            direct("read-only environment advisory command"),
            vec![
                flag(
                    "--only",
                    "only",
                    "string",
                    "comma-separated check ids to run",
                ),
                flag(
                    "--online",
                    "online",
                    "bool",
                    "accepted for legacy CLI compatibility; no network checks are performed",
                ),
            ],
        ),
        spec(
            CoreCommandId::DoctorCapabilities,
            &["doctor", "capabilities"],
            "doctor capabilities",
            "Emit the machine-readable doctor contract.",
            &[],
            direct("read-only doctor self-description command"),
            vec![],
        ),
        spec(
            CoreCommandId::DoctorHealth,
            &["doctor", "health"],
            "doctor health [--only <checks>]",
            "Emit a compact doctor health summary and findings exit code.",
            &[],
            direct("read-only environment advisory command"),
            vec![flag(
                "--only",
                "only",
                "string",
                "comma-separated check ids to run",
            )],
        ),
        spec(
            CoreCommandId::DoctorRobotDocs,
            &["doctor", "robot-docs"],
            "doctor robot-docs",
            "Print a paste-ready agent handbook for ooxml doctor.",
            &[],
            direct("read-only documentation command"),
            vec![],
        ),
        spec(
            CoreCommandId::Find,
            &["find"],
            "find <query> <file> [--type <all|text|formula|name>] [--ignore-case] [--regex] [--max <n>] [--to-ops|--replace <new> --apply (--out <file>|--in-place|--dry-run)]",
            "Search supported OOXML package text, formulas, and defined names; optionally emit or apply generated mutation ops.",
            &["package"],
            direct(
                "search/compose command with query and file positionals; emit apply-compatible operations with --to-ops, or use the generated mutation commands as apply ops",
            ),
            vec![
                flag(
                    "--type",
                    "type",
                    "string",
                    "search type: all, text, formula, or name",
                ),
                flag(
                    "--ignore-case",
                    "ignoreCase",
                    "bool",
                    "case-insensitive search",
                ),
                flag(
                    "--regex",
                    "regex",
                    "bool",
                    "treat query as a regular expression",
                ),
                flag(
                    "--max",
                    "max",
                    "int",
                    "maximum hits to return; 0 means unlimited",
                ),
                flag(
                    "--to-ops",
                    "toOps",
                    "bool",
                    "emit apply-compatible ops JSON without mutating the package",
                ),
                flag(
                    "--replace",
                    "replace",
                    "string",
                    "replacement value for generated ops",
                ),
                flag(
                    "--apply",
                    "apply",
                    "bool",
                    "run generated ops through the apply engine",
                ),
                flag("--out", "out", "string", "output file for --apply"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write --apply changes in place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "plan --apply without writing",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip final validation for --apply",
                ),
            ],
        ),
        spec(
            CoreCommandId::FindCapabilities,
            &["find", "capabilities"],
            "find capabilities",
            "Emit the machine-readable find contract.",
            &[],
            direct("read-only find self-description command"),
            vec![],
        ),
        spec(
            CoreCommandId::FindRobotDocs,
            &["find", "robot-docs"],
            "find robot-docs",
            "Print a paste-ready agent handbook for ooxml find.",
            &[],
            direct("read-only documentation command"),
            vec![],
        ),
        spec(
            CoreCommandId::RobotDocs,
            &["robot-docs"],
            "robot-docs",
            "Print the Rust-supported agent guide.",
            &[],
            direct("read-only documentation command"),
            vec![],
        ),
        spec(
            CoreCommandId::RobotDocsGuide,
            &["robot-docs", "guide"],
            "robot-docs guide",
            "Print the Rust-supported agent guide.",
            &[],
            direct("read-only documentation command"),
            vec![],
        ),
        spec(
            CoreCommandId::Completion,
            &["completion"],
            "completion",
            "Generate shell completion scripts for Rust-supported top-level commands.",
            &[],
            group("command group help surface; run a shell leaf to emit a completion script"),
            vec![],
        ),
        spec(
            CoreCommandId::CompletionBash,
            &["completion", "bash"],
            "completion bash",
            "Generate bash shell completion for ooxml.",
            &[],
            direct("shell integration helper"),
            vec![],
        ),
        spec(
            CoreCommandId::CompletionFish,
            &["completion", "fish"],
            "completion fish",
            "Generate fish shell completion for ooxml.",
            &[],
            direct("shell integration helper"),
            vec![],
        ),
        spec(
            CoreCommandId::CompletionPowershell,
            &["completion", "powershell"],
            "completion powershell",
            "Generate PowerShell argument completion for ooxml.",
            &[],
            direct("shell integration helper"),
            vec![],
        ),
        spec(
            CoreCommandId::CompletionZsh,
            &["completion", "zsh"],
            "completion zsh",
            "Generate zsh shell completion for ooxml.",
            &[],
            direct("shell integration helper"),
            vec![],
        ),
        spec(
            CoreCommandId::Conformance,
            &["conformance"],
            "conformance",
            "Show Rust-supported conformance reports.",
            &[],
            group("read-only conformance command group"),
            vec![],
        ),
        spec(
            CoreCommandId::ConformanceCoverage,
            &["conformance", "coverage"],
            "conformance coverage",
            "Show the static Office-repair conformance harness coverage report.",
            &[],
            direct("read-only conformance coverage report"),
            vec![],
        ),
        spec(
            CoreCommandId::ConformanceCheck,
            &["conformance", "check"],
            "conformance check <file> [--office-check] [--office-check-out-dir <dir>]",
            "Run package-open, repo-validation, repair-invariant, and optional local office-open checks for one OOXML package.",
            &["package"],
            direct("read-only package conformance proof; not a mutation op"),
            vec![
                flag(
                    "--office-check",
                    "office-check",
                    "bool",
                    "also run the optional local LibreOffice/soffice open check",
                ),
                flag(
                    "--office-check-out-dir",
                    "office-check-out-dir",
                    "string",
                    "directory for optional local office-open conversion output",
                ),
            ],
        ),
        spec(
            CoreCommandId::Apply,
            &["apply"],
            "apply <file> --ops <ops.json> (--out <file>|--in-place|--dry-run)",
            "Apply a JSON batch of mutation operations to one OOXML package through the same session engine used by serve and MCP.",
            &["package"],
            direct("batch command owns operation dispatch; do not nest inside serve/MCP op"),
            vec![
                flag(
                    "--ops",
                    "ops",
                    "string",
                    "JSON file containing an array of operations",
                ),
                flag("--out", "out", "string", "output package path"),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup path when used with --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "return the operation plan without writing output",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the final package back to the input file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation before publishing output",
                ),
            ],
        ),
        spec(
            CoreCommandId::ConvertXlsmToXlsx,
            &["convert", "xlsm-to-xlsx"],
            "convert xlsm-to-xlsx <input.xlsm> --out <output.xlsx>",
            "Convert XLSM to XLSX by removing VBA package wiring through the proven vba remove workflow.",
            &["package"],
            direct("package conversion alias; run it as a CLI command, not as a serve/MCP op"),
            vec![
                flag("--out", "out", "string", "output .xlsx file path"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "plan conversion without writing output",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation after conversion",
                ),
            ],
        ),
        spec(
            CoreCommandId::RepairNormalize,
            &["repair", "normalize"],
            "repair normalize <file> (--out <file>|--in-place|--dry-run)",
            "Normalize recoverable OOXML package issues, currently XLSX workbook child-element ordering.",
            &["package"],
            mutation(Some(
                "narrow repair command; run validate/conformance after normalization before handing the file to a user",
            )),
            vec![
                flag("--out", "out", "string", "output package path"),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup path when used with --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "report recoverable repairs without writing output",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the normalized package back to the input file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation after writing the normalized package",
                ),
            ],
        ),
        spec(
            CoreCommandId::Template,
            &["template"],
            "template",
            "Extract and apply design tokens across PPTX/XLSX templates.",
            &[],
            group("it is a command group, not a leaf mutation command"),
            vec![],
        ),
        spec(
            CoreCommandId::TemplateApply,
            &["template", "apply"],
            "template apply <file> (--from <template>|--tokens <tokens.json>|--profile <profile.json>) (--out <file>|--in-place|--dry-run)",
            "Apply proven design-token theme colors and fonts to a PPTX/XLSX package.",
            &["package", "style", "chart"],
            mutation(None),
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing output",
                ),
                flag(
                    "--for",
                    "for",
                    "string",
                    "target package family: pptx, xlsx, or auto",
                ),
                flag(
                    "--from",
                    "from",
                    "string",
                    "source template file to read tokens from",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write back to the input file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--profile",
                    "profile",
                    "string",
                    "saved design profile JSON to apply",
                ),
                flag(
                    "--target-colors",
                    "targetColors",
                    "bool",
                    "apply theme colors",
                ),
                flag(
                    "--target-fonts",
                    "targetFonts",
                    "bool",
                    "apply major/minor theme fonts",
                ),
                flag(
                    "--target-ranges",
                    "targetRanges",
                    "bool",
                    "range/cell style transfer is reported as skipped",
                ),
                flag(
                    "--tokens",
                    "tokens",
                    "string",
                    "source TemplateTokens JSON dump",
                ),
            ],
        ),
        spec(
            CoreCommandId::TemplateTokens,
            &["template", "tokens"],
            "template tokens <template-file> [--for <pptx|xlsx>]",
            "Extract reusable design tokens from a PPTX/POTX or XLSX/XLTX template.",
            &["template"],
            direct("read-only template design-token extraction"),
            vec![flag(
                "--for",
                "for",
                "string",
                "template package kind override: pptx or xlsx",
            )],
        ),
        spec(
            CoreCommandId::TemplateProfile,
            &["template", "profile"],
            "template profile",
            "Save and inspect portable design profiles.",
            &[],
            group("it is a command group, not a leaf mutation command"),
            vec![],
        ),
        spec(
            CoreCommandId::TemplateProfileSave,
            &["template", "profile", "save"],
            "template profile save <template-file> [--out <profile.json>]",
            "Save a reusable OOXML design profile extracted from a template package.",
            &["template"],
            direct("artifact-producing read-only extraction"),
            vec![
                flag(
                    "--description",
                    "description",
                    "string",
                    "profile description",
                ),
                flag(
                    "--for",
                    "for",
                    "string",
                    "template package kind override: pptx or xlsx",
                ),
                flag("--name", "name", "string", "profile name"),
                flag("--out", "out", "string", "profile JSON output path"),
            ],
        ),
        spec(
            CoreCommandId::TemplateProfileInspect,
            &["template", "profile", "inspect"],
            "template profile inspect <profile.json>",
            "Validate and print a saved OOXML design profile.",
            &["template"],
            direct("read-only profile inspection"),
            vec![],
        ),
        spec(
            CoreCommandId::Serve,
            &["serve"],
            "serve",
            "Run the JSON-RPC 2.0 stdio session server for web and agent workflows.",
            &[],
            direct("stdio session server; use JSON-RPC methods instead of op argv"),
            vec![],
        ),
        spec(
            CoreCommandId::Mcp,
            &["mcp"],
            "mcp",
            "Run the MCP stdio server backed by the same Rust session engine.",
            &[],
            direct("MCP stdio server; use MCP tools/resources instead of op argv"),
            vec![],
        ),
        spec(
            CoreCommandId::Inspect,
            &["inspect"],
            "inspect <file>",
            "Inspect a supported OOXML package.",
            &["package"],
            direct("read-only command; use inspect_current_with_ooxml through serve"),
            vec![],
        ),
        spec(
            CoreCommandId::Validate,
            &["validate"],
            "validate <file>",
            "Validate an OOXML package.",
            &["package"],
            direct("read-only validation command"),
            vec![],
        ),
        spec(
            CoreCommandId::Diff,
            &["diff"],
            "diff <baseline> <candidate>",
            "Compare two OOXML packages semantically, with optional PPTX visual render diff.",
            &["package"],
            direct("read-only package comparison command; not a serve/MCP mutation op"),
            vec![
                flag(
                    "--render",
                    "render",
                    "bool",
                    "enable PPTX visual diff via rendered slide images",
                ),
                flag(
                    "--threshold",
                    "threshold",
                    "float",
                    "visual diff threshold for PPTX --render",
                ),
                flag(
                    "--out",
                    "out",
                    "string",
                    "output directory for PPTX visual diff artifacts",
                ),
            ],
        ),
        spec(
            CoreCommandId::Verify,
            &["verify"],
            "verify <file>",
            "Validate and compare a package against a baseline where supported.",
            &["package"],
            direct("read-only verification command"),
            vec![flag(
                "--baseline",
                "baseline",
                "string",
                "baseline file to compare against",
            )],
        ),
    ]
}

fn spec(
    id: CoreCommandId,
    path: &'static [&'static str],
    use_text: &'static str,
    short: &'static str,
    target_object_kinds: &'static [&'static str],
    execution: ExecutionSupport,
    local_flags: Vec<FlagSpec>,
) -> CommandSpec {
    CommandSpec {
        id: CommandId::Core(id),
        path,
        use_text,
        short,
        target_object_kinds,
        local_flags,
        execution,
        flag_constraints: None,
    }
}

fn flag(
    name: &'static str,
    arg_name: &'static str,
    flag_type: &'static str,
    description: &'static str,
) -> FlagSpec {
    FlagSpec {
        name,
        arg_name,
        flag_type,
        description,
    }
}

fn direct(reason: &'static str) -> ExecutionSupport {
    ExecutionSupport::DirectOnly {
        reason: Some(reason),
    }
}

fn group(reason: &'static str) -> ExecutionSupport {
    ExecutionSupport::GroupOnly {
        reason: Some(reason),
    }
}

fn mutation(reason: Option<&'static str>) -> ExecutionSupport {
    ExecutionSupport::ServeMutation { reason }
}
