use serde_json::Value;

use super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml version",
            "version",
            "Print the version of ooxml.",
            &[],
            false,
            Some("read-only metadata command"),
            vec![],
        ),
        capability_command(
            "ooxml capabilities",
            "capabilities [--for <filter>]",
            "Emit the Rust-supported machine-readable command and object inventory.",
            &[],
            false,
            Some("read-only self-description command"),
            vec![flag(
                "--for",
                "for",
                "string",
                "filter commands by supported command family or object kind",
            )],
        ),
        capability_command(
            "ooxml doctor",
            "doctor [--only <checks>]",
            "Run read-only environment checks for agent/release workflows.",
            &[],
            false,
            Some("read-only environment advisory command"),
            vec![
                flag(
                    "--only",
                    "only",
                    "string",
                    "comma-separated check ids to run",
                ),
                flag(
                    "--online",
                    "online",
                    "bool",
                    "accepted for Go compatibility; no network checks are performed",
                ),
            ],
        ),
        capability_command(
            "ooxml doctor capabilities",
            "doctor capabilities",
            "Emit the machine-readable doctor contract.",
            &[],
            false,
            Some("read-only doctor self-description command"),
            vec![],
        ),
        capability_command(
            "ooxml doctor health",
            "doctor health [--only <checks>]",
            "Emit a compact doctor health summary and findings exit code.",
            &[],
            false,
            Some("read-only environment advisory command"),
            vec![flag(
                "--only",
                "only",
                "string",
                "comma-separated check ids to run",
            )],
        ),
        capability_command(
            "ooxml doctor robot-docs",
            "doctor robot-docs",
            "Print a paste-ready agent handbook for ooxml doctor.",
            &[],
            false,
            Some("read-only documentation command"),
            vec![],
        ),
        capability_command(
            "ooxml find",
            "find <query> <file> [--type <all|text|formula|name>] [--ignore-case] [--regex] [--max <n>]",
            "Search supported OOXML package text, formulas, and defined names without mutating the package.",
            &["package"],
            false,
            Some(
                "read-only search command; Rust does not yet advertise Go find --to-ops/--apply composition",
            ),
            vec![
                flag(
                    "--type",
                    "type",
                    "string",
                    "search type: all, text, formula, or name",
                ),
                flag(
                    "--ignore-case",
                    "ignoreCase",
                    "bool",
                    "case-insensitive search",
                ),
                flag(
                    "--regex",
                    "regex",
                    "bool",
                    "treat query as a regular expression",
                ),
                flag(
                    "--max",
                    "max",
                    "int",
                    "maximum hits to return; 0 means unlimited",
                ),
            ],
        ),
        capability_command(
            "ooxml find capabilities",
            "find capabilities",
            "Emit the machine-readable find contract.",
            &[],
            false,
            Some("read-only find self-description command"),
            vec![],
        ),
        capability_command(
            "ooxml find robot-docs",
            "find robot-docs",
            "Print a paste-ready agent handbook for ooxml find.",
            &[],
            false,
            Some("read-only documentation command"),
            vec![],
        ),
        capability_command(
            "ooxml robot-docs",
            "robot-docs",
            "Print the Rust-supported agent guide.",
            &[],
            false,
            Some("read-only documentation command"),
            vec![],
        ),
        capability_command(
            "ooxml robot-docs guide",
            "robot-docs guide",
            "Print the Rust-supported agent guide.",
            &[],
            false,
            Some("read-only documentation command"),
            vec![],
        ),
        capability_command(
            "ooxml completion bash",
            "completion bash",
            "Generate bash shell completion for ooxml.",
            &[],
            false,
            Some("shell integration helper"),
            vec![],
        ),
        capability_command(
            "ooxml completion fish",
            "completion fish",
            "Generate fish shell completion for ooxml.",
            &[],
            false,
            Some("shell integration helper"),
            vec![],
        ),
        capability_command(
            "ooxml completion powershell",
            "completion powershell",
            "Generate PowerShell argument completion for ooxml.",
            &[],
            false,
            Some("shell integration helper"),
            vec![],
        ),
        capability_command(
            "ooxml completion zsh",
            "completion zsh",
            "Generate zsh shell completion for ooxml.",
            &[],
            false,
            Some("shell integration helper"),
            vec![],
        ),
        capability_command(
            "ooxml conformance coverage",
            "conformance coverage",
            "Show the static Office-repair conformance harness coverage report.",
            &[],
            false,
            Some("read-only report wrapper; conformance check remains unadvertised in Rust"),
            vec![],
        ),
        capability_command(
            "ooxml apply",
            "apply <file> --ops <ops.json> (--out <file>|--in-place|--dry-run)",
            "Apply a JSON batch of mutation operations to one OOXML package through the same session engine used by serve and MCP.",
            &["package"],
            false,
            Some("batch command owns operation dispatch; do not nest inside serve/MCP op"),
            vec![
                flag(
                    "--ops",
                    "ops",
                    "string",
                    "JSON file containing an array of operations",
                ),
                flag("--out", "out", "string", "output package path"),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup path when used with --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "return the operation plan without writing output",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the final package back to the input file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation before publishing output",
                ),
            ],
        ),
        capability_command(
            "ooxml serve",
            "serve",
            "Run the JSON-RPC 2.0 stdio session server for web and agent workflows.",
            &[],
            false,
            Some("stdio session server; use JSON-RPC methods instead of op argv"),
            vec![],
        ),
        capability_command(
            "ooxml mcp",
            "mcp",
            "Run the MCP stdio server backed by the same Rust session engine.",
            &[],
            false,
            Some("MCP stdio server; use MCP tools/resources instead of op argv"),
            vec![],
        ),
        capability_command(
            "ooxml inspect",
            "inspect <file>",
            "Inspect a supported OOXML package.",
            &["package"],
            false,
            Some("read-only command; use inspect_current_with_ooxml through serve"),
            vec![],
        ),
        capability_command(
            "ooxml validate",
            "validate <file>",
            "Validate an OOXML package.",
            &["package"],
            false,
            Some("read-only validation command"),
            vec![],
        ),
        capability_command(
            "ooxml verify",
            "verify <file>",
            "Validate and compare a package against a baseline where supported.",
            &["package"],
            false,
            Some("read-only verification command"),
            vec![flag(
                "--baseline",
                "baseline",
                "string",
                "baseline file to compare against",
            )],
        ),
    ]
}
