use serde_json::Value;

use super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml version",
            "version",
            "Print the version of ooxml.",
            &[],
            false,
            Some("read-only metadata command"),
            vec![],
        ),
        capability_command(
            "ooxml capabilities",
            "capabilities [--for <filter>]",
            "Emit the Rust-supported machine-readable command and object inventory.",
            &[],
            false,
            Some("read-only self-description command"),
            vec![flag(
                "--for",
                "for",
                "string",
                "filter by command family or object kind; natural plurals and group aliases such as slides, ranges, conditional-formats, and modules are accepted",
            )],
        ),
        capability_command(
            "ooxml help",
            "help [command]",
            "Show Rust-supported command help.",
            &[],
            false,
            Some("read-only help command; parent/group help surfaces are not mutation ops"),
            vec![],
        ),
        capability_command(
            "ooxml doctor",
            "doctor [--only <checks>]",
            "Run read-only environment checks for agent/release workflows.",
            &[],
            false,
            Some("read-only environment advisory command"),
            vec![
                flag(
                    "--only",
                    "only",
                    "string",
                    "comma-separated check ids to run",
                ),
                flag(
                    "--online",
                    "online",
                    "bool",
                    "accepted for Go compatibility; no network checks are performed",
                ),
            ],
        ),
        capability_command(
            "ooxml doctor capabilities",
            "doctor capabilities",
            "Emit the machine-readable doctor contract.",
            &[],
            false,
            Some("read-only doctor self-description command"),
            vec![],
        ),
        capability_command(
            "ooxml doctor health",
            "doctor health [--only <checks>]",
            "Emit a compact doctor health summary and findings exit code.",
            &[],
            false,
            Some("read-only environment advisory command"),
            vec![flag(
                "--only",
                "only",
                "string",
                "comma-separated check ids to run",
            )],
        ),
        capability_command(
            "ooxml doctor robot-docs",
            "doctor robot-docs",
            "Print a paste-ready agent handbook for ooxml doctor.",
            &[],
            false,
            Some("read-only documentation command"),
            vec![],
        ),
        capability_command(
            "ooxml find",
            "find <query> <file> [--type <all|text|formula|name>] [--ignore-case] [--regex] [--max <n>] [--to-ops|--replace <new> --apply (--out <file>|--in-place|--dry-run)]",
            "Search supported OOXML package text, formulas, and defined names; optionally emit or apply generated mutation ops.",
            &["package"],
            false,
            Some(
                "search/compose command with query and file positionals; emit apply-compatible operations with --to-ops, or use the generated mutation commands as apply ops",
            ),
            vec![
                flag(
                    "--type",
                    "type",
                    "string",
                    "search type: all, text, formula, or name",
                ),
                flag(
                    "--ignore-case",
                    "ignoreCase",
                    "bool",
                    "case-insensitive search",
                ),
                flag(
                    "--regex",
                    "regex",
                    "bool",
                    "treat query as a regular expression",
                ),
                flag(
                    "--max",
                    "max",
                    "int",
                    "maximum hits to return; 0 means unlimited",
                ),
                flag(
                    "--to-ops",
                    "toOps",
                    "bool",
                    "emit apply-compatible ops JSON without mutating the package",
                ),
                flag(
                    "--replace",
                    "replace",
                    "string",
                    "replacement value for generated ops",
                ),
                flag(
                    "--apply",
                    "apply",
                    "bool",
                    "run generated ops through the apply engine",
                ),
                flag("--out", "out", "string", "output file for --apply"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write --apply changes in place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "plan --apply without writing",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip final validation for --apply",
                ),
            ],
        ),
        capability_command(
            "ooxml find capabilities",
            "find capabilities",
            "Emit the machine-readable find contract.",
            &[],
            false,
            Some("read-only find self-description command"),
            vec![],
        ),
        capability_command(
            "ooxml find robot-docs",
            "find robot-docs",
            "Print a paste-ready agent handbook for ooxml find.",
            &[],
            false,
            Some("read-only documentation command"),
            vec![],
        ),
        capability_command(
            "ooxml robot-docs",
            "robot-docs",
            "Print the Rust-supported agent guide.",
            &[],
            false,
            Some("read-only documentation command"),
            vec![],
        ),
        capability_command(
            "ooxml robot-docs guide",
            "robot-docs guide",
            "Print the Rust-supported agent guide.",
            &[],
            false,
            Some("read-only documentation command"),
            vec![],
        ),
        capability_command(
            "ooxml completion",
            "completion",
            "Generate shell completion scripts for Rust-supported top-level commands.",
            &[],
            false,
            Some("command group help surface; run a shell leaf to emit a completion script"),
            vec![],
        ),
        capability_command(
            "ooxml completion bash",
            "completion bash",
            "Generate bash shell completion for ooxml.",
            &[],
            false,
            Some("shell integration helper"),
            vec![],
        ),
        capability_command(
            "ooxml completion fish",
            "completion fish",
            "Generate fish shell completion for ooxml.",
            &[],
            false,
            Some("shell integration helper"),
            vec![],
        ),
        capability_command(
            "ooxml completion powershell",
            "completion powershell",
            "Generate PowerShell argument completion for ooxml.",
            &[],
            false,
            Some("shell integration helper"),
            vec![],
        ),
        capability_command(
            "ooxml completion zsh",
            "completion zsh",
            "Generate zsh shell completion for ooxml.",
            &[],
            false,
            Some("shell integration helper"),
            vec![],
        ),
        capability_command(
            "ooxml conformance",
            "conformance",
            "Show Rust-supported conformance reports.",
            &[],
            false,
            Some("read-only conformance command group"),
            vec![],
        ),
        capability_command(
            "ooxml conformance coverage",
            "conformance coverage",
            "Show the static Office-repair conformance harness coverage report.",
            &[],
            false,
            Some("read-only conformance coverage report"),
            vec![],
        ),
        capability_command(
            "ooxml conformance check",
            "conformance check <file> [--office-check] [--office-check-out-dir <dir>]",
            "Run package-open, repo-validation, repair-invariant, and optional local office-open checks for one OOXML package.",
            &["package"],
            false,
            Some("read-only package conformance proof; not a mutation op"),
            vec![
                flag(
                    "--office-check",
                    "office-check",
                    "bool",
                    "also run the optional local LibreOffice/soffice open check",
                ),
                flag(
                    "--office-check-out-dir",
                    "office-check-out-dir",
                    "string",
                    "directory for optional local office-open conversion output",
                ),
            ],
        ),
        capability_command(
            "ooxml apply",
            "apply <file> --ops <ops.json> (--out <file>|--in-place|--dry-run)",
            "Apply a JSON batch of mutation operations to one OOXML package through the same session engine used by serve and MCP.",
            &["package"],
            false,
            Some("batch command owns operation dispatch; do not nest inside serve/MCP op"),
            vec![
                flag(
                    "--ops",
                    "ops",
                    "string",
                    "JSON file containing an array of operations",
                ),
                flag("--out", "out", "string", "output package path"),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup path when used with --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "return the operation plan without writing output",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the final package back to the input file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation before publishing output",
                ),
            ],
        ),
        capability_command(
            "ooxml convert xlsm-to-xlsx",
            "convert xlsm-to-xlsx <input.xlsm> --out <output.xlsx>",
            "Convert XLSM to XLSX by removing VBA package wiring through the proven vba remove workflow.",
            &["package"],
            false,
            Some("package conversion alias; run it as a CLI command, not as a serve/MCP op"),
            vec![
                flag("--out", "out", "string", "output .xlsx file path"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "plan conversion without writing output",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation after conversion",
                ),
            ],
        ),
        capability_command(
            "ooxml repair normalize",
            "repair normalize <file> (--out <file>|--in-place|--dry-run)",
            "Normalize recoverable OOXML package issues, currently XLSX workbook child-element ordering.",
            &["package"],
            true,
            Some(
                "narrow repair command; run validate/conformance after normalization before handing the file to a user",
            ),
            vec![
                flag("--out", "out", "string", "output package path"),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup path when used with --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "report recoverable repairs without writing output",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the normalized package back to the input file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation after writing the normalized package",
                ),
            ],
        ),
        capability_command(
            "ooxml template",
            "template",
            "Extract and apply design tokens across PPTX/XLSX templates.",
            &[],
            false,
            Some("it is a command group, not a leaf mutation command"),
            vec![],
        ),
        capability_command(
            "ooxml template apply",
            "template apply <file> (--from <template>|--tokens <tokens.json>|--profile <profile.json>) (--out <file>|--in-place|--dry-run)",
            "Apply proven design-token theme colors and fonts to a PPTX/XLSX package.",
            &["package", "style", "chart"],
            true,
            None,
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing output",
                ),
                flag(
                    "--for",
                    "for",
                    "string",
                    "target package family: pptx, xlsx, or auto",
                ),
                flag(
                    "--from",
                    "from",
                    "string",
                    "source template file to read tokens from",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write back to the input file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--profile",
                    "profile",
                    "string",
                    "saved design profile JSON to apply",
                ),
                flag(
                    "--target-colors",
                    "targetColors",
                    "bool",
                    "apply theme colors",
                ),
                flag(
                    "--target-fonts",
                    "targetFonts",
                    "bool",
                    "apply major/minor theme fonts",
                ),
                flag(
                    "--target-ranges",
                    "targetRanges",
                    "bool",
                    "range/cell style transfer is reported as skipped",
                ),
                flag(
                    "--tokens",
                    "tokens",
                    "string",
                    "source TemplateTokens JSON dump",
                ),
            ],
        ),
        capability_command(
            "ooxml template tokens",
            "template tokens <template-file> [--for <pptx|xlsx>]",
            "Extract reusable design tokens from a PPTX/POTX or XLSX/XLTX template.",
            &["template"],
            false,
            Some("read-only template design-token extraction"),
            vec![flag(
                "--for",
                "for",
                "string",
                "template package kind override: pptx or xlsx",
            )],
        ),
        capability_command(
            "ooxml template profile",
            "template profile",
            "Save and inspect portable design profiles.",
            &[],
            false,
            Some("it is a command group, not a leaf mutation command"),
            vec![],
        ),
        capability_command(
            "ooxml template profile save",
            "template profile save <template-file> [--out <profile.json>]",
            "Save a reusable OOXML design profile extracted from a template package.",
            &["template"],
            false,
            Some("artifact-producing read-only extraction"),
            vec![
                flag(
                    "--description",
                    "description",
                    "string",
                    "profile description",
                ),
                flag(
                    "--for",
                    "for",
                    "string",
                    "template package kind override: pptx or xlsx",
                ),
                flag("--name", "name", "string", "profile name"),
                flag("--out", "out", "string", "profile JSON output path"),
            ],
        ),
        capability_command(
            "ooxml template profile inspect",
            "template profile inspect <profile.json>",
            "Validate and print a saved OOXML design profile.",
            &["template"],
            false,
            Some("read-only profile inspection"),
            vec![],
        ),
        capability_command(
            "ooxml serve",
            "serve",
            "Run the JSON-RPC 2.0 stdio session server for web and agent workflows.",
            &[],
            false,
            Some("stdio session server; use JSON-RPC methods instead of op argv"),
            vec![],
        ),
        capability_command(
            "ooxml mcp",
            "mcp",
            "Run the MCP stdio server backed by the same Rust session engine.",
            &[],
            false,
            Some("MCP stdio server; use MCP tools/resources instead of op argv"),
            vec![],
        ),
        capability_command(
            "ooxml inspect",
            "inspect <file>",
            "Inspect a supported OOXML package.",
            &["package"],
            false,
            Some("read-only command; use inspect_current_with_ooxml through serve"),
            vec![],
        ),
        capability_command(
            "ooxml validate",
            "validate <file>",
            "Validate an OOXML package.",
            &["package"],
            false,
            Some("read-only validation command"),
            vec![],
        ),
        capability_command(
            "ooxml diff",
            "diff <baseline> <candidate>",
            "Compare two OOXML packages semantically, with optional PPTX visual render diff.",
            &["package"],
            false,
            Some("read-only package comparison command; not a serve/MCP mutation op"),
            vec![
                flag(
                    "--render",
                    "render",
                    "bool",
                    "enable PPTX visual diff via rendered slide images",
                ),
                flag(
                    "--threshold",
                    "threshold",
                    "float",
                    "visual diff threshold for PPTX --render",
                ),
                flag(
                    "--out",
                    "out",
                    "string",
                    "output directory for PPTX visual diff artifacts",
                ),
            ],
        ),
        capability_command(
            "ooxml verify",
            "verify <file>",
            "Validate and compare a package against a baseline where supported.",
            &["package"],
            false,
            Some("read-only verification command"),
            vec![flag(
                "--baseline",
                "baseline",
                "string",
                "baseline file to compare against",
            )],
        ),
    ]
}
