use serde_json::Value;

use super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml docx text",
            "text <file>",
            "Extract DOCX paragraph text.",
            &["package"],
            false,
            Some("read-only command"),
            vec![],
        ),
        capability_command(
            "ooxml docx blocks",
            "blocks <file>",
            "Show stable DOCX body blocks with hashes, selectors, paragraph metadata, table cells, and optional runs.",
            &[],
            false,
            Some("read-only command; block hashes and selectors feed hash-guarded DOCX mutations"),
            vec![
                flag(
                    "--block",
                    "block",
                    "int",
                    "1-based body block index to show",
                ),
                flag(
                    "--include-runs",
                    "includeRuns",
                    "bool",
                    "include paragraph run text and basic run properties",
                ),
            ],
        ),
        capability_command(
            "ooxml docx blocks replace",
            "replace <file>",
            "Replace a hash-guarded DOCX body block with a paragraph.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--block",
                    "block",
                    "int",
                    "1-based body block index from docx blocks",
                ),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: content hash from docx blocks",
                ),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--style",
                    "style",
                    "string",
                    "optional paragraph style ID; default preserves paragraph style when replacing a paragraph",
                ),
                flag("--text", "text", "string", "replacement paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to replacement paragraph text",
                ),
            ],
        ),
        capability_command(
            "ooxml docx blocks delete",
            "delete <file>",
            "Delete a hash-guarded DOCX body block.",
            &["paragraph", "table"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--block",
                    "block",
                    "int",
                    "1-based body block index from docx blocks",
                ),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: content hash from docx blocks",
                ),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
        capability_command(
            "ooxml docx blocks insert-after",
            "insert-after <file>",
            "Insert a paragraph after a hash-guarded DOCX body block.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--block",
                    "block",
                    "int",
                    "1-based body block index from docx blocks; 0 inserts before the first block",
                ),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: content hash from docx blocks when --block is greater than 0",
                ),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--style", "style", "string", "optional paragraph style ID"),
                flag("--text", "text", "string", "paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to paragraph text",
                ),
            ],
        ),
        capability_command(
            "ooxml docx paragraphs append",
            "append <file>",
            "Append a main document body paragraph, preserving trailing section properties.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--text", "text", "string", "paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to paragraph text",
                ),
                flag("--style", "style", "string", "optional paragraph style ID"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx paragraphs insert",
            "insert <file>",
            "Insert a main document body paragraph after a body block index.",
            &["paragraph"],
            true,
            None,
            vec![
                flag(
                    "--insert-after",
                    "insertAfter",
                    "int",
                    "0 to prepend, or a 1-based body block index",
                ),
                flag("--text", "text", "string", "paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to paragraph text",
                ),
                flag("--style", "style", "string", "optional paragraph style ID"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx paragraphs set",
            "set <file>",
            "Replace one main document body paragraph's plain text.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--index", "index", "int", "1-based body block index"),
                flag(
                    "--handle",
                    "handle",
                    "string",
                    "stable DOCX paragraph handle",
                ),
                flag("--text", "text", "string", "replacement paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to replacement paragraph text",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx paragraphs clear",
            "clear <file>",
            "Clear one main document body paragraph's text while retaining paragraph metadata.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--index", "index", "int", "1-based body block index"),
                flag(
                    "--handle",
                    "handle",
                    "string",
                    "stable DOCX paragraph handle",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx styles list",
            "list <file>",
            "List DOCX paragraph, character, table, and numbering styles.",
            &["style"],
            false,
            Some("read-only command; generated style handles can be used by mutation commands"),
            vec![flag(
                "--type",
                "type",
                "string",
                "filter by style type: paragraph, character, table, or numbering",
            )],
        ),
        capability_command(
            "ooxml docx styles show",
            "show <file>",
            "Show detailed info for one DOCX style by styleId.",
            &["style"],
            false,
            Some("read-only command; generated style handles can be used by mutation commands"),
            vec![flag("--style", "style", "string", "styleId to show")],
        ),
        capability_command(
            "ooxml docx styles apply",
            "apply <file>",
            "Apply a paragraph, run, or table style to DOCX body content.",
            &["style", "paragraph", "table"],
            true,
            None,
            vec![
                flag(
                    "--index",
                    "index",
                    "int",
                    "1-based body block index for paragraph/run, or 1-based table number for table",
                ),
                flag(
                    "--handle",
                    "handle",
                    "string",
                    "stable DOCX paragraph handle for paragraph/run targets",
                ),
                flag(
                    "--target",
                    "target",
                    "string",
                    "style target: paragraph, run, or table",
                ),
                flag(
                    "--style",
                    "style",
                    "string",
                    "styleId or H:docx/pt:styles/style:n:<styleId> handle",
                ),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "optional sha256 block hash guard from docx blocks",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip style existence/type validation and post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx comments list",
            "list <file>",
            "List DOCX comments with stable selectors, hashes, and anchor blocks.",
            &["comment"],
            false,
            Some("read-only command; generated comment handles can be used by mutation commands"),
            vec![flag(
                "--comment-id",
                "commentId",
                "int",
                "show only the comment with this numeric w:id",
            )],
        ),
        capability_command(
            "ooxml docx comments add",
            "add <file>",
            "Add a DOCX comment anchored to a body paragraph.",
            &["comment"],
            true,
            None,
            vec![
                flag(
                    "--anchor-block",
                    "anchorBlock",
                    "int",
                    "1-based body block index to anchor to (default: first block)",
                ),
                flag("--author", "author", "string", "comment author name"),
                flag(
                    "--initials",
                    "initials",
                    "string",
                    "optional comment author initials",
                ),
                flag(
                    "--date",
                    "date",
                    "string",
                    "RFC3339 timestamp (default: now)",
                ),
                flag("--text", "text", "string", "comment text"),
                flag("--text-file", "textFile", "string", "path to comment text"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx comments edit",
            "edit <file>",
            "Edit an existing DOCX comment by id or stable handle.",
            &["comment"],
            true,
            None,
            vec![
                flag(
                    "--comment-id",
                    "commentId",
                    "int",
                    "comment id from comments list",
                ),
                flag("--handle", "handle", "string", "stable DOCX comment handle"),
                flag("--text", "text", "string", "new comment text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to new comment text",
                ),
                flag("--author", "author", "string", "new author"),
                flag("--date", "date", "string", "new RFC3339 timestamp"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256 content hash from comments list",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx comments remove",
            "remove <file>",
            "Remove an existing DOCX comment and its range/reference markers.",
            &["comment"],
            true,
            None,
            vec![
                flag(
                    "--comment-id",
                    "commentId",
                    "int",
                    "comment id from comments list",
                ),
                flag("--handle", "handle", "string", "stable DOCX comment handle"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256 content hash from comments list",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx fields list",
            "list <file>",
            "List all simple/complex fields in document body + headers/footers.",
            &["field"],
            false,
            Some(
                "read-only command; cached field results are stale until Word recalculates fields",
            ),
            vec![flag(
                "--type",
                "type",
                "string",
                "show only fields whose leading instruction keyword matches",
            )],
        ),
        capability_command(
            "ooxml docx fields insert",
            "insert <file>",
            "Insert a simple DOCX field into a body, header, or footer paragraph.",
            &["field", "paragraph"],
            true,
            None,
            vec![
                flag(
                    "--location",
                    "location",
                    "string",
                    "target part:block location, e.g. body:2 or header1:1",
                ),
                flag(
                    "--field-code",
                    "fieldCode",
                    "string",
                    "field instruction, e.g. PAGE",
                ),
                flag("--result", "result", "string", "initial cached result text"),
                flag("--out", "out", "string", "output file path"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx fields set-result",
            "set-result <file>",
            "Set the cached result text of a simple or complex DOCX field.",
            &["field", "paragraph"],
            true,
            None,
            vec![
                flag(
                    "--selector",
                    "selector",
                    "string",
                    "field selector part:block:field, e.g. body:1:0",
                ),
                flag("--result", "result", "string", "new cached result text"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256 of instruction plus cached result",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx headers list",
            "list <file>",
            "List headers and footers defined per section.",
            &["header", "footer"],
            false,
            Some(
                "read-only command; generated header/footer selectors can be pasted into show or set-text",
            ),
            vec![],
        ),
        capability_command(
            "ooxml docx headers show",
            "show <file>",
            "Show header content by type, section, or relationship id.",
            &["header", "paragraph"],
            false,
            Some("read-only command; accepts selectors from docx headers list"),
            vec![
                flag(
                    "--id",
                    "id",
                    "string",
                    "relationship id to resolve directly",
                ),
                flag(
                    "--section",
                    "section",
                    "int",
                    "1-based section index; 0 means the last section",
                ),
                flag(
                    "--selector",
                    "selector",
                    "string",
                    "selector from headers/footers list",
                ),
                flag("--type", "type", "string", "default, first, or even"),
            ],
        ),
        capability_command(
            "ooxml docx headers set-text",
            "set-text <file>",
            "Set header paragraph text by index.",
            &["header", "paragraph"],
            true,
            None,
            docx_header_footer_set_text_flags(),
        ),
        capability_command(
            "ooxml docx footers list",
            "list <file>",
            "List headers and footers defined per section.",
            &["footer", "header"],
            false,
            Some(
                "read-only command; generated header/footer selectors can be pasted into show or set-text",
            ),
            vec![],
        ),
        capability_command(
            "ooxml docx footers show",
            "show <file>",
            "Show footer content by type, section, or relationship id.",
            &["footer", "paragraph"],
            false,
            Some("read-only command; accepts selectors from docx footers list"),
            vec![
                flag(
                    "--id",
                    "id",
                    "string",
                    "relationship id to resolve directly",
                ),
                flag(
                    "--section",
                    "section",
                    "int",
                    "1-based section index; 0 means the last section",
                ),
                flag(
                    "--selector",
                    "selector",
                    "string",
                    "selector from headers/footers list",
                ),
                flag("--type", "type", "string", "default, first, or even"),
            ],
        ),
        capability_command(
            "ooxml docx footers set-text",
            "set-text <file>",
            "Set footer paragraph text by index.",
            &["footer", "paragraph"],
            true,
            None,
            docx_header_footer_set_text_flags(),
        ),
        capability_command(
            "ooxml docx images list",
            "list <file>",
            "List inline images in a DOCX document.",
            &["image", "paragraph"],
            false,
            Some(
                "read-only command; image records include relationship ids, media parts, dimensions, and block anchors",
            ),
            vec![],
        ),
        capability_command(
            "ooxml docx tables show",
            "show <file>",
            "Show DOCX tables by table index, body block index, dimensions, merged-cell flag, and cell text.",
            &[],
            false,
            Some(
                "read-only command; call via inspect in serve/MCP; generated table hashes feed hash-guarded DOCX table mutations",
            ),
            vec![
                flag(
                    "--details",
                    "details",
                    "bool",
                    "include detailed table object in JSON output",
                ),
                flag(
                    "--table",
                    "table",
                    "int",
                    "1-based table number; omitted shows all tables",
                ),
            ],
        ),
        capability_command(
            "ooxml docx tables set-cell",
            "set-cell <file>",
            "Set one main-document DOCX table cell's plain text.",
            &["table"],
            true,
            None,
            vec![
                flag("--table", "table", "int", "1-based table number"),
                flag("--row", "row", "int", "1-based table row"),
                flag("--col", "col", "int", "1-based table column"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: table block hash from docx tables show or docx blocks",
                ),
                flag("--text", "text", "string", "replacement cell text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to replacement cell text",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx tables clear-cell",
            "clear-cell <file>",
            "Clear one main-document DOCX table cell's text.",
            &["table"],
            true,
            None,
            vec![
                flag("--table", "table", "int", "1-based table number"),
                flag("--row", "row", "int", "1-based table row"),
                flag("--col", "col", "int", "1-based table column"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: table block hash from docx tables show or docx blocks",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
    ]
}
fn docx_header_footer_set_text_flags() -> Vec<Value> {
    vec![
        flag(
            "--id",
            "id",
            "string",
            "relationship id to resolve directly",
        ),
        flag("--type", "type", "string", "default, first, or even"),
        flag(
            "--section",
            "section",
            "int",
            "1-based section index; 0 means the last section",
        ),
        flag(
            "--index",
            "index",
            "int",
            "1-based paragraph index within the part",
        ),
        flag(
            "--selector",
            "selector",
            "string",
            "selector from headers/footers list",
        ),
        flag("--text", "text", "string", "replacement text"),
        flag(
            "--text-file",
            "textFile",
            "string",
            "path to replacement text",
        ),
        flag("--out", "out", "string", "output file path"),
        flag(
            "--in-place",
            "inPlace",
            "bool",
            "write the input file in place",
        ),
        flag("--backup", "backup", "string", "backup path for --in-place"),
        flag("--dry-run", "dryRun", "bool", "plan without writing"),
        flag(
            "--no-validate",
            "noValidate",
            "bool",
            "skip post-write validation",
        ),
    ]
}
