use serde_json::Value;

use super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml vba",
            "vba",
            "Inspect and edit Rust-supported VBA macro project surfaces.",
            &[],
            false,
            Some("command group help surface; run a VBA leaf command for work"),
            vec![],
        ),
        capability_command(
            "ooxml vba build-bin",
            "build-bin --family xlsx|pptx --source Module1.bas --out vbaProject.bin",
            "Build a source-only vbaProject.bin from .bas/.cls source files using pure Rust.",
            &["module"],
            true,
            Some(
                "pure Rust authoring path; attach the output with vba attach, then prove with Office before claiming compatibility",
            ),
            vec![
                flag(
                    "--family",
                    "family",
                    "string",
                    "target host family; currently xlsx or pptx",
                ),
                flag(
                    "--force",
                    "force",
                    "bool",
                    "overwrite an existing vbaProject.bin output",
                ),
                flag("--out", "out", "string", "output vbaProject.bin path"),
                flag(
                    "--source",
                    "source",
                    "stringArray",
                    "repeatable .bas or .cls source file",
                ),
            ],
        ),
        capability_command(
            "ooxml vba create",
            "create <workbook.xlsx|deck.pptx> --pure --source Module1.bas --out <workbook.xlsm|deck.pptm>",
            "Create an XLSM/PPTM from an existing package and .bas/.cls source files using pure Rust.",
            &["package", "module"],
            true,
            Some(
                "preferred cross-platform macro authoring path for XLSM/PPTM; legacy Office-COM create remains available without --pure",
            ),
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--enable-vba-object-model-access",
                    "enableVbaObjectModelAccess",
                    "bool",
                    "legacy Office-COM mode only: temporarily enable Trust access to the VBA project object model",
                ),
                flag(
                    "--extract-bin",
                    "extractBin",
                    "string",
                    "legacy Office-COM mode only: optional path to write the created vbaProject.bin seed",
                ),
                flag(
                    "--family",
                    "family",
                    "string",
                    "target Office family; pure mode supports xlsx or pptx and can infer from input extension",
                ),
                flag(
                    "--force",
                    "force",
                    "bool",
                    "legacy Office-COM mode only: overwrite existing helper outputs",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write back to the input package",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict package validation after mutation",
                ),
                flag(
                    "--office-create-script",
                    "officeCreateScript",
                    "string",
                    "legacy Office-COM mode only: path to windows-office-vba-create.ps1",
                ),
                flag(
                    "--out",
                    "out",
                    "string",
                    "pure mode output macro-enabled package path",
                ),
                flag(
                    "--pure",
                    "pure",
                    "bool",
                    "build vbaProject.bin in Rust and attach it to the input package",
                ),
                flag(
                    "--source",
                    "source",
                    "stringArray",
                    "repeatable .bas or .cls source file to import",
                ),
                flag(
                    "--visible",
                    "visible",
                    "bool",
                    "show the Office application window during creation",
                ),
            ],
        ),
        capability_command(
            "ooxml vba rebuild",
            "rebuild <workbook.xlsm|deck.pptm> --source-dir macros --out <edited.xlsm|edited.pptm>",
            "Rebuild a macro-enabled package from a directory of .bas/.cls sources using pure Rust.",
            &["package", "module"],
            true,
            Some(
                "safe module-set replacement path; rebuilds a fresh source-only vbaProject.bin rather than patching Office-authored binary metadata",
            ),
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--family",
                    "family",
                    "string",
                    "target Office family; supports xlsx or pptx and can infer from input extension",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write back to the input package",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict package validation after mutation",
                ),
                flag(
                    "--out",
                    "out",
                    "string",
                    "output macro-enabled package path",
                ),
                flag(
                    "--source-dir",
                    "sourceDir",
                    "string",
                    "directory recursively scanned for .bas and .cls source files",
                ),
            ],
        ),
        capability_command(
            "ooxml vba inspect",
            "inspect <file>",
            "Inspect opaque VBA package state for XLSM/PPTM package wiring.",
            &["package", "module"],
            false,
            Some("read-only command; use vba attach/remove for package mutation"),
            vec![],
        ),
        capability_command(
            "ooxml vba extract-bin",
            "extract-bin <file>",
            "Extract opaque vbaProject.bin bytes.",
            &["package", "module"],
            false,
            Some("read-only binary extraction command"),
            vec![flag("--out", "out", "string", "output vbaProject.bin path")],
        ),
        capability_command(
            "ooxml vba inspect-bin",
            "inspect-bin <vbaProject.bin>",
            "Inspect a standalone parseable vbaProject.bin before package attach.",
            &["module"],
            false,
            Some("read-only source-module inspection command"),
            vec![flag(
                "--family",
                "family",
                "string",
                "target host family for compatibility checks: pptx or xlsx",
            )],
        ),
        capability_command(
            "ooxml vba list",
            "list <file>",
            "List parseable VBA source modules with selectors and SHA-256 digests.",
            &["package", "module"],
            false,
            Some("read-only source-module listing command"),
            vec![],
        ),
        capability_command(
            "ooxml vba extract",
            "extract <file>",
            "Extract parseable VBA source modules to .bas/.cls files.",
            &["package", "module"],
            false,
            Some("source extraction writes .bas/.cls files but does not mutate the Office package"),
            vec![
                flag(
                    "--module",
                    "module",
                    "string",
                    "optional module selector from vba list",
                ),
                flag(
                    "--out-dir",
                    "outDir",
                    "string",
                    "directory for extracted .bas/.cls modules",
                ),
            ],
        ),
        capability_command(
            "ooxml vba add-module",
            "add-module <file>",
            "Experimental source-stream rewrite for non-Office-shaped VBA projects; Office-authored projects are guarded.",
            &["package", "module"],
            false,
            Some(
                "not a first-class macro authoring path; use vba create --pure for XLSM or vba attach for opaque seeds",
            ),
            vec![
                flag(
                    "--allow-experimental-vba-source-rewrite",
                    "allowExperimentalVbaSourceRewrite",
                    "bool",
                    "allow source rewriting that is package-valid but not Office-load verified",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--expect-module-count",
                    "expectModuleCount",
                    "integer",
                    "guard on the current module count before adding",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--kind",
                    "kind",
                    "string",
                    "module kind: standard/bas or class/cls",
                ),
                flag("--name", "name", "string", "module name to add"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--source", "source", "string", ".bas/.cls source file"),
            ],
        ),
        capability_command(
            "ooxml vba replace-module",
            "replace-module <file>",
            "Experimental source-stream rewrite for non-Office-shaped VBA projects; Office-authored projects are guarded.",
            &["package", "module"],
            false,
            Some(
                "not a first-class macro authoring path; use vba create --pure for XLSM or vba attach for opaque seeds",
            ),
            vec![
                flag(
                    "--allow-experimental-vba-source-rewrite",
                    "allowExperimentalVbaSourceRewrite",
                    "bool",
                    "allow source rewriting that is package-valid but not Office-load verified",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--expect-sha256",
                    "expectSha256",
                    "string",
                    "guard on the current decoded module-source SHA-256",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--module",
                    "module",
                    "string",
                    "module selector from vba list",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--source", "source", "string", ".bas/.cls source file"),
            ],
        ),
        capability_command(
            "ooxml vba remove-module",
            "remove-module <file>",
            "Experimental source-stream rewrite for non-Office-shaped VBA projects; Office-authored projects are guarded.",
            &["package", "module"],
            false,
            Some(
                "not a first-class macro authoring path; use vba create --pure for XLSM, vba attach for opaque seeds, or vba remove for package-level removal",
            ),
            vec![
                flag(
                    "--allow-experimental-vba-source-rewrite",
                    "allowExperimentalVbaSourceRewrite",
                    "bool",
                    "allow source rewriting that is package-valid but not Office-load verified",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--expect-sha256",
                    "expectSha256",
                    "string",
                    "guard on the current decoded module-source SHA-256",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--module",
                    "module",
                    "string",
                    "module selector from vba list",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
        capability_command(
            "ooxml vba office-check",
            "office-check <file>",
            "Validate a macro package and run a local LibreOffice/soffice open-check when available.",
            &["module"],
            false,
            Some("read-only compatibility evidence; macros are not executed or compiled"),
            vec![flag(
                "--out-dir",
                "outDir",
                "string",
                "optional directory to keep LibreOffice conversion output for inspection",
            )],
        ),
        capability_command(
            "ooxml vba attach",
            "attach <file>",
            "Attach or replace opaque vbaProject.bin and macro package wiring.",
            &["package", "module"],
            true,
            None,
            vec![
                flag(
                    "--allow-host-family-risk",
                    "allowHostFamilyRisk",
                    "bool",
                    "accepted for Go CLI compatibility; opaque Rust attach does not parse source-project host risk yet",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag("--bin", "bin", "string", "vbaProject.bin to attach"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
        capability_command(
            "ooxml vba remove",
            "remove <file>",
            "Remove opaque VBA package wiring and restore non-macro main content type.",
            &["package", "module"],
            true,
            None,
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
    ]
}
