use serde_json::Value;

use super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml vba create",
            "create <output.xlsm|output.pptm>",
            "Create an Office-authored XLSM/PPTM from .bas/.cls source files using the Windows Office helper.",
            &["package", "module"],
            false,
            Some(
                "requires Windows desktop Office automation and does not accept op mutation output flags",
            ),
            vec![
                flag(
                    "--enable-vba-object-model-access",
                    "enableVbaObjectModelAccess",
                    "bool",
                    "temporarily enable Trust access to the VBA project object model",
                ),
                flag(
                    "--extract-bin",
                    "extractBin",
                    "string",
                    "optional path to write the created vbaProject.bin seed",
                ),
                flag(
                    "--family",
                    "family",
                    "string",
                    "target Office family: xlsx or pptx; inferred from .xlsm/.pptm output",
                ),
                flag(
                    "--force",
                    "force",
                    "bool",
                    "overwrite existing helper outputs",
                ),
                flag(
                    "--office-create-script",
                    "officeCreateScript",
                    "string",
                    "path to windows-office-vba-create.ps1 when not running from the repo checkout",
                ),
                flag(
                    "--source",
                    "source",
                    "stringArray",
                    "repeatable .bas or .cls source file to import",
                ),
                flag(
                    "--visible",
                    "visible",
                    "bool",
                    "show the Office application window during creation",
                ),
            ],
        ),
        capability_command(
            "ooxml vba inspect",
            "inspect <file>",
            "Inspect opaque VBA package state for XLSM/PPTM package wiring.",
            &["package", "module"],
            false,
            Some("read-only command; use vba attach/remove for package mutation"),
            vec![],
        ),
        capability_command(
            "ooxml vba extract-bin",
            "extract-bin <file>",
            "Extract opaque vbaProject.bin bytes.",
            &["package", "module"],
            false,
            Some("read-only binary extraction command"),
            vec![flag("--out", "out", "string", "output vbaProject.bin path")],
        ),
        capability_command(
            "ooxml vba inspect-bin",
            "inspect-bin <vbaProject.bin>",
            "Inspect a standalone parseable vbaProject.bin before package attach.",
            &["module"],
            false,
            Some("read-only source-module inspection command"),
            vec![flag(
                "--family",
                "family",
                "string",
                "target host family for compatibility checks: pptx or xlsx",
            )],
        ),
        capability_command(
            "ooxml vba list",
            "list <file>",
            "List parseable VBA source modules with selectors and SHA-256 digests.",
            &["package", "module"],
            false,
            Some("read-only source-module listing command"),
            vec![],
        ),
        capability_command(
            "ooxml vba extract",
            "extract <file>",
            "Extract parseable VBA source modules to .bas/.cls files.",
            &["package", "module"],
            false,
            Some("source extraction writes .bas/.cls files but does not mutate the Office package"),
            vec![
                flag(
                    "--module",
                    "module",
                    "string",
                    "optional module selector from vba list",
                ),
                flag(
                    "--out-dir",
                    "outDir",
                    "string",
                    "directory for extracted .bas/.cls modules",
                ),
            ],
        ),
        capability_command(
            "ooxml vba office-check",
            "office-check <file>",
            "Validate a macro package and run a local LibreOffice/soffice open-check when available.",
            &["module"],
            false,
            Some("read-only compatibility evidence; macros are not executed or compiled"),
            vec![flag(
                "--out-dir",
                "outDir",
                "string",
                "optional directory to keep LibreOffice conversion output for inspection",
            )],
        ),
        capability_command(
            "ooxml vba attach",
            "attach <file>",
            "Attach or replace opaque vbaProject.bin and macro package wiring.",
            &["package", "module"],
            true,
            None,
            vec![
                flag(
                    "--allow-host-family-risk",
                    "allowHostFamilyRisk",
                    "bool",
                    "accepted for Go CLI compatibility; opaque Rust attach does not parse source-project host risk yet",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag("--bin", "bin", "string", "vbaProject.bin to attach"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
        capability_command(
            "ooxml vba remove",
            "remove <file>",
            "Remove opaque VBA package wiring and restore non-macro main content type.",
            &["package", "module"],
            true,
            None,
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
    ]
}
