use serde_json::{Value, json};

use super::{capability_command, capability_command_with_flag_constraints, flag};

pub(super) fn commands() -> Vec<Value> {
    let create = capability_command_with_flag_constraints(
        "ooxml vba create",
        "create <workbook.xlsx|deck.pptx|document.docx> --pure --source Module1.bas --out <workbook.xlsm|deck.pptm|document.docm>",
        "Create an XLSM/PPTM/DOCM from an existing package and VBA source files using pure Rust.",
        &["package", "module"],
        true,
        Some(
            "preferred cross-platform macro authoring path; legacy Office-COM create remains available without --pure for XLSM/PPTM seeds",
        ),
        vec![
            flag("--backup", "backup", "string", "backup path for --in-place"),
            flag(
                "--dry-run",
                "dryRun",
                "bool",
                "pure mode only: validate and report without writing",
            ),
            flag(
                "--enable-vba-object-model-access",
                "enableVbaObjectModelAccess",
                "bool",
                "legacy Office-COM mode only: temporarily enable Trust access to the VBA project object model",
            ),
            flag(
                "--extract-bin",
                "extractBin",
                "string",
                "legacy Office-COM mode only: optional path to write the created vbaProject.bin seed",
            ),
            flag(
                "--family",
                "family",
                "string",
                "target Office family; pure mode supports xlsx, pptx, or docx and can infer from input extension",
            ),
            flag(
                "--force",
                "force",
                "bool",
                "legacy Office-COM mode only: overwrite existing helper outputs",
            ),
            flag(
                "--in-place",
                "inPlace",
                "bool",
                "write back to the input package",
            ),
            flag(
                "--no-validate",
                "noValidate",
                "bool",
                "skip strict package validation after mutation",
            ),
            flag(
                "--office-create-script",
                "officeCreateScript",
                "string",
                "legacy Office-COM mode only: path to windows-office-vba-create.ps1",
            ),
            flag(
                "--out",
                "out",
                "string",
                "pure mode output macro-enabled package path",
            ),
            flag(
                "--pure",
                "pure",
                "bool",
                "build vbaProject.bin in Rust and attach it to the input package",
            ),
            flag(
                "--source",
                "source",
                "stringArray",
                "repeatable .bas/.cls source file, plus package/list/extract-only .frm for pure XLSM mode; legacy Office-COM mode supports .bas/.cls",
            ),
            flag(
                "--visible",
                "visible",
                "bool",
                "show the Office application window during creation",
            ),
        ],
        Some(json!({
            "modes": [
                {
                    "name": "pure",
                    "when": ["--pure"],
                    "allowedFlags": ["--pure", "--source", "--family", "--out", "--in-place", "--backup", "--dry-run", "--no-validate"],
                    "conflictsWith": ["--extract-bin", "--office-create-script", "--enable-vba-object-model-access", "--visible", "--force"],
                    "recommendedCommand": "ooxml --json vba create <input.xlsx|input.pptx|input.docx> --pure --source Module1.bas --out <output.xlsm|output.pptm|output.docm>"
                },
                {
                    "name": "legacy-office-com",
                    "when": ["not --pure"],
                    "allowedFlags": ["--family", "--source", "--extract-bin", "--office-create-script", "--enable-vba-object-model-access", "--visible", "--force"],
                    "conflictsWith": ["--out", "--backup", "--dry-run", "--no-validate", "--in-place"],
                    "recommendedCommand": "ooxml --json vba create <input.xlsx|input.pptx> <output.xlsm|output.pptm> --office-create-script <windows-office-vba-create.ps1>"
                }
            ],
            "rules": [
                "--pure cannot be combined with legacy Office-COM create flags.",
                "Pure mode writes with --out, --in-place, or --dry-run; legacy Office-COM mode uses the positional output path."
            ]
        })),
    );
    vec![
        capability_command(
            "ooxml vba",
            "vba",
            "Inspect and edit Rust-supported VBA macro project surfaces.",
            &[],
            false,
            Some("command group help surface; run a VBA leaf command for work"),
            vec![],
        ),
        capability_command(
            "ooxml vba build-bin",
            "build-bin --family xlsx|pptx|docx --source Module1.bas --out vbaProject.bin",
            "Build a source-only vbaProject.bin from source files using pure Rust.",
            &["module"],
            true,
            Some(
                "pure Rust authoring path; attach the output with vba attach, then prove with Office before claiming compatibility",
            ),
            vec![
                flag(
                    "--family",
                    "family",
                    "string",
                    "target host family; xlsx, pptx, and docx support .bas and .cls source, with host modules synthesized where required",
                ),
                flag(
                    "--force",
                    "force",
                    "bool",
                    "overwrite an existing vbaProject.bin output",
                ),
                flag("--out", "out", "string", "output vbaProject.bin path"),
                flag(
                    "--source",
                    "source",
                    "stringArray",
                    "repeatable .bas or .cls source file",
                ),
            ],
        ),
        create,
        capability_command(
            "ooxml vba rebuild",
            "rebuild <workbook.xlsm|deck.pptm|document.docm> --source-dir macros --out <edited.xlsm|edited.pptm|edited.docm>",
            "Rebuild a macro-enabled package from a directory of .bas/.cls sources using pure Rust.",
            &["package", "module"],
            true,
            Some(
                "safe module-set replacement path; rebuilds a fresh source-only vbaProject.bin rather than patching Office-authored binary metadata",
            ),
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--family",
                    "family",
                    "string",
                    "target Office family; supports xlsx, pptx, or docx and can infer from input extension",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write back to the input package",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict package validation after mutation",
                ),
                flag(
                    "--out",
                    "out",
                    "string",
                    "output macro-enabled package path",
                ),
                flag(
                    "--source-dir",
                    "sourceDir",
                    "string",
                    "directory recursively scanned for .bas and .cls source files",
                ),
            ],
        ),
        capability_command(
            "ooxml vba inspect",
            "inspect <file>",
            "Inspect opaque VBA package state for XLSM/PPTM/DOCM package wiring.",
            &["package", "module"],
            false,
            Some("read-only command; use vba attach/remove for package mutation"),
            vec![],
        ),
        capability_command(
            "ooxml vba extract-bin",
            "extract-bin <file>",
            "Extract opaque vbaProject.bin bytes.",
            &["package", "module"],
            false,
            Some("read-only binary extraction command"),
            vec![flag("--out", "out", "string", "output vbaProject.bin path")],
        ),
        capability_command(
            "ooxml vba inspect-bin",
            "inspect-bin <vbaProject.bin>",
            "Inspect a standalone parseable vbaProject.bin before package attach.",
            &["module"],
            false,
            Some("read-only source-module inspection command"),
            vec![flag(
                "--family",
                "family",
                "string",
                "target host family for compatibility checks: pptx, docx, or xlsx",
            )],
        ),
        capability_command(
            "ooxml vba list",
            "list <file>",
            "List parseable VBA source modules with selectors and SHA-256 digests.",
            &["package", "module"],
            false,
            Some("read-only source-module listing command"),
            vec![],
        ),
        capability_command(
            "ooxml vba extract",
            "extract <file>",
            "Extract parseable VBA source modules to .bas/.cls files.",
            &["package", "module"],
            false,
            Some("source extraction writes .bas/.cls files but does not mutate the Office package"),
            vec![
                flag(
                    "--module",
                    "module",
                    "string",
                    "optional module selector from vba list",
                ),
                flag(
                    "--out-dir",
                    "outDir",
                    "string",
                    "directory for extracted .bas/.cls modules",
                ),
            ],
        ),
        capability_command(
            "ooxml vba add-module",
            "add-module <file>",
            "Experimental source-stream rewrite for non-Office-shaped VBA projects; Office-authored projects are guarded.",
            &["package", "module"],
            false,
            Some(
                "not a first-class macro authoring path; use vba create --pure or vba attach for opaque seeds",
            ),
            vec![
                flag(
                    "--allow-experimental-vba-source-rewrite",
                    "allowExperimentalVbaSourceRewrite",
                    "bool",
                    "allow source rewriting that is package-valid but not Office-load verified",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--expect-module-count",
                    "expectModuleCount",
                    "integer",
                    "guard on the current module count before adding",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--kind",
                    "kind",
                    "string",
                    "module kind: standard/bas or class/cls",
                ),
                flag("--name", "name", "string", "module name to add"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--source", "source", "string", ".bas/.cls source file"),
            ],
        ),
        capability_command(
            "ooxml vba replace-module",
            "replace-module <file>",
            "Experimental source-stream rewrite for non-Office-shaped VBA projects; Office-authored projects are guarded.",
            &["package", "module"],
            false,
            Some(
                "not a first-class macro authoring path; use vba create --pure or vba attach for opaque seeds",
            ),
            vec![
                flag(
                    "--allow-experimental-vba-source-rewrite",
                    "allowExperimentalVbaSourceRewrite",
                    "bool",
                    "allow source rewriting that is package-valid but not Office-load verified",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--expect-sha256",
                    "expectSha256",
                    "string",
                    "guard on the current decoded module-source SHA-256",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--module",
                    "module",
                    "string",
                    "module selector from vba list",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--source", "source", "string", ".bas/.cls source file"),
            ],
        ),
        capability_command(
            "ooxml vba remove-module",
            "remove-module <file>",
            "Experimental source-stream rewrite for non-Office-shaped VBA projects; Office-authored projects are guarded.",
            &["package", "module"],
            false,
            Some(
                "not a first-class macro authoring path; use vba create --pure, vba attach for opaque seeds, or vba remove for package-level removal",
            ),
            vec![
                flag(
                    "--allow-experimental-vba-source-rewrite",
                    "allowExperimentalVbaSourceRewrite",
                    "bool",
                    "allow source rewriting that is package-valid but not Office-load verified",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--expect-sha256",
                    "expectSha256",
                    "string",
                    "guard on the current decoded module-source SHA-256",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--module",
                    "module",
                    "string",
                    "module selector from vba list",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
        capability_command(
            "ooxml vba office-check",
            "office-check <file>",
            "Validate a macro package and run a local Office-open check when available.",
            &["module"],
            false,
            Some(
                "read-only compatibility evidence; on Windows this prefers Microsoft Office COM, but macros are not executed",
            ),
            vec![flag(
                "--out-dir",
                "outDir",
                "string",
                "optional directory to keep Office-open check output for inspection",
            )],
        ),
        capability_command(
            "ooxml vba run-smoke",
            "run-smoke [file.xlsm]",
            "Explicit opt-in Excel VBA macro execution smoke for a harmless generated or provided XLSM.",
            &["module"],
            false,
            Some(
                "Windows desktop Excel proof gate; executes VBA through Office COM, so use only when the user explicitly asks for macro execution proof",
            ),
            vec![
                flag(
                    "--expected-cell",
                    "expectedCell",
                    "string",
                    "Excel cell to verify after the macro run; default A1",
                ),
                flag(
                    "--expected-value",
                    "expectedValue",
                    "string",
                    "expected cell or marker value after the macro run",
                ),
                flag(
                    "--macro",
                    "macro",
                    "string",
                    "macro name to run in a provided .xlsm; generated smoke workbooks use AgentSmokeRun",
                ),
                flag(
                    "--out-dir",
                    "outDir",
                    "string",
                    "directory for smoke artifacts and summary.json",
                ),
                flag(
                    "--smoke-mode",
                    "smokeMode",
                    "string",
                    "generated smoke mode when no file is supplied: Standard or Class; omit for provided .xlsm files",
                ),
                flag(
                    "--timeout-seconds",
                    "timeoutSeconds",
                    "integer",
                    "bounded Office COM macro-run timeout; default 120",
                ),
                flag(
                    "--visible",
                    "visible",
                    "bool",
                    "show Excel during the macro-run smoke",
                ),
            ],
        ),
        capability_command(
            "ooxml vba attach",
            "attach <file>",
            "Attach or replace opaque vbaProject.bin and macro package wiring.",
            &["package", "module"],
            true,
            None,
            vec![
                flag(
                    "--allow-host-family-risk",
                    "allowHostFamilyRisk",
                    "bool",
                    "accepted for legacy CLI compatibility; opaque Rust attach does not parse source-project host risk yet",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag("--bin", "bin", "string", "vbaProject.bin to attach"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
        capability_command(
            "ooxml vba remove",
            "remove <file>",
            "Remove opaque VBA package wiring and restore non-macro main content type.",
            &["package", "module"],
            true,
            None,
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing an output file",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "modify the input file in place",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
    ]
}
