mod tables;

use serde_json::Value;

use super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    let mut commands = vec![
        capability_command(
            "ooxml xlsx sheets list",
            "list <file>",
            "List workbook sheets and selectors.",
            &["sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![],
        ),
        capability_command(
            "ooxml xlsx sheets show",
            "show <file>",
            "Show worksheet metadata, used ranges, and generated readback commands.",
            &["sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
        ),
        capability_command(
            "ooxml xlsx sheets add",
            "add <file> --name <name>",
            "Add an empty worksheet and wire workbook.xml, workbook relationships, and content types.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--name", "name", "string", "new worksheet name"),
                flag(
                    "--after",
                    "after",
                    "string",
                    "insert after sheet selector; omitted appends",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx sheets rename",
            "rename <file> --sheet <sheet> --name <name>",
            "Rename a workbook worksheet by sheet selector.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--name", "name", "string", "new worksheet name"),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx sheets move",
            "move <file> --sheet <sheet> (--to <n>|--before <sheet>|--after <sheet>)",
            "Move a workbook sheet in tab order while preserving its part, sheetId, and relationship ID.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--to", "to", "int", "final 1-based workbook sheet position"),
                flag(
                    "--before",
                    "before",
                    "string",
                    "move before this sheet selector",
                ),
                flag(
                    "--after",
                    "after",
                    "string",
                    "move after this sheet selector",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx sheets delete",
            "delete <file> --sheet <sheet>",
            "Delete one worksheet and remove its workbook relationship, worksheet part, worksheet relationships, and calcChain.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx colwidths show",
            "show <file> --sheet <sheet> --range <columns>",
            "Show resolved worksheet column widths for a column range.",
            &["sheet", "range"],
            false,
            Some("read-only command; direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "column span such as B or B:D"),
            ],
        ),
        capability_command(
            "ooxml xlsx colwidths set",
            "set <file> --sheet <sheet> --range <columns> --width <width>",
            "Set a uniform worksheet column width for a column range.",
            &["sheet", "range"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "column span such as B or B:D"),
                flag(
                    "--width",
                    "width",
                    "number",
                    "column width in character units (0-255)",
                ),
                flag(
                    "--expect-width",
                    "expectWidth",
                    "number",
                    "guard: require the first column to currently have this width",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx rowheights show",
            "show <file> --sheet <sheet> --range <rows>",
            "Show resolved worksheet row heights for a row range.",
            &["sheet", "range"],
            false,
            Some("read-only command; direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "row span such as 2 or 2:5"),
            ],
        ),
        capability_command(
            "ooxml xlsx rowheights set",
            "set <file> --sheet <sheet> --range <rows> --height <height>",
            "Set a uniform worksheet row height for a row range.",
            &["sheet", "range"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "row span such as 2 or 2:5"),
                flag(
                    "--height",
                    "height",
                    "number",
                    "row height in points (0-409)",
                ),
                flag(
                    "--expect-height",
                    "expectHeight",
                    "number",
                    "guard: require the first row to currently have this height",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx rows insert",
            "insert <file> --sheet <sheet> --at <row>",
            "Insert blank worksheet rows before a 1-based row position.",
            &["sheet", "range"],
            false,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--at",
                    "at",
                    "int",
                    "1-based row position for the inserted rows",
                ),
                flag("--count", "count", "int", "number of rows to insert"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx rows delete",
            "delete <file> --sheet <sheet> --row <row>",
            "Delete a band of worksheet rows.",
            &["sheet", "range"],
            false,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--row", "row", "int", "1-based first row to delete"),
                flag("--count", "count", "int", "number of rows to delete"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cols insert",
            "insert <file> --sheet <sheet> --at <column>",
            "Insert blank worksheet columns before a column position.",
            &["sheet", "range"],
            false,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--at",
                    "at",
                    "string",
                    "column position for the inserted columns",
                ),
                flag("--count", "count", "int", "number of columns to insert"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cols delete",
            "delete <file> --sheet <sheet> --col <column>",
            "Delete a band of worksheet columns.",
            &["sheet", "range"],
            false,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--col", "col", "string", "first column to delete"),
                flag("--count", "count", "int", "number of columns to delete"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx charts list",
            "list <file>",
            "List workbook charts, stable selectors, source formulas, anchors, and chart style readback.",
            &["chart"],
            false,
            Some("read-only command; generated show commands can read back individual charts"),
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
        ),
        capability_command(
            "ooxml xlsx charts show",
            "show <file> [--chart <selector>]",
            "Show one workbook chart, including chart type, source formulas, cached previews, anchors, part metadata, and practical style.",
            &["chart"],
            false,
            Some("read-only command; generated by xlsx charts list"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
            ],
        ),
        capability_command(
            "ooxml xlsx charts set-title",
            "set-title <file> --title <text>",
            "Set a worksheet chart title and optional title font fields.",
            &["chart", "style"],
            false,
            Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag("--title", "title", "string", "new chart title text"),
                flag(
                    "--expect-title",
                    "expectTitle",
                    "string",
                    "guard: current title text",
                ),
                flag("--font-family", "fontFamily", "string", "title font family"),
                flag(
                    "--font-size",
                    "fontSize",
                    "float",
                    "title font size in points",
                ),
                flag("--font-color", "fontColor", "string", "title font color"),
                flag("--font-bold", "fontBold", "bool", "title font bold"),
                flag("--font-italic", "fontItalic", "bool", "title font italic"),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx charts set-legend",
            "set-legend <file> --position <position>",
            "Set or remove a worksheet chart legend position and overlay flag.",
            &["chart", "style"],
            false,
            Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag(
                    "--position",
                    "position",
                    "string",
                    "right, left, top, bottom, or none",
                ),
                flag("--overlay", "overlay", "bool", "legend overlays plot area"),
                flag(
                    "--expect-position",
                    "expectPosition",
                    "string",
                    "guard: current legend position",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx charts set-chart-area-fill",
            "set-chart-area-fill <file> --fill-color <#RRGGBB|none>",
            "Set or clear the worksheet chart-area fill.",
            &["chart", "style"],
            false,
            Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            xlsx_chart_fill_flags(),
        ),
        capability_command(
            "ooxml xlsx charts set-plot-area-fill",
            "set-plot-area-fill <file> --fill-color <#RRGGBB|none>",
            "Set or clear the worksheet plot-area fill.",
            &["chart", "style"],
            false,
            Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            xlsx_chart_fill_flags(),
        ),
        capability_command(
            "ooxml xlsx charts set-series-style",
            "set-series-style <file> --series <n>",
            "Set fill, line, and marker style fields on a worksheet chart series.",
            &["chart", "style"],
            false,
            Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag("--series", "series", "int", "1-based series number"),
                flag("--fill-color", "fillColor", "string", "series fill color"),
                flag("--line-color", "lineColor", "string", "series line color"),
                flag(
                    "--line-width-pt",
                    "lineWidthPt",
                    "float",
                    "series line width in points",
                ),
                flag(
                    "--marker-symbol",
                    "markerSymbol",
                    "string",
                    "circle, square, diamond, triangle, or none",
                ),
                flag("--marker-size", "markerSize", "int", "marker size 2..72"),
                flag(
                    "--expect-series-count",
                    "expectSeriesCount",
                    "int",
                    "guard: current series count",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx charts convert-type",
            "convert-type <file> --to <type>",
            "Convert an existing worksheet chart to bar, column, line, area, pie, or scatter while preserving series source references and caches where possible.",
            &["chart"],
            false,
            Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag(
                    "--to",
                    "to",
                    "string",
                    "target type: bar, column, line, area, pie, or scatter",
                ),
                flag(
                    "--expect-type",
                    "expectType",
                    "string",
                    "guard: current chart type",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx charts copy-style",
            "copy-style <file> --from <template.xlsx>",
            "Copy practical chart style fields from a template worksheet chart without copying chart content or source data.",
            &["chart", "style"],
            false,
            Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            vec![
                flag("--sheet", "sheet", "string", "target sheet selector"),
                flag("--chart", "chart", "string", "target chart selector"),
                flag(
                    "--to-chart",
                    "toChart",
                    "string",
                    "target chart selector alias",
                ),
                flag("--from", "from", "string", "template XLSX file"),
                flag(
                    "--from-chart",
                    "fromChart",
                    "string",
                    "template chart selector",
                ),
                flag(
                    "--expect-series-count",
                    "expectSeriesCount",
                    "int",
                    "guard: target series count",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx charts set-axis",
            "set-axis <file> --axis <category|value>",
            "Set practical category/value axis properties such as title, visibility, scale, number format, gridlines, and label/title fonts.",
            &["chart", "style"],
            false,
            Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag("--axis", "axis", "string", "category or value"),
                flag(
                    "--title",
                    "title",
                    "string",
                    "axis title text; empty clears",
                ),
                flag(
                    "--expect-axis-title",
                    "expectAxisTitle",
                    "string",
                    "guard: current axis title",
                ),
                flag("--hidden", "hidden", "bool", "hide or show the axis"),
                flag("--min", "min", "float", "axis scale minimum"),
                flag("--max", "max", "float", "axis scale maximum"),
                flag(
                    "--major-unit",
                    "majorUnit",
                    "float",
                    "value-axis major unit",
                ),
                flag(
                    "--number-format",
                    "numberFormat",
                    "string",
                    "axis number format code",
                ),
                flag(
                    "--major-gridlines",
                    "majorGridlines",
                    "bool",
                    "show major gridlines",
                ),
                flag(
                    "--minor-gridlines",
                    "minorGridlines",
                    "bool",
                    "show minor gridlines",
                ),
                flag(
                    "--tick-label-font-family",
                    "tickLabelFontFamily",
                    "string",
                    "tick label font family",
                ),
                flag(
                    "--tick-label-font-size",
                    "tickLabelFontSize",
                    "float",
                    "tick label font size in points",
                ),
                flag(
                    "--tick-label-font-color",
                    "tickLabelFontColor",
                    "string",
                    "tick label font color",
                ),
                flag(
                    "--tick-label-font-bold",
                    "tickLabelFontBold",
                    "bool",
                    "tick label bold",
                ),
                flag(
                    "--tick-label-font-italic",
                    "tickLabelFontItalic",
                    "bool",
                    "tick label italic",
                ),
                flag(
                    "--title-font-family",
                    "titleFontFamily",
                    "string",
                    "axis title font family",
                ),
                flag(
                    "--title-font-size",
                    "titleFontSize",
                    "float",
                    "axis title font size in points",
                ),
                flag(
                    "--title-font-color",
                    "titleFontColor",
                    "string",
                    "axis title font color",
                ),
                flag(
                    "--title-font-bold",
                    "titleFontBold",
                    "bool",
                    "axis title bold",
                ),
                flag(
                    "--title-font-italic",
                    "titleFontItalic",
                    "bool",
                    "axis title italic",
                ),
                flag(
                    "--expect-axis-count",
                    "expectAxisCount",
                    "int",
                    "guard: chart axis count",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx comments list",
            "list <file> [--sheet <sheet>] [--comment-id <id>]",
            "List worksheet comments, authors, selectors, hashes, and anchored cells.",
            &["comment", "sheet", "cell"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--comment-id",
                    "commentId",
                    "int",
                    "only return the comment with this zero-based id",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx comments add",
            "add <file> --cell <A1> --author <name> [--text <text>]",
            "Add a worksheet cell comment, creating comments and legacy VML drawing parts when needed.",
            &["comment", "sheet", "cell"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--cell", "cell", "string", "target cell such as C3"),
                flag("--author", "author", "string", "comment author"),
                flag("--text", "text", "string", "comment text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "read comment text from file",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx comments update",
            "update <file> (--handle <handle>|--comment-id <id>)",
            "Update a worksheet comment's text and/or author with optional hash guard.",
            &["comment", "sheet", "cell"],
            true,
            None,
            vec![
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet selector used with --comment-id",
                ),
                flag(
                    "--comment-id",
                    "commentId",
                    "int",
                    "zero-based comment id on the selected sheet",
                ),
                flag("--handle", "handle", "string", "published comment handle"),
                flag("--text", "text", "string", "replacement comment text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "read replacement text from file",
                ),
                flag(
                    "--author",
                    "author",
                    "string",
                    "replacement/additional author",
                ),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "guard: expected current comment content hash",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx comments remove",
            "remove <file> (--handle <handle>|--comment-id <id>)",
            "Remove a worksheet comment, cleaning orphaned comments/VML parts when the sheet has no comments left.",
            &["comment", "sheet", "cell"],
            true,
            None,
            vec![
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet selector used with --comment-id",
                ),
                flag(
                    "--comment-id",
                    "commentId",
                    "int",
                    "zero-based comment id on the selected sheet",
                ),
                flag("--handle", "handle", "string", "published comment handle"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "guard: expected current comment content hash",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx data-validations list",
            "list <file> [--sheet <sheet>]",
            "List worksheet data-validation rules and their target ranges.",
            &["data-validation", "range", "sheet"],
            false,
            Some("read-only command; call via direct CLI in the current Rust slice"),
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
        ),
        capability_command(
            "ooxml xlsx data-validations show",
            "show <file> --range <sqref> [--sheet <sheet>]",
            "Show the validation rule that targets a specific worksheet range.",
            &["data-validation", "range", "sheet"],
            false,
            Some("read-only command; call via direct CLI in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "target sqref such as A2:A20"),
            ],
        ),
        capability_command(
            "ooxml xlsx data-validations create",
            "create <file> --range <sqref> --type <type>",
            "Create a worksheet data-validation rule such as a dropdown list or numeric constraint.",
            &["data-validation", "range", "sheet"],
            true,
            None,
            xlsx_data_validation_mutation_flags(false),
        ),
        capability_command(
            "ooxml xlsx data-validations update",
            "update <file> --range <sqref>",
            "Update an existing worksheet data-validation rule with optional type/formula guards.",
            &["data-validation", "range", "sheet"],
            true,
            None,
            xlsx_data_validation_mutation_flags(true),
        ),
        capability_command(
            "ooxml xlsx data-validations delete",
            "delete <file> --range <sqref>",
            "Delete a worksheet data-validation rule by target range with optional type/formula guards.",
            &["data-validation", "range", "sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "target sqref such as A2:A20"),
                flag(
                    "--expect-type",
                    "expectType",
                    "string",
                    "guard: require the current validation type to match",
                ),
                flag(
                    "--expect-formula1",
                    "expectFormula1",
                    "string",
                    "guard: require the current formula1 to match",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx hyperlinks list",
            "list <file> [--sheet <sheet>]",
            "List worksheet hyperlinks with stable cell or range selectors.",
            &["hyperlink", "cell", "range", "sheet"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--include-broken",
                    "includeBroken",
                    "bool",
                    "only return broken external hyperlinks",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx hyperlinks show",
            "show <file> --sheet <sheet> --cell <A1>",
            "Show the hyperlink attached to a worksheet cell or range ref.",
            &["hyperlink", "cell", "range", "sheet"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--cell", "cell", "string", "cell or range ref such as B2"),
            ],
        ),
        capability_command(
            "ooxml xlsx hyperlinks add",
            "add <file> --sheet <sheet> --cell <A1> (--url <url>|--location <ref>)",
            "Add an internal or external worksheet hyperlink.",
            &["hyperlink", "cell", "range", "sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--cell", "cell", "string", "cell or range ref such as B2"),
                flag("--url", "url", "string", "external hyperlink target"),
                flag(
                    "--location",
                    "location",
                    "string",
                    "internal workbook hyperlink target",
                ),
                flag("--display", "display", "string", "optional display text"),
                flag("--tooltip", "tooltip", "string", "optional tooltip text"),
                flag(
                    "--replace",
                    "replace",
                    "bool",
                    "replace an existing hyperlink on the ref",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx hyperlinks update",
            "update <file> --sheet <sheet> --cell <A1>",
            "Update an existing worksheet hyperlink with optional stale-target guards.",
            &["hyperlink", "cell", "range", "sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--cell", "cell", "string", "cell or range ref such as B2"),
                flag("--url", "url", "string", "new external hyperlink target"),
                flag(
                    "--location",
                    "location",
                    "string",
                    "new internal workbook hyperlink target",
                ),
                flag("--display", "display", "string", "replacement display text"),
                flag("--tooltip", "tooltip", "string", "replacement tooltip text"),
                flag(
                    "--expect-url",
                    "expectUrl",
                    "string",
                    "guard: expected current external target",
                ),
                flag(
                    "--expect-location",
                    "expectLocation",
                    "string",
                    "guard: expected current internal target",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx hyperlinks delete",
            "delete <file> --sheet <sheet> --cell <A1>",
            "Delete an existing worksheet hyperlink with optional stale-target guards.",
            &["hyperlink", "cell", "range", "sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--cell", "cell", "string", "cell or range ref such as B2"),
                flag(
                    "--expect-url",
                    "expectUrl",
                    "string",
                    "guard: expected current external target",
                ),
                flag(
                    "--expect-location",
                    "expectLocation",
                    "string",
                    "guard: expected current internal target",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx filters-sorts show",
            "show <file> [--sheet <sheet>] [--table <table>]",
            "Display worksheet or table autoFilter state and worksheet sortState.",
            &["sheet", "range", "table"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--range",
                    "range",
                    "string",
                    "informational range hint; state is read from worksheet/table XML",
                ),
                flag("--table", "table", "string", "table selector"),
            ],
        ),
        capability_command(
            "ooxml xlsx filters-sorts set-autofilter",
            "set-autofilter <file> (--range <A1:D10>|--table <table>)",
            "Add or replace a worksheet or table autoFilter ref.",
            &["sheet", "range", "table"],
            false,
            Some("direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "worksheet autoFilter range"),
                flag("--table", "table", "string", "table selector"),
                flag(
                    "--expect-range",
                    "expectRange",
                    "string",
                    "guard: require the current autoFilter ref to match",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx filters-sorts clear-autofilter",
            "clear-autofilter <file> [--sheet <sheet>] [--table <table>]",
            "Remove a worksheet or table autoFilter.",
            &["sheet", "range", "table"],
            false,
            Some("direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--range",
                    "range",
                    "string",
                    "accepted for CLI compatibility; current state is read from the worksheet/table",
                ),
                flag("--table", "table", "string", "table selector"),
                flag(
                    "--expect-range",
                    "expectRange",
                    "string",
                    "guard: require the current autoFilter ref to match",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx filters-sorts add-column-filter",
            "add-column-filter <file> --column <colId> (--values <a,b>|--custom-op <op>)",
            "Add values and/or custom criteria to one worksheet autoFilter column.",
            &["sheet", "range"],
            false,
            Some("direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--column",
                    "column",
                    "number",
                    "0-based column offset within the autoFilter ref",
                ),
                flag(
                    "--values",
                    "values",
                    "string",
                    "comma-separated filter values",
                ),
                flag(
                    "--custom-op",
                    "customOp",
                    "string",
                    "custom operator: equal|notEqual|lessThan|lessThanOrEqual|greaterThan|greaterThanOrEqual|between|notBetween",
                ),
                flag(
                    "--custom-val1",
                    "customVal1",
                    "string",
                    "first custom criterion value",
                ),
                flag(
                    "--custom-val2",
                    "customVal2",
                    "string",
                    "second custom criterion value for between/notBetween",
                ),
                flag(
                    "--expect-filter",
                    "expectFilter",
                    "string",
                    "guard: require current column filter summary to match",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx filters-sorts clear-column-filter",
            "clear-column-filter <file> --column <colId>",
            "Remove one worksheet autoFilter column criterion.",
            &["sheet", "range"],
            false,
            Some("direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--column",
                    "column",
                    "int",
                    "0-based column offset within the autoFilter ref",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx filters-sorts set-sort",
            "set-sort <file> --ref <A1:D10> --column <A>",
            "Add or replace one worksheet sortState condition.",
            &["sheet", "range"],
            false,
            Some("direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--ref", "ref", "string", "sortState range such as A1:D10"),
                flag("--column", "column", "string", "column letter to sort by"),
                flag("--descending", "descending", "bool", "sort descending"),
                flag(
                    "--expect-sort",
                    "expectSort",
                    "string",
                    "guard: require current sortState ref to match",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx filters-sorts clear-sort",
            "clear-sort <file> [--sheet <sheet>]",
            "Remove the worksheet sortState.",
            &["sheet", "range"],
            false,
            Some("direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx names list",
            "list <file> [--scope-sheet <sheet>]",
            "List workbook and sheet-local defined names with selectors.",
            &["name", "sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag(
                "--scope-sheet",
                "scopeSheet",
                "string",
                "only list sheet-local names for this sheet selector",
            )],
        ),
        capability_command(
            "ooxml xlsx names show",
            "show <file> --name <selector> [--scope-sheet <sheet>]",
            "Show one workbook defined name by name, selector, or handle.",
            &["name", "sheet", "range"],
            false,
            Some("read-only command; generated by xlsx names list"),
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name, selector, or workbook-scoped handle",
                ),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx names add",
            "add <file> --name <name> (--ref <ref>|--sheet <sheet> --range <range>)",
            "Add a workbook or sheet-local defined name.",
            &["name", "sheet", "range"],
            true,
            None,
            vec![
                flag("--name", "name", "string", "defined name to add"),
                flag(
                    "--ref",
                    "ref",
                    "string",
                    "exact defined-name ref/formula text",
                ),
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet selector used with --range",
                ),
                flag("--range", "range", "string", "A1 range used with --sheet"),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "create a sheet-local name scoped to this sheet selector",
                ),
                flag("--hidden", "hidden", "bool", "mark the defined name hidden"),
                flag(
                    "--comment",
                    "comment",
                    "string",
                    "optional defined-name comment",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx names update",
            "update <file> --name <selector> (--ref <ref>|--sheet <sheet> --range <range>)",
            "Update a workbook defined name reference.",
            &["name", "sheet", "range"],
            true,
            None,
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name or published selector",
                ),
                flag(
                    "--ref",
                    "ref",
                    "string",
                    "exact replacement ref/formula text",
                ),
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet selector used with --range",
                ),
                flag(
                    "--range",
                    "range",
                    "string",
                    "replacement A1 range used with --sheet",
                ),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
                flag(
                    "--expect-ref",
                    "expectRef",
                    "string",
                    "guard: expected current ref/formula text",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx names rename",
            "rename <file> --name <selector> --new-name <name>",
            "Rename a workbook defined name while preserving its ref and scope.",
            &["name", "sheet", "range"],
            true,
            None,
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name or published selector",
                ),
                flag("--new-name", "newName", "string", "new defined name"),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
                flag(
                    "--expect-ref",
                    "expectRef",
                    "string",
                    "guard: expected current ref/formula text",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx names delete",
            "delete <file> --name <selector>",
            "Delete a workbook defined name.",
            &["name", "sheet", "range"],
            true,
            None,
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name or published selector",
                ),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
                flag(
                    "--expect-ref",
                    "expectRef",
                    "string",
                    "guard: expected current ref/formula text",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
    ];
    commands.extend(tables::commands());
    commands.extend(vec![
        capability_command(
            "ooxml xlsx pivots list",
            "list <file>",
            "List workbook PivotTables, cache sources, selectors, and generated readback commands.",
            &["pivot", "sheet", "range", "table"],
            false,
            Some("read-only command; call via inspect/list in direct CLI"),
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
        ),
        capability_command(
            "ooxml xlsx pivots show",
            "show <file>",
            "Show one PivotTable with cache fields, source range, axis fields, and selectors.",
            &["pivot", "sheet", "range", "table"],
            false,
            Some("read-only command; call via inspect/list in direct CLI"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--pivot",
                    "pivot",
                    "string",
                    "pivot selector from pivots list",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx pivots create",
            "create <file>",
            "Author a new PivotTable from a source table or worksheet range.",
            &["pivot", "sheet", "range", "table"],
            false,
            Some("direct CLI mutation; serve/MCP operation dispatch is not wired for this command"),
            vec![
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "source sheet selector for --range or table disambiguation",
                ),
                flag(
                    "--range",
                    "range",
                    "string",
                    "source A1 range with a header row",
                ),
                flag("--table", "table", "string", "source table selector"),
                flag(
                    "--target-sheet",
                    "targetSheet",
                    "string",
                    "sheet to place the pivot on; defaults to the source sheet",
                ),
                flag(
                    "--anchor",
                    "anchor",
                    "string",
                    "top-left pivot anchor cell; defaults right of the source range",
                ),
                flag("--name", "name", "string", "pivot table name"),
                flag(
                    "--rows",
                    "rows",
                    "string",
                    "comma-separated row field names",
                ),
                flag(
                    "--cols",
                    "cols",
                    "string",
                    "comma-separated column field names",
                ),
                flag(
                    "--filters",
                    "filters",
                    "string",
                    "comma-separated filter/page field names",
                ),
                flag(
                    "--values",
                    "values",
                    "string",
                    "comma-separated value field specs such as Amount or Amount:sum",
                ),
                flag(
                    "--expect-source-range",
                    "expectSourceRange",
                    "string",
                    "guard: require the resolved source range to match",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum source cells to read",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
    ]);
    commands.extend(vec![
        capability_command(
            "ooxml xlsx workbook metadata inspect",
            "inspect <file>",
            "Inspect workbook core/app properties and calc settings.",
            &["package"],
            false,
            Some("it does not accept the mutation output flags injected by the op engine"),
            vec![],
        ),
        capability_command(
            "ooxml xlsx workbook metadata update",
            "update <file>",
            "Update workbook metadata fields and calc settings.",
            &["package"],
            true,
            None,
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--calc-mode",
                    "calcMode",
                    "string",
                    "set workbook calcMode (auto|manual|autoNoTable)",
                ),
                flag(
                    "--category",
                    "category",
                    "string",
                    "set core property category",
                ),
                flag("--company", "company", "string", "set app property Company"),
                flag(
                    "--creator",
                    "creator",
                    "string",
                    "set core property dc:creator",
                ),
                flag(
                    "--description",
                    "description",
                    "string",
                    "set core property dc:description",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--expect-category",
                    "expectCategory",
                    "string",
                    "guard: require current category to equal this value",
                ),
                flag(
                    "--expect-company",
                    "expectCompany",
                    "string",
                    "guard: require current company to equal this value",
                ),
                flag(
                    "--expect-creator",
                    "expectCreator",
                    "string",
                    "guard: require current creator to equal this value",
                ),
                flag(
                    "--expect-description",
                    "expectDescription",
                    "string",
                    "guard: require current description to equal this value",
                ),
                flag(
                    "--expect-keywords",
                    "expectKeywords",
                    "string",
                    "guard: require current keywords to equal this value",
                ),
                flag(
                    "--expect-last-modified-by",
                    "expectLastModifiedBy",
                    "string",
                    "guard: require current lastModifiedBy to equal this value",
                ),
                flag(
                    "--expect-manager",
                    "expectManager",
                    "string",
                    "guard: require current manager to equal this value",
                ),
                flag(
                    "--expect-subject",
                    "expectSubject",
                    "string",
                    "guard: require current subject to equal this value",
                ),
                flag(
                    "--expect-title",
                    "expectTitle",
                    "string",
                    "guard: require current title to equal this value",
                ),
                flag(
                    "--full-calc-on-load",
                    "fullCalcOnLoad",
                    "bool",
                    "set fullCalcOnLoad and forceFullCalc so Excel recalculates on open",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag(
                    "--keywords",
                    "keywords",
                    "string",
                    "set core property keywords",
                ),
                flag(
                    "--last-modified-by",
                    "lastModifiedBy",
                    "string",
                    "set core property lastModifiedBy",
                ),
                flag("--manager", "manager", "string", "set app property Manager"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--subject",
                    "subject",
                    "string",
                    "set core property dc:subject",
                ),
                flag("--title", "title", "string", "set core property dc:title"),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges export",
            "export <file>",
            "Export decoded worksheet cells from a range.",
            &["sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag(
                    "--include-types",
                    "includeTypes",
                    "bool",
                    "include cell types",
                ),
                flag(
                    "--include-formulas",
                    "includeFormulas",
                    "bool",
                    "include formulas",
                ),
                flag(
                    "--include-formats",
                    "includeFormats",
                    "bool",
                    "include style and number-format matrices",
                ),
                flag(
                    "--data-out",
                    "dataOut",
                    "string",
                    "write JSON matrix data to this file",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to export",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges set",
            "set <file>",
            "Set a worksheet range from a rectangular JSON, CSV, or TSV matrix.",
            &["sheet", "range", "cell"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--anchor", "anchor", "string", "top-left A1 cell"),
                flag("--values", "values", "string", "inline matrix data"),
                flag(
                    "--values-file",
                    "valuesFile",
                    "string",
                    "path to matrix data, or - for stdin",
                ),
                flag(
                    "--data-format",
                    "dataFormat",
                    "string",
                    "matrix data format: json, csv, or tsv",
                ),
                flag(
                    "--null-policy",
                    "nullPolicy",
                    "string",
                    "null handling: skip, clear, or empty-string",
                ),
                flag(
                    "--ragged",
                    "ragged",
                    "string",
                    "ragged handling: reject or fill-empty",
                ),
                flag("--max-cells", "maxCells", "number", "maximum cells to set"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--overwrite-formulas",
                    "overwriteFormulas",
                    "bool",
                    "allow replacing existing formula cells",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges set-format",
            "set-format <file>",
            "Apply a practical number format to a worksheet range.",
            &["sheet", "range", "style"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag(
                    "--preset",
                    "preset",
                    "string",
                    "format preset: integer, number, currency, percent, date, datetime, text, or general",
                ),
                flag(
                    "--format-code",
                    "formatCode",
                    "string",
                    "custom SpreadsheetML number format code",
                ),
                flag(
                    "--decimals",
                    "decimals",
                    "number",
                    "decimal places for number, currency, and percent presets",
                ),
                flag(
                    "--currency-symbol",
                    "currencySymbol",
                    "string",
                    "currency literal for the currency preset",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to format",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges set-style",
            "set-style <file>",
            "Apply font, fill, border, and alignment styling to a worksheet range.",
            &["sheet", "range", "style"],
            false,
            Some("direct CLI mutation; serve/MCP operation dispatch is not wired for this command"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--font-name", "fontName", "string", "font family name"),
                flag("--font-size", "fontSize", "number", "font size in points"),
                flag("--font-bold", "fontBold", "bool", "toggle bold text"),
                flag("--font-italic", "fontItalic", "bool", "toggle italic text"),
                flag(
                    "--font-underline",
                    "fontUnderline",
                    "bool",
                    "toggle underline text",
                ),
                flag("--font-color", "fontColor", "string", "font color as hex RGB"),
                flag("--fill-color", "fillColor", "string", "cell fill color as hex RGB"),
                flag("--border-style", "borderStyle", "string", "border line style"),
                flag("--border-color", "borderColor", "string", "border color as hex RGB"),
                flag("--border-top", "borderTop", "bool", "apply top border"),
                flag("--border-bottom", "borderBottom", "bool", "apply bottom border"),
                flag("--border-left", "borderLeft", "bool", "apply left border"),
                flag("--border-right", "borderRight", "bool", "apply right border"),
                flag(
                    "--alignment-horizontal",
                    "alignmentHorizontal",
                    "string",
                    "horizontal alignment",
                ),
                flag(
                    "--alignment-vertical",
                    "alignmentVertical",
                    "string",
                    "vertical alignment",
                ),
                flag(
                    "--alignment-wrap-text",
                    "alignmentWrapText",
                    "bool",
                    "toggle text wrapping",
                ),
                flag("--max-cells", "maxCells", "number", "maximum cells to style"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cells extract",
            "extract <file>",
            "Extract decoded worksheet cells with stable cell selectors.",
            &["sheet", "range", "cell"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--max-rows", "maxRows", "number", "maximum rows to emit"),
                flag("--max-cells", "maxCells", "number", "maximum cells to emit"),
                flag(
                    "--include-empty",
                    "includeEmpty",
                    "bool",
                    "include empty cells inside output bounds",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cells set",
            "set <file>",
            "Set a worksheet cell value.",
            &["sheet", "cell"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path"),
                flag("--cell", "cell", "string", "A1 cell reference"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag("--formula", "formula", "string", "cell formula"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag(
                    "--out",
                    "out",
                    "string",
                    "output file path for direct CLI use",
                ),
                flag("--ref", "ref", "string", "A1 cell reference alias"),
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--type", "type", "string", "value type"),
                flag("--value", "value", "string", "cell value"),
            ],
        ),
        capability_command(
            "ooxml xlsx cells clear",
            "clear <file>",
            "Clear values and formulas from a worksheet cell or range.",
            &["sheet", "range", "cell"],
            false,
            Some("direct CLI mutation; serve/MCP operation dispatch is not wired for this command"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--ref", "ref", "string", "A1 cell reference"),
                flag(
                    "--readback-max-cells",
                    "readbackMaxCells",
                    "number",
                    "maximum cells in emitted destination readback",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cells set-batch",
            "set-batch <file>",
            "Set multiple worksheet cells from inline JSON or a JSON file.",
            &["sheet", "range", "cell"],
            false,
            Some("direct CLI mutation; serve/MCP operation dispatch is not wired for this command"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--cells", "cells", "string", "inline JSON cell assignments"),
                flag(
                    "--cells-file",
                    "cellsFile",
                    "string",
                    "path to JSON cell assignments, or - for stdin",
                ),
                flag("--details", "details", "bool", "emit per-cell mutation details"),
                flag(
                    "--readback-max-cells",
                    "readbackMaxCells",
                    "number",
                    "maximum cells in emitted destination readback",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx freeze show",
            "show <file>",
            "Display current worksheet freeze panes state.",
            &["sheet"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
        ),
        capability_command(
            "ooxml xlsx freeze set",
            "set <file>",
            "Set frozen rows and/or columns on a worksheet.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--rows", "rows", "number", "number of top rows to freeze"),
                flag(
                    "--cols",
                    "cols",
                    "number",
                    "number of left columns to freeze",
                ),
                flag(
                    "--expect-state",
                    "expectState",
                    "string",
                    "guard: require current state to be none or frozen",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx freeze clear",
            "clear <file>",
            "Remove frozen panes from a worksheet.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--expect-state",
                    "expectState",
                    "string",
                    "guard: require current state to be none or frozen",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
    ]);
    commands
}

fn xlsx_chart_fill_flags() -> Vec<Value> {
    vec![
        flag("--sheet", "sheet", "string", "sheet selector"),
        flag("--chart", "chart", "string", "chart selector"),
        flag(
            "--fill-color",
            "fillColor",
            "string",
            "fill color as #RRGGBB, or none",
        ),
        flag(
            "--expect-fill",
            "expectFill",
            "string",
            "guard: current fill color, scheme:<name>, or none",
        ),
        flag("--out", "out", "string", "write edited workbook"),
        flag(
            "--in-place",
            "inPlace",
            "bool",
            "edit the workbook in place",
        ),
        flag("--backup", "backup", "string", "backup path for --in-place"),
        flag("--dry-run", "dryRun", "bool", "validate without writing"),
        flag(
            "--no-validate",
            "noValidate",
            "bool",
            "skip strict validation",
        ),
    ]
}

fn xlsx_data_validation_mutation_flags(include_guards: bool) -> Vec<Value> {
    let mut flags = vec![
        flag("--sheet", "sheet", "string", "sheet selector"),
        flag(
            "--range",
            "range",
            "string",
            "target sqref; space-separated ranges are accepted",
        ),
        flag(
            "--type",
            "type",
            "string",
            "validation type: list, whole, decimal, date, time, textLength, or custom",
        ),
        flag(
            "--list-values",
            "listValues",
            "string",
            "comma-separated inline values for list validations",
        ),
        flag(
            "--list-range",
            "listRange",
            "string",
            "worksheet range source for list validations",
        ),
        flag(
            "--operator",
            "operator",
            "string",
            "operator such as between, equal, greaterThan, or lessThanOrEqual",
        ),
        flag("--formula1", "formula1", "string", "first formula or bound"),
        flag(
            "--formula2",
            "formula2",
            "string",
            "second formula or bound for between/notBetween",
        ),
        flag("--allow-blank", "allowBlank", "bool", "allow blank cells"),
        flag(
            "--show-input-message",
            "showInputMessage",
            "bool",
            "show the input prompt",
        ),
        flag(
            "--input-title",
            "inputTitle",
            "string",
            "input prompt title",
        ),
        flag(
            "--input-message",
            "inputMessage",
            "string",
            "input prompt message",
        ),
        flag(
            "--show-error-message",
            "showErrorMessage",
            "bool",
            "show the error alert",
        ),
        flag("--error-title", "errorTitle", "string", "error alert title"),
        flag(
            "--error-message",
            "errorMessage",
            "string",
            "error alert message",
        ),
        flag(
            "--error-style",
            "errorStyle",
            "string",
            "error alert style: stop, warning, or information",
        ),
    ];
    if include_guards {
        flags.push(flag(
            "--expect-type",
            "expectType",
            "string",
            "guard: require the current validation type to match",
        ));
        flags.push(flag(
            "--expect-formula1",
            "expectFormula1",
            "string",
            "guard: require the current formula1 to match",
        ));
    }
    flags.extend([
        flag("--out", "out", "string", "write edited workbook"),
        flag(
            "--in-place",
            "inPlace",
            "bool",
            "edit the workbook in place",
        ),
        flag(
            "--backup",
            "backup",
            "string",
            "backup file path for --in-place",
        ),
        flag("--dry-run", "dryRun", "bool", "validate without writing"),
        flag(
            "--no-validate",
            "noValidate",
            "bool",
            "skip post-write validation",
        ),
    ]);
    flags
}
