use serde_json::{Value, json};
use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;
use std::process::{Command, Output};

const CSV: &str = "Region,Revenue\nNorth,150\nSouth,175\nWest,210\n";
const MARKDOWN: &str = "# Next quarter\n\n- Expand the pilot\n- Review revenue monthly\n";

struct Simulation {
    root: PathBuf,
    capabilities: Value,
    discovered: BTreeSet<String>,
    tutorial: String,
}

impl Drop for Simulation {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.root);
    }
}

impl Simulation {
    fn new() -> Self {
        let root = std::env::temp_dir().join(format!(
            "ooxml-agent-edits-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        fs::create_dir(&root).unwrap();
        let mut simulation = Self {
            root,
            capabilities: Value::Null,
            discovered: BTreeSet::new(),
            tutorial: String::from(
                "# Agent quickstart: edit existing Office files\n\n\
                 Generated by `tests/agent_edit_simulation.rs` from commands it executes. \
                 The drift test checks this entire document after verifying saved results.\n\n\
                 Start with [README](../README.md), the [OOXML skill](../skills/ooxml/SKILL.md), \
                 live help, and capabilities. Selectors below come from readback. \
                 Replace the example filenames and selectors with your own.\n\n\
                 These examples work in a directory containing copies of the repository fixtures: \
                 `testdata/pptx/chart-simple/presentation.pptx` as `deck.pptx`, \
                 `testdata/docx/scaffold-styles/dangling-style.docx` as `report.docx`, and \
                 `testdata/xlsx/chart-workbook/workbook.xlsx` as `workbook.xlsx`. \
                 All edits publish to new files; the tests verify that inputs remain byte-identical.\n\n\
                 ## Discover the available commands\n\n",
            ),
        };
        let readme = include_str!("../README.md");
        let skill = include_str!("../skills/ooxml/SKILL.md");
        for surface in [readme, skill] {
            assert!(surface.contains("capabilities"));
            assert!(surface.contains("--json"));
        }
        assert!(readme.contains("docs/agent-quickstart.md"));
        let help = simulation.execute(&["--help"], 0);
        assert!(
            String::from_utf8(help.stdout)
                .unwrap()
                .contains("capabilities")
        );
        simulation.capabilities = simulation.json(&["--json", "capabilities"], 0);
        simulation
    }

    fn execute(&mut self, args: &[&str], status: i32) -> Output {
        let output = Command::new(env!("CARGO_BIN_EXE_ooxml"))
            .args(args)
            .current_dir(&self.root)
            .output()
            .unwrap();
        assert_eq!(
            output.status.code(),
            Some(status),
            "first attempt {args:?}\nstdout: {}\nstderr: {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        if status != 1 {
            assert!(output.stderr.is_empty(), "{args:?}: {:?}", output.stderr);
        }
        let command = args
            .iter()
            .map(|arg| {
                if arg
                    .chars()
                    .all(|c| c.is_ascii_alphanumeric() || "-._:/".contains(c))
                {
                    (*arg).to_owned()
                } else {
                    // Single-quoted arguments work in both Bash and PowerShell.
                    assert!(!arg.contains('\''));
                    format!("'{arg}'")
                }
            })
            .collect::<Vec<_>>()
            .join(" ");
        self.tutorial
            .push_str(&format!("```sh\nooxml {command}\n```\n\n"));
        output
    }

    fn json(&mut self, args: &[&str], status: i32) -> Value {
        let output = self.execute(args, status);
        serde_json::from_slice(&output.stdout).unwrap()
    }

    fn discover(&mut self, path: &[&str], flags: &[&str]) {
        let name = format!("ooxml {}", path.join(" "));
        let leaf = self.capabilities["commands"]
            .as_array()
            .unwrap()
            .iter()
            .find(|command| command["path"] == name)
            .unwrap_or_else(|| panic!("public capabilities omit {name}"));
        for flag in flags {
            assert!(
                leaf["localFlags"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .any(|f| f["name"] == *flag),
                "{name} hides {flag}"
            );
        }
        if self.discovered.insert(name) {
            let mut args = path.to_vec();
            args.push("--help");
            let output = self.execute(&args, 0);
            let help = String::from_utf8(output.stdout).unwrap();
            for flag in flags {
                assert!(help.contains(flag));
            }
        }
    }

    fn section(&mut self, title: &str, description: &str) {
        self.tutorial
            .push_str(&format!("## {title}\n\n{description}\n\n"));
    }

    fn copy(&self, source: &str, destination: &str) -> Vec<u8> {
        let bytes = fs::read(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(source)).unwrap();
        fs::write(self.root.join(destination), &bytes).unwrap();
        bytes
    }
}

#[test]
fn public_discovery_edits_existing_files_and_generates_quickstart_without_drift() {
    let mut sim = Simulation::new();
    let originals = [
        (
            "deck.pptx",
            sim.copy("testdata/pptx/chart-simple/presentation.pptx", "deck.pptx"),
        ),
        (
            "report.docx",
            sim.copy(
                "testdata/docx/scaffold-styles/dangling-style.docx",
                "report.docx",
            ),
        ),
        (
            "workbook.xlsx",
            sim.copy(
                "testdata/xlsx/chart-workbook/workbook.xlsx",
                "workbook.xlsx",
            ),
        ),
    ];
    fs::write(sim.root.join("numbers.csv"), CSV).unwrap();
    fs::write(sim.root.join("snippet.md"), MARKDOWN).unwrap();

    sim.section("Update an existing deck from CSV", &format!(
        "Read `numbers.csv`:\n\n```csv\n{CSV}```\n\n\
         The chart command accepts comma-separated values or JSON arrays, rather than a CSV filename. \
         Parse the CSV header and rows first; the arguments below are generated from these rows. \
         Use a CSV reader for quoted fields in your own data. Read the chart selector and current point count before editing."));
    sim.discover(&["pptx", "charts", "list"], &[]);
    let charts = sim.json(&["--json", "pptx", "charts", "list", "deck.pptx"], 0);
    let chart = charts["charts"][0]["primarySelector"].as_str().unwrap();
    let untouched_chart = charts["charts"][1]["series"].clone();
    let csv = fs::read_to_string(sim.root.join("numbers.csv")).unwrap();
    assert_eq!(csv.lines().next(), Some("Region,Revenue"));
    let rows = csv
        .lines()
        .skip(1)
        .map(|row| row.split_once(',').unwrap())
        .collect::<Vec<_>>();
    let categories =
        serde_json::to_string(&rows.iter().map(|(label, _)| *label).collect::<Vec<_>>()).unwrap();
    let values =
        serde_json::to_string(&rows.iter().map(|(_, value)| *value).collect::<Vec<_>>()).unwrap();
    let points = charts["charts"][0]["series"][0]["values"]["pointCount"]
        .as_u64()
        .unwrap()
        .to_string();
    sim.discover(
        &["pptx", "charts", "update-data"],
        &[
            "--chart",
            "--series",
            "--values-json",
            "--categories-json",
            "--expect-point-count",
            "--out",
        ],
    );
    sim.json(
        &[
            "--json",
            "pptx",
            "charts",
            "update-data",
            "deck.pptx",
            "--chart",
            chart,
            "--series",
            "1",
            "--values-json",
            &values,
            "--categories-json",
            &categories,
            "--expect-point-count",
            &points,
            "--out",
            "numbers-updated.pptx",
        ],
        0,
    );
    let updated = sim.json(
        &["--json", "pptx", "charts", "list", "numbers-updated.pptx"],
        0,
    );
    assert_eq!(
        updated["charts"][0]["series"][0]["values"]["cachePreview"],
        json!(["150", "175", "210"])
    );
    assert_eq!(
        updated["charts"][0]["series"][0]["categories"]["cachePreview"],
        json!(["North", "South", "West"])
    );
    assert_eq!(updated["charts"][1]["series"], untouched_chart);
    // Prove both the visible cache and the underlying embedded worksheet changed.
    let archive = fs::File::open(sim.root.join("numbers-updated.pptx")).unwrap();
    let mut zip = zip::ZipArchive::new(archive).unwrap();
    let part = updated["charts"][0]["embeddedWorkbookPartUri"]
        .as_str()
        .unwrap()
        .trim_start_matches('/');
    let mut embedded = zip.by_name(part).unwrap();
    let mut output = fs::File::create(sim.root.join("chart-data.xlsx")).unwrap();
    std::io::copy(&mut embedded, &mut output).unwrap();
    drop(output);
    sim.tutorial.push_str("Saved chart readback contains values `150, 175, 210` and categories `North, South, West`; the second chart is unchanged. The test also extracts the embedded workbook and verifies the matching cells.\n\n");
    // Internal proof uses the public readback command but is not a user editing step.
    let proof = Command::new(env!("CARGO_BIN_EXE_ooxml"))
        .args([
            "--json",
            "xlsx",
            "ranges",
            "export",
            "chart-data.xlsx",
            "--sheet",
            "Sheet1",
            "--range",
            "A2:B4",
        ])
        .current_dir(&sim.root)
        .output()
        .unwrap();
    assert!(
        proof.status.success(),
        "{}",
        String::from_utf8_lossy(&proof.stdout)
    );
    let proof: Value = serde_json::from_slice(&proof.stdout).unwrap();
    assert_eq!(
        proof["values"],
        json!([["North", 150], ["South", 175], ["West", 210]])
    );

    sim.section("Append a slide from a Markdown snippet", &format!(
        "Write `snippet.md`:\n\n```markdown\n{MARKDOWN}```\n\n\
         Build the snippet as a one-slide presentation, then import that slide into the existing deck. \
         Use explicit import policies when the source has a different layout or theme. With no insertion flag, `import-slide` appends. Inspect the slide count before and after."));
    sim.discover(&["pptx", "slides", "list"], &[]);
    let before = sim.json(
        &["--json", "pptx", "slides", "list", "numbers-updated.pptx"],
        0,
    );
    sim.discover(&["pptx", "build"], &["--from-markdown", "--out"]);
    sim.json(
        &[
            "--json",
            "pptx",
            "build",
            "--from-markdown",
            "snippet.md",
            "--out",
            "snippet.pptx",
        ],
        0,
    );
    sim.discover(
        &["pptx", "slides", "import-slide"],
        &[
            "--source",
            "--slide",
            "--layout-policy",
            "--theme-policy",
            "--out",
        ],
    );
    sim.tutorial.push_str("The original first guess below exits `1` for these fixtures because their layouts differ. It publishes no output. This expected refusal is retained as a diagnostic regression for `ooxml-fqo`:\n\n");
    let refused = sim.execute(
        &[
            "--json",
            "pptx",
            "slides",
            "import-slide",
            "numbers-updated.pptx",
            "--source",
            "snippet.pptx",
            "--slide",
            "1",
            "--out",
            "expanded.pptx",
        ],
        1,
    );
    let error: Value = serde_json::from_slice(&refused.stderr).unwrap();
    let message = error["error"]["message"].as_str().unwrap();
    assert!(message.contains("--layout-policy import"), "{message}");
    assert!(message.contains("--theme-policy import"), "{message}");
    assert!(!sim.root.join("expanded.pptx").exists());
    sim.tutorial.push_str(
        "Recover using the explicit policies documented by help and the refusal message:\n\n",
    );
    sim.json(
        &[
            "--json",
            "pptx",
            "slides",
            "import-slide",
            "numbers-updated.pptx",
            "--layout-policy",
            "import",
            "--theme-policy",
            "import",
            "--source",
            "snippet.pptx",
            "--slide",
            "1",
            "--out",
            "expanded.pptx",
        ],
        0,
    );
    let after = sim.json(&["--json", "pptx", "slides", "list", "expanded.pptx"], 0);
    let count = after["slides"].as_array().unwrap().len();
    assert_eq!(count, before["slides"].as_array().unwrap().len() + 1);
    sim.discover(&["pptx", "slides", "show"], &["--slide", "--include-text"]);
    let slide = sim.json(
        &[
            "--json",
            "pptx",
            "slides",
            "show",
            "expanded.pptx",
            "--slide",
            &count.to_string(),
            "--include-text",
        ],
        0,
    );
    for text in ["Next quarter", "Expand the pilot", "Review revenue monthly"] {
        assert!(slide.to_string().contains(text), "missing {text}: {slide}");
    }
    let preserved = sim.json(&["--json", "pptx", "charts", "list", "expanded.pptx"], 0);
    assert_eq!(
        preserved["charts"].as_array().unwrap().len(),
        updated["charts"].as_array().unwrap().len()
    );
    for (saved, original) in preserved["charts"]
        .as_array()
        .unwrap()
        .iter()
        .zip(updated["charts"].as_array().unwrap())
    {
        for key in ["series", "title", "types", "slide", "shapeId"] {
            assert_eq!(saved[key], original[key], "existing chart {key} changed");
        }
    }
    sim.tutorial.push_str("Saved readback shows three slides, the snippet title and both bullets on the final slide, and unchanged chart data on the existing slides.\n\n");

    sim.section("Fix dangling document styles", "Inspect the report, then use the one-call remediation loop. The seeded report exits `5` because it references an undefined style; that exit is expected for the initial check. Inspect the returned findings before choosing a fix.");
    sim.discover(&["check"], &["--fix", "--out", "--openxml-sdk"]);
    let before = sim.json(
        &["--json", "check", "report.docx", "--openxml-sdk", "skip"],
        5,
    );
    assert!(
        before["findings"]
            .as_array()
            .unwrap()
            .iter()
            .any(|finding| finding["code"] == "DOCX_DANGLING_STYLE")
    );
    let fixed = sim.json(
        &[
            "--json",
            "check",
            "report.docx",
            "--fix",
            "--out",
            "repaired.docx",
            "--openxml-sdk",
            "skip",
        ],
        0,
    );
    assert_eq!(fixed["committed"], true);
    assert_eq!(fixed["validated"], true);
    let after = sim.json(
        &["--json", "check", "repaired.docx", "--openxml-sdk", "skip"],
        0,
    );
    assert_eq!(after["summary"]["total"], 0);
    sim.tutorial.push_str("The saved document passes check with zero findings. The original report stays unchanged. `--openxml-sdk skip` keeps this editing loop independent of optional local tools; run schema proof separately when available.\n\n");

    sim.section("Add a chart to an existing workbook", "Use `charts create` to add a chart. Read the sheet and source range first, then confirm the new chart and unchanged worksheet values.");
    sim.discover(&["xlsx", "sheets", "list"], &[]);
    let sheets = sim.json(&["--json", "xlsx", "sheets", "list", "workbook.xlsx"], 0);
    let sheet = sheets["sheets"][0]["name"].as_str().unwrap();
    sim.discover(
        &["xlsx", "ranges", "export"],
        &["--sheet", "--range", "--include-types"],
    );
    let source = sim.json(
        &[
            "--json",
            "xlsx",
            "ranges",
            "export",
            "workbook.xlsx",
            "--sheet",
            sheet,
            "--range",
            "A1:B4",
            "--include-types",
        ],
        0,
    );
    sim.discover(&["xlsx", "charts", "list"], &[]);
    let charts = sim.json(&["--json", "xlsx", "charts", "list", "workbook.xlsx"], 0);
    sim.discover(
        &["xlsx", "charts", "create"],
        &[
            "--type", "--sheet", "--range", "--title", "--anchor", "--out",
        ],
    );
    sim.json(
        &[
            "--json",
            "xlsx",
            "charts",
            "create",
            "workbook.xlsx",
            "--sheet",
            sheet,
            "--type",
            "line",
            "--range",
            "A1:B4",
            "--title",
            "Revenue trend",
            "--anchor",
            "L2",
            "--out",
            "charted.xlsx",
        ],
        0,
    );
    let after = sim.json(&["--json", "xlsx", "charts", "list", "charted.xlsx"], 0);
    assert_eq!(
        after["charts"].as_array().unwrap().len(),
        charts["charts"].as_array().unwrap().len() + 1
    );
    let chart = after["charts"]
        .as_array()
        .unwrap()
        .iter()
        .find(|chart| chart["title"] == "Revenue trend")
        .unwrap();
    assert_eq!(chart["types"], json!(["lineChart"]));
    assert_eq!(
        chart["series"][0]["values"]["cachePreview"],
        json!(["100", "120", "90"])
    );
    let saved = sim.json(
        &[
            "--json",
            "xlsx",
            "ranges",
            "export",
            "charted.xlsx",
            "--sheet",
            sheet,
            "--range",
            "A1:B4",
            "--include-types",
        ],
        0,
    );
    assert_eq!(saved["values"], source["values"]);
    assert_eq!(saved["types"], source["types"]);
    sim.tutorial.push_str("Saved readback shows two charts, including the new line chart with values `100, 120, 90`. The worksheet values and cell types are unchanged.\n\n");

    sim.section("Validate the saved packages", "Strict validation is a separate check of each saved artifact. It does not establish desktop Office compatibility.");
    sim.discover(&["validate"], &[]);
    for path in [
        "numbers-updated.pptx",
        "snippet.pptx",
        "expanded.pptx",
        "repaired.docx",
        "charted.xlsx",
    ] {
        sim.json(&["--json", "validate", "--strict", path], 0);
        schema_proof(&sim.root.join(path));
    }
    for (path, bytes) in originals {
        assert_eq!(
            fs::read(sim.root.join(path)).unwrap(),
            bytes,
            "original {path} changed"
        );
    }
    sim.section("First-guess failures recorded during discovery", "The initial guess `ooxml xlsx charts add --help` exited `2`; `ooxml xlsx charts --help` revealed `create`. This teaching gap is tracked as `ooxml-x6c` and addressed by this generated recipe.\n\nThe guess `ooxml --json xlsx range get workbook.xlsx --sheet Sheet1 --range A1:B5` also exited `2`. Its suggested `ranges set` command is a mutation, so it was not executed. README and range help identify `ranges export` as the read operation used above. Intent-aware typo correction is tracked separately as `ooxml-wrv`.\n\nThe first snippet build using `--from-markdown snippet.md` exposed `ooxml-try`: a bare relative filename failed directory resolution. The builder fix is covered across all three families, including JSON specs; the original command above now succeeds.\n\nFinally, `validate --help` exposed `ooxml-siw`: validation parsing ran before help routing. The routing fix lets the original help command succeed.\n\nThe recorded sequence explicitly includes the default-policy refusal and its recovery. The four completed editing recipes use only the documented commands and policies shown above. The test verifies resulting content, original-file preservation, and strict validation; optional SDK, rendering, and desktop Office proofs belong to separate gates.");
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("docs/agent-quickstart.md");
    if std::env::var("UPDATE_GOLDENS").as_deref() == Ok("1") {
        fs::write(&path, &sim.tutorial).unwrap();
    }
    let expected = fs::read_to_string(path).unwrap();
    assert!(!expected.contains('\r'), "quickstart must use LF");
    assert_eq!(
        expected, sim.tutorial,
        "regenerate only after reviewing command drift"
    );
}

#[test]
fn bare_relative_markdown_and_emitted_spec_paths_build_all_three_families() {
    let mut sim = Simulation::new();
    for (family, markdown) in [
        ("pptx", MARKDOWN),
        ("docx", MARKDOWN),
        (
            "xlsx",
            "# Data\n\n| Region | Revenue |\n| --- | --- |\n| North | 150 |\n",
        ),
    ] {
        let input = format!("{family}.md");
        let emitted = format!("{family}.json");
        let output = format!("markdown.{family}");
        let rebuilt = format!("spec.{family}");
        fs::write(sim.root.join(&input), markdown).unwrap();
        sim.json(
            &[
                "--json",
                family,
                "build",
                "--from-markdown",
                &input,
                "--emit-spec",
                &emitted,
                "--out",
                &output,
            ],
            0,
        );
        sim.json(
            &[
                "--json", family, "build", "--spec", &emitted, "--out", &rebuilt,
            ],
            0,
        );
        for path in [&output, &rebuilt] {
            sim.json(&["--json", "validate", "--strict", path], 0);
            schema_proof(&sim.root.join(path));
        }
        assert_eq!(
            fs::read(sim.root.join(output)).unwrap(),
            fs::read(sim.root.join(rebuilt)).unwrap(),
            "{family} relative Markdown/spec output differs"
        );
    }
}

fn schema_proof(path: &std::path::Path) {
    // Tool inventory stays outside the generated tutorial and its drift contract.
    let output = Command::new(env!("CARGO_BIN_EXE_ooxml"))
        .args(["--json", "conformance", "check"])
        .arg(path)
        .arg("--openxml-sdk")
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    let schema = report["checks"]
        .as_array()
        .unwrap()
        .iter()
        .find(|check| check["name"] == "schema")
        .unwrap();
    if schema["status"] == "skipped" {
        assert!(
            !std::env::var("OOXML_REQUIRE_OPENXML_SDK").is_ok_and(|value| value == "1"),
            "required SDK unavailable"
        );
        eprintln!(
            "{}: optional SDK unavailable",
            path.file_name().unwrap().to_string_lossy()
        );
    } else {
        assert_eq!(schema["schemaCheck"]["valid"], true, "{schema}");
    }
}
