pub(crate) struct InspectProbeCase<I> {
    pub(crate) family: &'static str,
    pub(crate) key: I,
    pub(crate) canonical: &'static str,
    pub(crate) aliases: &'static [&'static str],
    pub(crate) fixture: &'static str,
    pub(crate) args: serde_json::Value,
    pub(crate) direct_argv: &'static [&'static str],
}

pub(crate) fn inspect_probe_cases<I>(
    mut resolve: impl FnMut(&'static str) -> I,
) -> Vec<InspectProbeCase<I>> {
    vec![
        probe(
            &mut resolve,
            "xlsx",
            "xlsx ranges export",
            &[],
            "xlsx-minimal",
            serde_json::json!({"sheet": "1", "range": "A1"}),
            &[
                "xlsx", "ranges", "export", "{file}", "--sheet", "1", "--range", "A1",
            ],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx cells extract",
            &[],
            "xlsx-minimal",
            serde_json::json!({}),
            &["xlsx", "cells", "extract", "{file}"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx comments list",
            &[],
            "xlsx-minimal",
            serde_json::json!({}),
            &["xlsx", "comments", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx conditional-formats list",
            &[
                "xlsx conditional-formatting list",
                "xlsx conditional-format list",
                "xlsx cf list",
            ],
            "xlsx-cf",
            serde_json::json!({"sheet": "1"}),
            &[
                "xlsx",
                "conditional-formats",
                "list",
                "{file}",
                "--sheet",
                "1",
            ],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx conditional-formats show",
            &[
                "xlsx conditional-formatting show",
                "xlsx conditional-format show",
                "xlsx cf show",
            ],
            "xlsx-cf",
            serde_json::json!({"sheet": "1", "rule": "block:1/rule:1"}),
            &[
                "xlsx",
                "conditional-formats",
                "show",
                "{file}",
                "--sheet",
                "1",
                "--rule",
                "block:1/rule:1",
            ],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx sheets list",
            &[],
            "xlsx-minimal",
            serde_json::json!({}),
            &["xlsx", "sheets", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx sheets show",
            &[],
            "xlsx-minimal",
            serde_json::json!({"sheet": "1"}),
            &["xlsx", "sheets", "show", "{file}", "--sheet", "1"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx freeze show",
            &[],
            "xlsx-hyperlinks",
            serde_json::json!({"sheet": "1"}),
            &["xlsx", "freeze", "show", "{file}", "--sheet", "1"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx hyperlinks list",
            &[],
            "xlsx-hyperlinks",
            serde_json::json!({"sheet": "1"}),
            &["xlsx", "hyperlinks", "list", "{file}", "--sheet", "1"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx hyperlinks show",
            &[],
            "xlsx-hyperlinks",
            serde_json::json!({"sheet": "1", "cell": "A1"}),
            &[
                "xlsx",
                "hyperlinks",
                "show",
                "{file}",
                "--sheet",
                "1",
                "--cell",
                "A1",
            ],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx filters-sorts show",
            &[],
            "xlsx-minimal",
            serde_json::json!({"sheet": "1"}),
            &["xlsx", "filters-sorts", "show", "{file}", "--sheet", "1"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx names list",
            &[],
            "xlsx-names",
            serde_json::json!({}),
            &["xlsx", "names", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx names show",
            &[],
            "xlsx-names",
            serde_json::json!({"name": "GlobalName"}),
            &["xlsx", "names", "show", "{file}", "--name", "GlobalName"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx tables list",
            &[],
            "xlsx-tables",
            serde_json::json!({"sheet": "Data"}),
            &["xlsx", "tables", "list", "{file}", "--sheet", "Data"],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx tables show",
            &[],
            "xlsx-tables",
            serde_json::json!({"sheet": "Data", "table": "Sales"}),
            &[
                "xlsx", "tables", "show", "{file}", "--sheet", "Data", "--table", "Sales",
            ],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx tables export",
            &[],
            "xlsx-tables",
            serde_json::json!({"sheet": "Data", "table": "Sales"}),
            &[
                "xlsx", "tables", "export", "{file}", "--sheet", "Data", "--table", "Sales",
            ],
        ),
        probe(
            &mut resolve,
            "xlsx",
            "xlsx workbook metadata inspect",
            &[],
            "xlsx-minimal",
            serde_json::json!({}),
            &["xlsx", "workbook", "metadata", "inspect", "{file}"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx text",
            &[],
            "docx-minimal",
            serde_json::json!({}),
            &["docx", "text", "{file}"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx fields list",
            &[],
            "docx-minimal",
            serde_json::json!({}),
            &["docx", "fields", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx headers list",
            &[],
            "docx-headers",
            serde_json::json!({}),
            &["docx", "headers", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx footers list",
            &[],
            "docx-headers",
            serde_json::json!({}),
            &["docx", "footers", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx headers show",
            &[],
            "docx-headers",
            serde_json::json!({"selector": "header:1:default"}),
            &[
                "docx",
                "headers",
                "show",
                "{file}",
                "--selector",
                "header:1:default",
            ],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx footers show",
            &[],
            "docx-headers",
            serde_json::json!({"id": "rId11"}),
            &["docx", "footers", "show", "{file}", "--id", "rId11"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx images list",
            &[],
            "docx-minimal",
            serde_json::json!({}),
            &["docx", "images", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx comments list",
            &[],
            "docx-minimal",
            serde_json::json!({}),
            &["docx", "comments", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx blocks",
            &[],
            "docx-mixed-blocks",
            serde_json::json!({"block": 0}),
            &["docx", "blocks", "{file}", "--block", "0"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx styles list",
            &[],
            "docx-styles",
            serde_json::json!({"type": "paragraph"}),
            &["docx", "styles", "list", "{file}", "--type", "paragraph"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx styles show",
            &[],
            "docx-styles",
            serde_json::json!({"style": "Heading2"}),
            &["docx", "styles", "show", "{file}", "--style", "Heading2"],
        ),
        probe(
            &mut resolve,
            "docx",
            "docx tables show",
            &[],
            "docx-tables",
            serde_json::json!({"table": 1}),
            &["docx", "tables", "show", "{file}", "--table", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx slides list",
            &[],
            "pptx-title-content",
            serde_json::json!({}),
            &["pptx", "slides", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx slides selectors",
            &[],
            "pptx-title-content",
            serde_json::json!({"slide": 1}),
            &["pptx", "slides", "selectors", "{file}", "--slide", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx slides show",
            &[],
            "pptx-title-content",
            serde_json::json!({"slide": 1}),
            &["pptx", "slides", "show", "{file}", "--slide", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx extract text",
            &[],
            "pptx-title-content",
            serde_json::json!({"slide": 1}),
            &["pptx", "extract", "text", "{file}", "--slide", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx extract notes",
            &[],
            "pptx-notes",
            serde_json::json!({"slide": 1}),
            &["pptx", "extract", "notes", "{file}", "--slide", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx notes show",
            &[],
            "pptx-notes",
            serde_json::json!({"slide": 1}),
            &["pptx", "notes", "show", "{file}", "--slide", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx comments list",
            &[],
            "pptx-title-content",
            serde_json::json!({}),
            &["pptx", "comments", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx masters list",
            &[],
            "pptx-title-content",
            serde_json::json!({}),
            &["pptx", "masters", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx masters show",
            &[],
            "pptx-title-content",
            serde_json::json!({"master": 1}),
            &["pptx", "masters", "show", "{file}", "--master", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx layouts list",
            &[],
            "pptx-title-content",
            serde_json::json!({}),
            &["pptx", "layouts", "list", "{file}"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx layouts show",
            &[],
            "pptx-title-content",
            serde_json::json!({"layout": "1"}),
            &["pptx", "layouts", "show", "{file}", "--layout", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx tables show",
            &[],
            "pptx-title-content",
            serde_json::json!({"slide": 1}),
            &["pptx", "tables", "show", "{file}", "--slide", "1"],
        ),
        probe(
            &mut resolve,
            "pptx",
            "pptx shapes show",
            &[],
            "pptx-title-content",
            serde_json::json!({"slide": 1, "includeText": true, "includeBounds": true}),
            &[
                "pptx",
                "shapes",
                "show",
                "{file}",
                "--slide",
                "1",
                "--include-text",
                "--include-bounds",
            ],
        ),
    ]
}

fn probe<I>(
    resolve: &mut impl FnMut(&'static str) -> I,
    family: &'static str,
    canonical: &'static str,
    aliases: &'static [&'static str],
    fixture: &'static str,
    args: serde_json::Value,
    direct_argv: &'static [&'static str],
) -> InspectProbeCase<I> {
    InspectProbeCase {
        family,
        key: resolve(canonical),
        canonical,
        aliases,
        fixture,
        args,
        direct_argv,
    }
}
