use super::{PptxCommandId, direct, flag, inspect, mutation, spec};

pub(super) const COMMAND_COUNT: usize = 15;

pub(super) fn command_specs() -> Vec<super::CommandSpec> {
    vec![
        spec(
            PptxCommandId::Scaffold,
            &["pptx", "scaffold"],
            "scaffold <output.pptx> (or --out <output.pptx>)",
            "Create a minimal PowerPoint presentation from scratch.",
            &["package", "slide", "shape"],
            vec![
                flag(
                    "--out",
                    "out",
                    "string",
                    "output presentation path; accepted as an alternative to positional <output.pptx>",
                ),
                flag("--title", "title", "string", "initial title text"),
                flag("--subtitle", "subtitle", "string", "initial subtitle text"),
                flag(
                    "--force",
                    "force",
                    "bool",
                    "replace an existing output file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation of the generated package",
                ),
            ],
            super::ExecutionSupport::DirectOnly { reason: None },
            None,
        ),
        spec(
            PptxCommandId::ShapesShow,
            &["pptx", "shapes", "show"],
            "show <file> --slide <n>",
            "Show targetable shapes on a slide.",
            &["slide", "shape"],
            vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--include-text",
                    "includeText",
                    "bool",
                    "include text preview/content where available",
                ),
                flag(
                    "--include-bounds",
                    "includeBounds",
                    "bool",
                    "include explicit shape bounds where available",
                ),
            ],
            inspect("read-only command; generated by slides list/show"),
            None,
        ),
        spec(
            PptxCommandId::ShapesGet,
            &["pptx", "shapes", "get"],
            "get <file> --slide <n> --target <selector>",
            "Read one targetable shape on a slide.",
            &["slide", "shape"],
            vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--target",
                    "target",
                    "string",
                    "shape selector such as title, body, shape:3, or ~Title 1",
                ),
                flag(
                    "--include-text",
                    "includeText",
                    "bool",
                    "include text preview/content where available",
                ),
                flag(
                    "--include-bounds",
                    "includeBounds",
                    "bool",
                    "include explicit shape bounds where available",
                ),
            ],
            direct("read-only command; generated by shapes show"),
            None,
        ),
        spec(
            PptxCommandId::AddTextbox,
            &["pptx", "add-textbox"],
            "add-textbox <file> --slide <n> --text <text> --x <emu> --y <emu> --cx <emu> --cy <emu>",
            "Insert a text box shape on a slide at explicit EMU bounds.",
            &["slide", "shape"],
            with_output_flags(vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag("--text", "text", "string", "text box content"),
                flag("--x", "x", "int", "left position in EMUs"),
                flag("--y", "y", "int", "top position in EMUs"),
                flag("--cx", "cx", "int", "width in EMUs"),
                flag("--cy", "cy", "int", "height in EMUs"),
                flag("--name", "name", "string", "optional shape name"),
                flag("--font-size", "fontSize", "number", "font size in points"),
                flag("--font", "font", "string", "Latin font family"),
                flag("--bold", "bold", "bool", "set text bold"),
                flag("--italic", "italic", "bool", "set text italic"),
                flag("--color", "color", "string", "RGB hex text color"),
                flag("--level", "level", "int", "paragraph indent level"),
                flag("--align", "align", "string", "paragraph alignment token"),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::TextSet,
            &["pptx", "text", "set"],
            "set <file>",
            "Set run-level text styling on a slide shape paragraph/run.",
            &["slide", "shape", "style", "hyperlink"],
            with_output_flags(vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--target",
                    "target",
                    "string",
                    "shape selector such as title, body, shape:3, or ~Shape Name",
                ),
                flag(
                    "--paragraph",
                    "paragraph",
                    "int",
                    "0-based paragraph index within the shape",
                ),
                flag(
                    "--run-index",
                    "runIndex",
                    "int",
                    "0-based text run index within the paragraph; omit to apply to all runs",
                ),
                flag("--bold", "bold", "bool", "set bold on/off"),
                flag("--italic", "italic", "bool", "set italic on/off"),
                flag(
                    "--underline",
                    "underline",
                    "string",
                    "underline kind such as sng, dbl, heavy, dotted, dash, wavy, or none",
                ),
                flag("--font-size", "fontSize", "float64", "font size in points"),
                flag("--color", "color", "string", "RGB hex color"),
                flag("--font-family", "fontFamily", "string", "latin font family"),
                flag(
                    "--hyperlink",
                    "hyperlink",
                    "string",
                    "external hyperlink URL",
                ),
                flag("--remove-bold", "removeBold", "bool", "remove bold"),
                flag("--remove-italic", "removeItalic", "bool", "remove italic"),
                flag(
                    "--remove-underline",
                    "removeUnderline",
                    "bool",
                    "remove underline",
                ),
                flag(
                    "--remove-font-size",
                    "removeFontSize",
                    "bool",
                    "remove font size",
                ),
                flag("--remove-color", "removeColor", "bool", "remove color"),
                flag(
                    "--remove-font-family",
                    "removeFontFamily",
                    "bool",
                    "remove font family",
                ),
                flag(
                    "--remove-hyperlink",
                    "removeHyperlink",
                    "bool",
                    "remove hyperlink",
                ),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::FieldsInspect,
            &["pptx", "fields", "inspect"],
            "inspect <file>",
            "Inspect PowerPoint header/footer field visibility defaults and slide placeholders.",
            &["field", "footer", "slide", "master"],
            vec![],
            direct("read-only command; reports existing field placeholders without creating them"),
            None,
        ),
        spec(
            PptxCommandId::FieldsSet,
            &["pptx", "fields", "set"],
            "set <file>",
            "Update PowerPoint header/footer field visibility, synthesizing missing footer placeholders when shown.",
            &["field", "footer", "slide", "master"],
            with_output_flags(vec![
                flag(
                    "--footer",
                    "footer",
                    "string",
                    "footer text; updates existing footer placeholders and creates missing visible footer placeholders",
                ),
                flag(
                    "--show-footer",
                    "showFooter",
                    "bool",
                    "toggle master footer placeholder visibility",
                ),
                flag(
                    "--show-slide-number",
                    "showSlideNumber",
                    "bool",
                    "toggle master slide-number placeholder visibility",
                ),
                flag(
                    "--show-date",
                    "showDate",
                    "bool",
                    "toggle master date placeholder visibility",
                ),
                flag(
                    "--date-format",
                    "dateFormat",
                    "string",
                    "date field format: auto, datetime, or date-only",
                ),
            ]),
            direct(
                "direct CLI mutation; synthesizes missing footer placeholders when --show-footer=true or --footer is requested",
            ),
            None,
        ),
        spec(
            PptxCommandId::ThemeUpdate,
            &["pptx", "theme", "update"],
            "update <file>",
            "Update deck theme colors and Latin major/minor fonts.",
            &["style", "slide"],
            with_output_flags(vec![
                flag(
                    "--color",
                    "color",
                    "string",
                    "repeatable theme color assignment name=RRGGBB",
                ),
                flag(
                    "--major-font",
                    "majorFont",
                    "string",
                    "Latin major font family",
                ),
                flag(
                    "--minor-font",
                    "minorFont",
                    "string",
                    "Latin minor font family",
                ),
                flag("--mode", "mode", "string", "theme mode: deck or slide"),
                flag(
                    "--slide",
                    "slide",
                    "int",
                    "1-based slide number for slide mode",
                ),
                flag(
                    "--for-slides",
                    "forSlides",
                    "string",
                    "slide selector list/range for slide mode",
                ),
            ]),
            direct(
                "direct CLI mutation; deck mode is supported, slide color mode preserves the legacy error behavior",
            ),
            None,
        ),
        spec(
            PptxCommandId::TranslateExport,
            &["pptx", "translate", "export"],
            "export <file>",
            "Export PPTX slide and notes text to a translation manifest.",
            &["slide", "shape"],
            vec![
                flag("--slide", "slide", "int", "repeatable 1-based slide number"),
                flag(
                    "--include-notes",
                    "includeNotes",
                    "bool",
                    "include speaker notes",
                ),
                flag(
                    "--source-lang",
                    "sourceLang",
                    "string",
                    "source language tag",
                ),
                flag(
                    "--target-lang",
                    "targetLang",
                    "string",
                    "target language tag",
                ),
                flag("--format", "format", "string", "json"),
            ],
            direct("read-only translation workflow; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::TranslateApply,
            &["pptx", "translate", "apply"],
            "apply <file> <manifest>",
            "Apply a translation manifest to PPTX slide text.",
            &["slide", "shape"],
            vec![
                flag(
                    "--stale",
                    "stale",
                    "string",
                    "stale source handling: skip, warn, or error",
                ),
                flag("--output", "output", "string", "output file path"),
            ],
            direct("direct CLI translation mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::PlaceImage,
            &["pptx", "place", "image"],
            "image <file> --slide <n> --image <path> --x <emu> --y <emu> --cx <emu> --cy <emu>",
            "Place a new image shape on a slide at explicit EMU bounds.",
            &["slide", "shape", "image"],
            with_output_flags(vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag("--image", "image", "string", "local image file path"),
                flag("--x", "x", "int", "left position in EMUs"),
                flag("--y", "y", "int", "top position in EMUs"),
                flag("--cx", "cx", "int", "width in EMUs"),
                flag("--cy", "cy", "int", "height in EMUs"),
                flag("--name", "name", "string", "optional picture shape name"),
                flag(
                    "--fit-mode",
                    "fitMode",
                    "string",
                    "fit mode: contain/fit or cover/crop",
                ),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::PlaceTable,
            &["pptx", "place", "table"],
            "table <file> --slide <n> --data <path> --x <emu> --y <emu> --cx <emu>",
            "Place a new table shape on a slide from CSV or JSON data.",
            &["slide", "shape", "table"],
            with_output_flags(place_table_flags()),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::PlaceTableFromXlsx,
            &["pptx", "place", "table-from-xlsx"],
            "table-from-xlsx <file> --slide <n> --workbook <xlsx> (--sheet <selector> --range <a1>|--table <selector>) --x <emu> --y <emu> --cx <emu>",
            "Place a new PowerPoint table from an XLSX range or workbook table.",
            &["slide", "shape", "table", "sheet", "range"],
            with_output_flags({
                let mut flags = vec![
                    flag("--slide", "slide", "int", "1-based slide number"),
                    flag(
                        "--workbook",
                        "workbook",
                        "string",
                        "source XLSX workbook path",
                    ),
                    flag("--sheet", "sheet", "string", "source sheet selector"),
                    flag("--range", "range", "string", "source A1 range"),
                    flag(
                        "--table",
                        "table",
                        "string",
                        "source workbook table selector",
                    ),
                    flag(
                        "--max-cells",
                        "maxCells",
                        "int",
                        "maximum source cells to read; zero means unlimited",
                    ),
                    flag(
                        "--formula-mode",
                        "formulaMode",
                        "string",
                        "formula handling: value or formula",
                    ),
                    flag(
                        "--expect-source-range",
                        "expectSourceRange",
                        "string",
                        "fail unless the resolved source range matches this A1 range",
                    ),
                ];
                flags.extend(place_table_layout_flags());
                flags
            }),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::ShapesSetBounds,
            &["pptx", "shapes", "set-bounds"],
            "set-bounds <file> --slide <n> --target <selector> --bounds <x,y,cx,cy>",
            "Set one PowerPoint shape's explicit bounds in EMUs.",
            &["slide", "shape"],
            with_output_flags(vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--target",
                    "target",
                    "string",
                    "shape selector such as title, body, shape:3, or ~Title 1",
                ),
                flag(
                    "--bounds",
                    "bounds",
                    "string",
                    "new bounds as x,y,cx,cy EMU values",
                ),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::ShapesDelete,
            &["pptx", "shapes", "delete"],
            "delete <file> --slide <n> --target <selector>",
            "Delete one targetable PowerPoint shape from a slide.",
            &["slide", "shape"],
            with_output_flags(vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--target",
                    "target",
                    "string",
                    "shape selector such as title, body, shape:3, or ~Title 1",
                ),
            ]),
            mutation(None),
            None,
        ),
    ]
}

fn output_flags() -> Vec<super::FlagSpec> {
    vec![
        flag("--out", "out", "string", "output file path"),
        flag("--backup", "backup", "string", "backup path for --in-place"),
        flag(
            "--dry-run",
            "dryRun",
            "bool",
            "plan and validate without writing",
        ),
        flag(
            "--in-place",
            "inPlace",
            "bool",
            "write back to the input file",
        ),
        flag(
            "--no-validate",
            "noValidate",
            "bool",
            "skip strict validation of the mutated package",
        ),
    ]
}

fn with_output_flags(mut flags: Vec<super::FlagSpec>) -> Vec<super::FlagSpec> {
    flags.extend(output_flags());
    flags
}

fn place_table_flags() -> Vec<super::FlagSpec> {
    let mut flags = vec![
        flag("--slide", "slide", "int", "1-based slide number"),
        flag("--data", "data", "string", "CSV or JSON data file path"),
        flag("--format", "format", "string", "data format: csv or json"),
    ];
    flags.extend(place_table_layout_flags());
    flags
}

fn place_table_layout_flags() -> Vec<super::FlagSpec> {
    vec![
        flag("--x", "x", "int", "left position in EMUs"),
        flag("--y", "y", "int", "top position in EMUs"),
        flag("--cx", "cx", "int", "width in EMUs"),
        flag(
            "--cy",
            "cy",
            "int",
            "height in EMUs; calculated from row count when omitted or zero",
        ),
        flag("--name", "name", "string", "optional table shape name"),
        flag("--header", "header", "bool", "treat first row as a header"),
        flag(
            "--header-color",
            "headerColor",
            "string",
            "header fill color as RGB hex",
        ),
        flag("--banded-rows", "bandedRows", "bool", "alternate row fills"),
        flag(
            "--band1-color",
            "band1Color",
            "string",
            "first band fill color as RGB hex",
        ),
        flag(
            "--band2-color",
            "band2Color",
            "string",
            "second band fill color as RGB hex",
        ),
        flag("--font-size", "fontSize", "int", "font size in points"),
        flag(
            "--border-color",
            "borderColor",
            "string",
            "table border color as RGB hex",
        ),
        flag(
            "--border-width",
            "borderWidth",
            "int",
            "table border width in EMUs",
        ),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command_manifest::ExecutionSupport;

    #[test]
    fn owner_contract() {
        let specs = command_specs();
        assert_eq!(specs.len(), COMMAND_COUNT);
        assert_eq!(
            specs
                .iter()
                .filter(|spec| matches!(&spec.execution, ExecutionSupport::ServeInspect { .. }))
                .count(),
            1
        );
        assert_eq!(
            specs
                .iter()
                .filter(|spec| matches!(&spec.execution, ExecutionSupport::ServeMutation { .. }))
                .count(),
            1
        );
        assert_eq!(
            specs
                .iter()
                .filter(|spec| matches!(&spec.execution, ExecutionSupport::DirectOnly { .. }))
                .count(),
            13
        );
    }
}
