use serde_json::json;

use super::{PptxCommandId, direct, flag, spec};

pub(super) const COMMAND_COUNT: usize = 12;

pub(super) fn command_specs() -> Vec<super::CommandSpec> {
    vec![
        spec(
            PptxCommandId::ChartsList,
            &["pptx", "charts", "list"],
            "list <file> [--slide <n>]",
            "List PPTX slide charts, selectors, chart parts, series sources, cached previews, and embedded workbook links.",
            &["slide", "chart"],
            vec![slide_flag("optional 1-based slide number to search")],
            direct("read-only command; generated show commands can read back individual charts"),
            None,
        ),
        spec(
            PptxCommandId::ChartsShow,
            &["pptx", "charts", "show"],
            "show <file> [--slide <n>] [--chart <selector>]",
            "Show one PPTX slide chart, including chart type, series source formulas, cached previews, part metadata, and practical style.",
            &["slide", "chart"],
            chart_selector_flags(),
            direct("read-only command; generated by pptx charts list"),
            None,
        ),
        spec(
            PptxCommandId::ChartsCreate,
            &["pptx", "charts", "create"],
            "create <file> --slide <n> --type <type> (--values-json <json>|--values-file <path>|--source-file <xlsx> --source-range <range>)",
            "Create a new PPTX slide chart from an inline matrix or an XLSX range.",
            &["chart", "slide", "range"],
            vec![
                slide_flag("1-based slide number to add the chart to"),
                flag(
                    "--type",
                    "type",
                    "string",
                    "chart type: bar, line, area, pie, or scatter",
                ),
                flag("--title", "title", "string", "chart title"),
                flag(
                    "--values-json",
                    "valuesJson",
                    "string",
                    "inline row-major JSON matrix",
                ),
                flag(
                    "--values-file",
                    "valuesFile",
                    "string",
                    "path to an inline JSON matrix file",
                ),
                flag(
                    "--source-file",
                    "sourceFile",
                    "string",
                    "xlsx workbook to source chart data from",
                ),
                flag(
                    "--source-sheet",
                    "sourceSheet",
                    "string",
                    "source sheet number or name",
                ),
                flag(
                    "--source-range",
                    "sourceRange",
                    "string",
                    "source A1 range such as A1:C5",
                ),
                flag(
                    "--expect-source-range",
                    "expectSourceRange",
                    "string",
                    "fail unless the resolved source range matches",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "int",
                    "maximum source cells to read, 0 for unlimited",
                ),
                flag(
                    "--embed-workbook",
                    "embedWorkbook",
                    "bool",
                    "embed --source-file as the editable chart workbook",
                ),
                flag("--x", "x", "int", "left position in EMUs"),
                flag("--y", "y", "int", "top position in EMUs"),
                flag("--cx", "cx", "int", "width in EMUs"),
                flag("--cy", "cy", "int", "height in EMUs"),
                flag("--out", "out", "string", "output file path"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "plan and validate without writing",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write back to the input file",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation of the mutated package",
                ),
            ],
            direct(
                "direct CLI mutation; supports dry-run/readback commands but serve/MCP op support is not wired yet",
            ),
            Some(json!({
                "modeFlag": "--type",
                "modes": [
                    {"value": "bar", "required": ["--slide", "--type"]},
                    {"value": "line", "required": ["--slide", "--type"]},
                    {"value": "area", "required": ["--slide", "--type"]},
                    {"value": "pie", "required": ["--slide", "--type"], "notes": ["Pie charts use only the first series when the source has multiple series."]},
                    {"value": "scatter", "required": ["--slide", "--type"]}
                ],
                "sourceModes": [
                    {
                        "name": "inline-json",
                        "required": ["--values-json"],
                        "conflictsWith": ["--values-file", "--source-file", "--source-sheet", "--source-range", "--expect-source-range", "--embed-workbook"]
                    },
                    {
                        "name": "inline-file",
                        "required": ["--values-file"],
                        "conflictsWith": ["--values-json", "--source-file", "--source-sheet", "--source-range", "--expect-source-range", "--embed-workbook"]
                    },
                    {
                        "name": "external-xlsx",
                        "required": ["--source-file", "--source-range"],
                        "optional": ["--source-sheet", "--expect-source-range", "--embed-workbook"],
                        "conflictsWith": ["--values-json", "--values-file"]
                    }
                ],
                "outputRequiredOneOf": ["--out", "--in-place", "--dry-run"],
                "rules": [
                    "--slide must be a 1-based slide number.",
                    "--type is required and must be bar, line, area, pie, or scatter.",
                    "Specify exactly one source family: --values-json, --values-file, or --source-file.",
                    "--source-file requires --source-range; --source-sheet defaults to 1 when omitted."
                ]
            })),
        ),
        spec(
            PptxCommandId::ChartsUpdateData,
            &["pptx", "charts", "update-data"],
            "update-data <file> --chart <selector> --series <n> [--values <csv>|--values-json <json>] [--categories <csv>|--categories-json <json>]",
            "Update an existing PPTX chart series' stored cache and matching embedded workbook cells when available.",
            &["chart"],
            with_output_flags({
                let mut flags = chart_selector_flags();
                flags.extend([
                    flag("--series", "series", "int", "1-based chart series number"),
                    flag(
                        "--values",
                        "values",
                        "string",
                        "comma-separated values for the series values source",
                    ),
                    flag(
                        "--values-json",
                        "valuesJson",
                        "string",
                        "JSON string array for the series values source",
                    ),
                    flag(
                        "--categories",
                        "categories",
                        "string",
                        "comma-separated labels for the category source",
                    ),
                    flag(
                        "--categories-json",
                        "categoriesJson",
                        "string",
                        "JSON string array for the category source",
                    ),
                    flag(
                        "--expect-point-count",
                        "expectPointCount",
                        "int",
                        "fail unless each updated current source has this cache point count",
                    ),
                    flag(
                        "--expect-values-hash",
                        "expectValuesHash",
                        "string",
                        "fail unless current values cache has this sha256 hash",
                    ),
                ]);
                flags
            }),
            direct(
                "direct CLI mutation; edits existing chart sources and does not recalculate PowerPoint rendering",
            ),
            None,
        ),
        spec(
            PptxCommandId::ChartsSetTitle,
            &["pptx", "charts", "set-title"],
            "set-title <file> --chart <selector> --title <text>",
            "Set one PPTX chart title and optional title font styling.",
            &["slide", "chart", "style"],
            with_output_flags({
                let mut flags = chart_selector_flags();
                flags.extend([
                    flag("--title", "title", "string", "new chart title text"),
                    flag(
                        "--expect-title",
                        "expectTitle",
                        "string",
                        "fail unless the existing title matches",
                    ),
                    flag("--font-family", "fontFamily", "string", "title font family"),
                    flag(
                        "--font-size",
                        "fontSize",
                        "float",
                        "title font size in points",
                    ),
                    flag(
                        "--font-color",
                        "fontColor",
                        "string",
                        "title font color as #RRGGBB",
                    ),
                    flag(
                        "--font-bold",
                        "fontBold",
                        "bool",
                        "set title font bold on or off",
                    ),
                    flag(
                        "--font-italic",
                        "fontItalic",
                        "bool",
                        "set title font italic on or off",
                    ),
                ]);
                flags
            }),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::ChartsSetLegend,
            &["pptx", "charts", "set-legend"],
            "set-legend <file> --chart <selector> [--position <pos>] [--overlay=<bool>]",
            "Set, move, or remove one PPTX chart legend.",
            &["slide", "chart", "style"],
            with_output_flags({
                let mut flags = chart_selector_flags();
                flags.extend([
                    flag(
                        "--position",
                        "position",
                        "string",
                        "legend position: right, left, top, bottom, or none",
                    ),
                    flag(
                        "--overlay",
                        "overlay",
                        "bool",
                        "whether the legend overlays the plot area",
                    ),
                    flag(
                        "--expect-position",
                        "expectPosition",
                        "string",
                        "fail unless the existing legend position matches",
                    ),
                ]);
                flags
            }),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        fill_spec(
            PptxCommandId::ChartsSetChartAreaFill,
            &["pptx", "charts", "set-chart-area-fill"],
            "set-chart-area-fill <file> --chart <selector> --fill-color <#RRGGBB|none>",
            "Set the outer chart area fill for one PPTX chart.",
        ),
        fill_spec(
            PptxCommandId::ChartsSetPlotAreaFill,
            &["pptx", "charts", "set-plot-area-fill"],
            "set-plot-area-fill <file> --chart <selector> --fill-color <#RRGGBB|none>",
            "Set the plot area fill for one PPTX chart.",
        ),
        spec(
            PptxCommandId::ChartsSetSeriesStyle,
            &["pptx", "charts", "set-series-style"],
            "set-series-style <file> --chart <selector> --series <n>",
            "Set fill, line, and marker style for one PPTX chart series.",
            &["slide", "chart", "style"],
            with_output_flags({
                let mut flags = chart_selector_flags();
                flags.extend([
                    flag("--series", "series", "int", "1-based series number"),
                    flag(
                        "--fill-color",
                        "fillColor",
                        "string",
                        "series fill color as #RRGGBB, or none",
                    ),
                    flag(
                        "--line-color",
                        "lineColor",
                        "string",
                        "series line color as #RRGGBB, or none",
                    ),
                    flag(
                        "--line-width-pt",
                        "lineWidthPt",
                        "float",
                        "series line width in points",
                    ),
                    flag(
                        "--marker-symbol",
                        "markerSymbol",
                        "string",
                        "marker symbol for marker-compatible charts",
                    ),
                    flag(
                        "--marker-size",
                        "markerSize",
                        "int",
                        "marker size from 2 to 72",
                    ),
                    flag(
                        "--expect-series-count",
                        "expectSeriesCount",
                        "int",
                        "fail unless the chart has this many series",
                    ),
                ]);
                flags
            }),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::ChartsSetAxis,
            &["pptx", "charts", "set-axis"],
            "set-axis <file> --chart <selector> --axis <category|value>",
            "Set title, visibility, scale, number format, gridlines, or tick-label font on one PPTX chart axis.",
            &["slide", "chart", "style"],
            with_output_flags({
                let mut flags = chart_selector_flags();
                flags.extend([
                    flag(
                        "--axis",
                        "axis",
                        "string",
                        "axis to edit: category or value",
                    ),
                    flag("--title", "title", "string", "axis title text"),
                    flag(
                        "--expect-axis-title",
                        "expectAxisTitle",
                        "string",
                        "fail unless the existing axis title matches",
                    ),
                    flag("--hidden", "hidden", "bool", "hide or show the axis"),
                    flag("--min", "min", "float", "axis scale minimum"),
                    flag("--max", "max", "float", "axis scale maximum"),
                    flag(
                        "--major-unit",
                        "majorUnit",
                        "float",
                        "major unit interval for value axes",
                    ),
                    flag(
                        "--number-format",
                        "numberFormat",
                        "string",
                        "axis number format code",
                    ),
                    flag(
                        "--major-gridlines",
                        "majorGridlines",
                        "bool",
                        "show or hide major gridlines",
                    ),
                    flag(
                        "--minor-gridlines",
                        "minorGridlines",
                        "bool",
                        "show or hide minor gridlines",
                    ),
                    flag(
                        "--tick-label-font-family",
                        "tickLabelFontFamily",
                        "string",
                        "tick-label font family",
                    ),
                    flag(
                        "--tick-label-font-size",
                        "tickLabelFontSize",
                        "float",
                        "tick-label font size in points",
                    ),
                    flag(
                        "--tick-label-font-color",
                        "tickLabelFontColor",
                        "string",
                        "tick-label font color as #RRGGBB",
                    ),
                    flag(
                        "--tick-label-font-bold",
                        "tickLabelFontBold",
                        "bool",
                        "set tick-label font bold on or off",
                    ),
                    flag(
                        "--tick-label-font-italic",
                        "tickLabelFontItalic",
                        "bool",
                        "set tick-label font italic on or off",
                    ),
                    flag(
                        "--title-font-family",
                        "titleFontFamily",
                        "string",
                        "axis title font family",
                    ),
                    flag(
                        "--title-font-size",
                        "titleFontSize",
                        "float",
                        "axis title font size in points",
                    ),
                    flag(
                        "--title-font-color",
                        "titleFontColor",
                        "string",
                        "axis title font color as #RRGGBB",
                    ),
                    flag(
                        "--title-font-bold",
                        "titleFontBold",
                        "bool",
                        "set axis title font bold on or off",
                    ),
                    flag(
                        "--title-font-italic",
                        "titleFontItalic",
                        "bool",
                        "set axis title font italic on or off",
                    ),
                    flag(
                        "--expect-axis-count",
                        "expectAxisCount",
                        "int",
                        "fail unless the chart has this many axes",
                    ),
                ]);
                flags
            }),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::ChartsConvertType,
            &["pptx", "charts", "convert-type"],
            "convert-type <file> --chart <selector> --to <type>",
            "Convert one PPTX chart between bar, column, line, area, pie, and scatter where the existing data shape can be preserved.",
            &["slide", "chart", "style"],
            with_output_flags({
                let mut flags = chart_selector_flags();
                flags.extend([
                    flag(
                        "--to",
                        "to",
                        "string",
                        "target chart type: bar, column, line, area, pie, or scatter",
                    ),
                    flag(
                        "--expect-type",
                        "expectType",
                        "string",
                        "fail unless the current chart type matches",
                    ),
                ]);
                flags
            }),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::ChartsCopyStyle,
            &["pptx", "charts", "copy-style"],
            "copy-style <file> --chart <selector> --from <template.pptx>",
            "Copy practical chart styling from a template PPTX chart without changing target data or labels.",
            &["slide", "chart", "style"],
            with_output_flags(vec![
                slide_flag("optional 1-based slide number for the target chart"),
                flag("--chart", "chart", "string", "target chart selector"),
                flag(
                    "--to-chart",
                    "toChart",
                    "string",
                    "target chart selector alias",
                ),
                flag("--from", "from", "string", "template PPTX file"),
                flag(
                    "--from-slide",
                    "fromSlide",
                    "int",
                    "optional 1-based template slide number",
                ),
                flag(
                    "--from-chart",
                    "fromChart",
                    "string",
                    "template chart selector",
                ),
                flag(
                    "--expect-series-count",
                    "expectSeriesCount",
                    "int",
                    "fail unless the target chart has this many series",
                ),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
    ]
}

fn fill_spec(
    id: PptxCommandId,
    path: &'static [&'static str],
    use_text: &'static str,
    short: &'static str,
) -> super::CommandSpec {
    spec(
        id,
        path,
        use_text,
        short,
        &["slide", "chart", "style"],
        with_output_flags({
            let mut flags = chart_selector_flags();
            flags.extend([
                flag(
                    "--fill-color",
                    "fillColor",
                    "string",
                    "new fill color as #RRGGBB, or none",
                ),
                flag(
                    "--expect-fill",
                    "expectFill",
                    "string",
                    "fail unless the existing fill matches",
                ),
            ]);
            flags
        }),
        direct("direct CLI mutation; serve/MCP op support is not wired yet"),
        None,
    )
}

fn slide_flag(description: &'static str) -> super::FlagSpec {
    flag("--slide", "slide", "int", description)
}

fn chart_selector_flags() -> Vec<super::FlagSpec> {
    vec![
        slide_flag("optional 1-based slide number to search"),
        flag(
            "--chart",
            "chart",
            "string",
            "chart selector from pptx charts list",
        ),
    ]
}

fn with_output_flags(mut flags: Vec<super::FlagSpec>) -> Vec<super::FlagSpec> {
    flags.extend([
        flag("--out", "out", "string", "output file path"),
        flag("--backup", "backup", "string", "backup path for --in-place"),
        flag(
            "--dry-run",
            "dryRun",
            "bool",
            "plan and validate without writing",
        ),
        flag(
            "--in-place",
            "inPlace",
            "bool",
            "write back to the input file",
        ),
        flag(
            "--no-validate",
            "noValidate",
            "bool",
            "skip strict validation of the mutated package",
        ),
    ]);
    flags
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command_manifest::ExecutionSupport;

    #[test]
    fn owner_contract() {
        let specs = command_specs();
        assert_eq!(specs.len(), COMMAND_COUNT);
        assert!(
            specs
                .iter()
                .all(|spec| matches!(&spec.execution, ExecutionSupport::DirectOnly { .. }))
        );
        assert_eq!(
            specs
                .iter()
                .filter(|spec| spec.flag_constraints.is_some())
                .count(),
            1
        );
    }
}
