use super::{PptxCommandId, direct, flag, inspect, spec};

pub(super) const COMMAND_COUNT: usize = 12;

pub(super) fn command_specs() -> Vec<super::CommandSpec> {
    vec![
        spec(
            PptxCommandId::MastersList,
            &["pptx", "masters", "list"],
            "list <file>",
            "List slide masters with stable selectors, layout counts, and theme links.",
            &["master", "layout"],
            vec![],
            inspect("read-only command; call via inspect in serve/MCP"),
            None,
        ),
        spec(
            PptxCommandId::MastersShow,
            &["pptx", "masters", "show"],
            "show <file> --master <n>",
            "Show one slide master, linked layouts, placeholders, theme, and text style summaries.",
            &["master", "layout", "placeholder"],
            vec![flag(
                "--master",
                "master",
                "int",
                "1-based master number; default 1",
            )],
            inspect("read-only command; generated by masters list"),
            None,
        ),
        spec(
            PptxCommandId::MastersAddPlaceholder,
            &["pptx", "masters", "add-placeholder"],
            "add-placeholder <file> --master <n> --type <text|pic> --bounds <x,y,cx,cy>",
            "Add a text or picture placeholder to a slide master.",
            &["master", "placeholder"],
            with_output_flags(vec![
                flag("--master", "master", "int", "1-based master number"),
                flag("--type", "type", "string", "placeholder type: text or pic"),
                flag(
                    "--bounds",
                    "bounds",
                    "string",
                    "placeholder bounds as x,y,cx,cy EMU values",
                ),
                flag(
                    "--idx",
                    "idx",
                    "int",
                    "placeholder index; omit or pass -1 to auto-allocate",
                ),
                flag("--size", "size", "string", "optional placeholder size enum"),
                flag(
                    "--orient",
                    "orient",
                    "string",
                    "optional placeholder orientation",
                ),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::MastersImport,
            &["pptx", "masters", "import"],
            "import <file> --source <pptx> --master <n>",
            "Import one slide master and its layouts from another PowerPoint presentation.",
            &["master", "layout", "theme"],
            with_output_flags(vec![
                flag("--source", "source", "string", "source PPTX file path"),
                flag("--master", "master", "int", "1-based source master number"),
                flag(
                    "--theme-policy",
                    "themePolicy",
                    "string",
                    "theme handling policy: reuse or import",
                ),
            ]),
            direct("direct CLI cross-package mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::LayoutsList,
            &["pptx", "layouts", "list"],
            "list <file>",
            "List slide layouts with stable selectors and placeholder summaries.",
            &["layout", "placeholder"],
            vec![flag(
                "--master",
                "master",
                "int",
                "optional 1-based master number to filter layouts",
            )],
            inspect("read-only command; call via inspect in serve/MCP"),
            None,
        ),
        spec(
            PptxCommandId::LayoutsShow,
            &["pptx", "layouts", "show"],
            "show <file> --layout <selector>",
            "Show one slide layout, placeholders, and theme/default text style context.",
            &["layout", "placeholder"],
            vec![layout_flag(
                "layout number or exact layout name from layouts list",
            )],
            inspect("read-only command; generated by slides list/show"),
            None,
        ),
        spec(
            PptxCommandId::LayoutsClone,
            &["pptx", "layouts", "clone"],
            "clone <file> --layout <selector> --name <name>",
            "Clone an existing slide layout under the same master.",
            &["layout"],
            with_output_flags(vec![
                layout_flag("layout number or exact layout name from layouts list"),
                flag("--name", "name", "string", "new layout name"),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::LayoutsImport,
            &["pptx", "layouts", "import"],
            "import <file> --source <pptx> --layout <selector>",
            "Import one slide layout from another PowerPoint presentation.",
            &["layout", "master", "theme"],
            with_output_flags(vec![
                flag("--source", "source", "string", "source PPTX file path"),
                layout_flag("layout number or exact source layout name"),
                flag(
                    "--theme-policy",
                    "themePolicy",
                    "string",
                    "theme handling policy: reuse or import",
                ),
            ]),
            direct("direct CLI cross-package mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::LayoutsRename,
            &["pptx", "layouts", "rename"],
            "rename <file> --layout <selector> --name <name>",
            "Rename one PowerPoint slide layout.",
            &["layout"],
            with_output_flags(vec![
                layout_flag("layout number or exact layout name from layouts list"),
                flag("--name", "name", "string", "new layout name"),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::LayoutsSetBounds,
            &["pptx", "layouts", "set-bounds"],
            "set-bounds <file> --layout <selector> --target <selector> --bounds <x,y,cx,cy>",
            "Set explicit bounds for one layout shape or placeholder.",
            &["layout", "placeholder", "shape"],
            with_output_flags(vec![
                layout_flag("layout number or exact layout name from layouts list"),
                target_flag(),
                flag(
                    "--bounds",
                    "bounds",
                    "string",
                    "new bounds as x,y,cx,cy EMU values",
                ),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::LayoutsDeleteShape,
            &["pptx", "layouts", "delete-shape"],
            "delete-shape <file> --layout <selector> --target <selector>",
            "Delete one shape or placeholder from a slide layout.",
            &["layout", "placeholder", "shape"],
            with_output_flags(vec![
                layout_flag("layout number or exact layout name from layouts list"),
                target_flag(),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::LayoutsAddPlaceholder,
            &["pptx", "layouts", "add-placeholder"],
            "add-placeholder <file> --layout <selector> --type <text|pic> --bounds <x,y,cx,cy>",
            "Add a text or picture placeholder to a slide layout.",
            &["layout", "placeholder"],
            with_output_flags(vec![
                layout_flag("layout number or exact layout name from layouts list"),
                flag("--type", "type", "string", "placeholder type: text or pic"),
                flag(
                    "--bounds",
                    "bounds",
                    "string",
                    "placeholder bounds as x,y,cx,cy EMU values",
                ),
                flag(
                    "--idx",
                    "idx",
                    "int",
                    "placeholder index; omit or pass -1 to auto-allocate",
                ),
                flag("--size", "size", "string", "optional placeholder size enum"),
                flag(
                    "--orient",
                    "orient",
                    "string",
                    "optional placeholder orientation",
                ),
            ]),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
    ]
}

fn layout_flag(description: &'static str) -> super::FlagSpec {
    flag("--layout", "layout", "string", description)
}

fn target_flag() -> super::FlagSpec {
    flag(
        "--target",
        "target",
        "string",
        "layout shape selector such as title, body:1, pic:0, shape:3, or ~Picture Placeholder 0",
    )
}

fn with_output_flags(mut flags: Vec<super::FlagSpec>) -> Vec<super::FlagSpec> {
    flags.extend([
        flag("--out", "out", "string", "output file path"),
        flag("--backup", "backup", "string", "backup path for --in-place"),
        flag(
            "--dry-run",
            "dryRun",
            "bool",
            "plan and validate without writing",
        ),
        flag(
            "--in-place",
            "inPlace",
            "bool",
            "write back to the input file",
        ),
        flag(
            "--no-validate",
            "noValidate",
            "bool",
            "skip strict validation of the mutated package",
        ),
    ]);
    flags
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::command_manifest::ExecutionSupport;

    #[test]
    fn owner_contract() {
        let specs = command_specs();
        assert_eq!(specs.len(), COMMAND_COUNT);
        assert_eq!(
            specs
                .iter()
                .filter(|spec| matches!(&spec.execution, ExecutionSupport::ServeInspect { .. }))
                .count(),
            4
        );
        assert_eq!(
            specs
                .iter()
                .filter(|spec| matches!(&spec.execution, ExecutionSupport::DirectOnly { .. }))
                .count(),
            8
        );
    }
}
