use super::{PptxCommandId, direct, flag, inspect, spec};

pub(super) const COMMAND_COUNT: usize = 11;

pub(super) fn command_specs() -> Vec<super::CommandSpec> {
    vec![
        spec(
            PptxCommandId::SlidesList,
            &["pptx", "slides", "list"],
            "list <file>",
            "List slides and stable slide selectors.",
            &["slide", "shape"],
            vec![],
            inspect("read-only command; call via inspect in serve/MCP"),
            None,
        ),
        spec(
            PptxCommandId::SlidesSelectors,
            &["pptx", "slides", "selectors"],
            "selectors <file> --slide <n>",
            "List targetable selectors for a slide.",
            &["slide", "shape"],
            vec![flag("--slide", "slide", "int", "1-based slide number")],
            inspect("read-only command; generated by slides list/show"),
            None,
        ),
        spec(
            PptxCommandId::SlidesShow,
            &["pptx", "slides", "show"],
            "show <file>",
            "Show slide text and stable selectors.",
            &["slide", "shape"],
            vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--include-text",
                    "includeText",
                    "bool",
                    "include visible text",
                ),
                flag(
                    "--include-bounds",
                    "includeBounds",
                    "bool",
                    "include shape bounds when available",
                ),
            ],
            inspect("read-only command; call via inspect in serve/MCP"),
            None,
        ),
        spec(
            PptxCommandId::SlidesDelete,
            &["pptx", "slides", "delete"],
            "delete <file> <slide-number>",
            "Delete one slide from a PowerPoint presentation.",
            &["slide"],
            mutation_output_flags(),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::SlidesMove,
            &["pptx", "slides", "move"],
            "move <file> <from-position> <to-position>",
            "Move one slide to another position in a PowerPoint presentation.",
            &["slide"],
            mutation_output_flags(),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::SlidesReorder,
            &["pptx", "slides", "reorder"],
            "reorder <file> <order>",
            "Reorder all slides using a comma-separated 1-based permutation.",
            &["slide"],
            mutation_output_flags(),
            direct("direct CLI mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::SlidesImportSlide,
            &["pptx", "slides", "import-slide"],
            "import-slide <file> --source <pptx> --slide <n>",
            "Import one slide from another PowerPoint presentation.",
            &["slide", "layout", "master", "theme"],
            with_output_flags(vec![
                flag("--source", "source", "string", "source PPTX file path"),
                flag("--slide", "slide", "int", "1-based source slide number"),
                flag(
                    "--insert-after",
                    "insertAfter",
                    "int",
                    "insert after this 1-based target slide; default appends",
                ),
                flag(
                    "--layout-policy",
                    "layoutPolicy",
                    "string",
                    "layout handling policy: reuse or import",
                ),
                flag(
                    "--theme-policy",
                    "themePolicy",
                    "string",
                    "theme handling policy: reuse or import",
                ),
                flag(
                    "--notes-policy",
                    "notesPolicy",
                    "string",
                    "notes handling policy: drop or clone",
                ),
            ]),
            direct("direct CLI cross-package mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::SlidesMerge,
            &["pptx", "slides", "merge"],
            "merge <target-file> <source-file>",
            "Append all slides from one PowerPoint presentation to another.",
            &["slide", "layout", "master", "theme"],
            with_output_flags(vec![
                flag(
                    "--layout-policy",
                    "layoutPolicy",
                    "string",
                    "layout handling policy: reuse or import",
                ),
                flag(
                    "--theme-policy",
                    "themePolicy",
                    "string",
                    "theme handling policy: reuse or import",
                ),
            ]),
            direct("direct CLI cross-package mutation; serve/MCP op support is not wired yet"),
            None,
        ),
        spec(
            PptxCommandId::CloneSlide,
            &["pptx", "clone-slide"],
            "clone-slide <file> --slide <n>",
            "Clone a slide within a PowerPoint presentation, including notes when present.",
            &["slide"],
            with_output_flags(vec![
                flag("--slide", "slide", "int", "1-based source slide number"),
                flag(
                    "--insert-after",
                    "insertAfter",
                    "int",
                    "insert the clone after this 1-based slide number; defaults to the source slide",
                ),
            ]),
            direct(
                "direct CLI mutation; serve/MCP op support and deep-copy of non-notes media/chart related parts are not wired in this slice",
            ),
            None,
        ),
        spec(
            PptxCommandId::NewSlideFromLayout,
            &["pptx", "new-slide-from-layout"],
            "new-slide-from-layout <file> --layout <selector>",
            "Create a new slide from an existing layout and optionally fill text placeholders.",
            &["slide", "layout", "placeholder"],
            with_output_flags(vec![
                flag(
                    "--layout",
                    "layout",
                    "string",
                    "layout number or exact layout name from layouts list",
                ),
                flag(
                    "--set-text",
                    "setText",
                    "string",
                    "repeatable placeholder text assignment key=value",
                ),
                flag(
                    "--insert-after",
                    "insertAfter",
                    "int",
                    "insert after this 1-based slide number; default appends at end",
                ),
            ]),
            direct(
                "Rust port slice supports --set-text; rich text, image fills, and bullet formatting are deferred",
            ),
            None,
        ),
        spec(
            PptxCommandId::ValidateLayout,
            &["pptx", "validate-layout"],
            "validate-layout <file>",
            "Validate slide layout for overflow, collisions, and density.",
            &[],
            vec![],
            direct("read-only command; layout QA is not a mutation op"),
            None,
        ),
    ]
}

fn mutation_output_flags() -> Vec<super::FlagSpec> {
    vec![
        flag("--out", "out", "string", "output file path"),
        flag("--backup", "backup", "string", "backup path for --in-place"),
        flag(
            "--dry-run",
            "dryRun",
            "bool",
            "plan and validate without writing",
        ),
        flag(
            "--in-place",
            "inPlace",
            "bool",
            "write back to the input file",
        ),
        flag(
            "--no-validate",
            "noValidate",
            "bool",
            "skip strict validation of the mutated package",
        ),
    ]
}

fn with_output_flags(mut flags: Vec<super::FlagSpec>) -> Vec<super::FlagSpec> {
    flags.extend(mutation_output_flags());
    flags
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;
    use crate::command_manifest::{CommandId, ExecutionSupport};

    #[test]
    fn owner_contract() {
        let specs = command_specs();
        assert_eq!(specs.len(), COMMAND_COUNT);
        assert_eq!(
            specs
                .iter()
                .filter_map(|spec| match &spec.execution {
                    ExecutionSupport::ServeInspect { .. } => Some(spec.id),
                    _ => None,
                })
                .collect::<BTreeSet<_>>(),
            BTreeSet::from([
                CommandId::Pptx(PptxCommandId::SlidesList),
                CommandId::Pptx(PptxCommandId::SlidesSelectors),
                CommandId::Pptx(PptxCommandId::SlidesShow),
            ])
        );
        assert_eq!(
            specs
                .iter()
                .filter(|spec| matches!(&spec.execution, ExecutionSupport::DirectOnly { .. }))
                .count(),
            8
        );
    }
}
