use serde_json::Value;

use super::super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml xlsx pivots list",
            "list <file>",
            "List workbook PivotTables, cache sources, selectors, and generated readback commands.",
            &["pivot", "sheet", "range", "table"],
            false,
            Some("read-only command; call via inspect/list in direct CLI"),
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
        ),
        capability_command(
            "ooxml xlsx pivots show",
            "show <file>",
            "Show one PivotTable with cache fields, source range, axis fields, and selectors.",
            &["pivot", "sheet", "range", "table"],
            false,
            Some("read-only command; call via inspect/list in direct CLI"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--pivot",
                    "pivot",
                    "string",
                    "pivot selector from pivots list",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx pivots create",
            "create <file>",
            "Author a new PivotTable from a source table or worksheet range.",
            &["pivot", "sheet", "range", "table"],
            false,
            Some("direct CLI mutation; serve/MCP operation dispatch is not wired for this command"),
            vec![
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "source sheet selector for --range or table disambiguation",
                ),
                flag(
                    "--range",
                    "range",
                    "string",
                    "source A1 range with a header row",
                ),
                flag("--table", "table", "string", "source table selector"),
                flag(
                    "--target-sheet",
                    "targetSheet",
                    "string",
                    "sheet to place the pivot on; defaults to the source sheet",
                ),
                flag(
                    "--anchor",
                    "anchor",
                    "string",
                    "top-left pivot anchor cell; defaults right of the source range",
                ),
                flag("--name", "name", "string", "pivot table name"),
                flag(
                    "--rows",
                    "rows",
                    "string",
                    "comma-separated row field names",
                ),
                flag(
                    "--cols",
                    "cols",
                    "string",
                    "comma-separated column field names",
                ),
                flag(
                    "--filters",
                    "filters",
                    "string",
                    "comma-separated filter/page field names",
                ),
                flag(
                    "--values",
                    "values",
                    "string",
                    "comma-separated value field specs such as Amount or Amount:sum",
                ),
                flag(
                    "--expect-source-range",
                    "expectSourceRange",
                    "string",
                    "guard: require the resolved source range to match",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum source cells to read",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx workbook metadata inspect",
            "inspect <file>",
            "Inspect workbook core/app properties and calc settings.",
            &["package"],
            false,
            Some("it does not accept the mutation output flags injected by the op engine"),
            vec![],
        ),
        capability_command(
            "ooxml xlsx workbook metadata update",
            "update <file>",
            "Update workbook metadata fields and calc settings.",
            &["package"],
            true,
            None,
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--calc-mode",
                    "calcMode",
                    "string",
                    "set workbook calcMode (auto|manual|autoNoTable)",
                ),
                flag(
                    "--category",
                    "category",
                    "string",
                    "set core property category",
                ),
                flag("--company", "company", "string", "set app property Company"),
                flag(
                    "--creator",
                    "creator",
                    "string",
                    "set core property dc:creator",
                ),
                flag(
                    "--description",
                    "description",
                    "string",
                    "set core property dc:description",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--expect-category",
                    "expectCategory",
                    "string",
                    "guard: require current category to equal this value",
                ),
                flag(
                    "--expect-company",
                    "expectCompany",
                    "string",
                    "guard: require current company to equal this value",
                ),
                flag(
                    "--expect-creator",
                    "expectCreator",
                    "string",
                    "guard: require current creator to equal this value",
                ),
                flag(
                    "--expect-description",
                    "expectDescription",
                    "string",
                    "guard: require current description to equal this value",
                ),
                flag(
                    "--expect-keywords",
                    "expectKeywords",
                    "string",
                    "guard: require current keywords to equal this value",
                ),
                flag(
                    "--expect-last-modified-by",
                    "expectLastModifiedBy",
                    "string",
                    "guard: require current lastModifiedBy to equal this value",
                ),
                flag(
                    "--expect-manager",
                    "expectManager",
                    "string",
                    "guard: require current manager to equal this value",
                ),
                flag(
                    "--expect-subject",
                    "expectSubject",
                    "string",
                    "guard: require current subject to equal this value",
                ),
                flag(
                    "--expect-title",
                    "expectTitle",
                    "string",
                    "guard: require current title to equal this value",
                ),
                flag(
                    "--full-calc-on-load",
                    "fullCalcOnLoad",
                    "bool",
                    "set fullCalcOnLoad and forceFullCalc so Excel recalculates on open",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag(
                    "--keywords",
                    "keywords",
                    "string",
                    "set core property keywords",
                ),
                flag(
                    "--last-modified-by",
                    "lastModifiedBy",
                    "string",
                    "set core property lastModifiedBy",
                ),
                flag("--manager", "manager", "string", "set app property Manager"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--subject",
                    "subject",
                    "string",
                    "set core property dc:subject",
                ),
                flag("--title", "title", "string", "set core property dc:title"),
            ],
        ),
    ]
}
