use serde_json::Value;

use super::super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml xlsx ranges export",
            "export <file>",
            "Export decoded worksheet cells from a range.",
            &["sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag(
                    "--include-types",
                    "includeTypes",
                    "bool",
                    "include cell types",
                ),
                flag(
                    "--include-formulas",
                    "includeFormulas",
                    "bool",
                    "include formulas",
                ),
                flag(
                    "--include-formats",
                    "includeFormats",
                    "bool",
                    "include style and number-format matrices",
                ),
                flag(
                    "--data-out",
                    "dataOut",
                    "string",
                    "write JSON matrix data to this file",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to export",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges set",
            "set <file>",
            "Set a worksheet range from a rectangular JSON, CSV, or TSV matrix.",
            &["sheet", "range", "cell"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--anchor", "anchor", "string", "top-left A1 cell"),
                flag("--values", "values", "string", "inline matrix data"),
                flag(
                    "--values-file",
                    "valuesFile",
                    "string",
                    "path to matrix data, or - for stdin",
                ),
                flag(
                    "--data-format",
                    "dataFormat",
                    "string",
                    "matrix data format: json, csv, or tsv",
                ),
                flag(
                    "--null-policy",
                    "nullPolicy",
                    "string",
                    "null handling: skip, clear, or empty-string",
                ),
                flag(
                    "--ragged",
                    "ragged",
                    "string",
                    "ragged handling: reject or fill-empty",
                ),
                flag("--max-cells", "maxCells", "number", "maximum cells to set"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--overwrite-formulas",
                    "overwriteFormulas",
                    "bool",
                    "allow replacing existing formula cells",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges set-format",
            "set-format <file>",
            "Apply a practical number format to a worksheet range.",
            &["sheet", "range", "style"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag(
                    "--preset",
                    "preset",
                    "string",
                    "format preset: integer, number, currency, percent, date, datetime, text, or general",
                ),
                flag(
                    "--format-code",
                    "formatCode",
                    "string",
                    "custom SpreadsheetML number format code",
                ),
                flag(
                    "--decimals",
                    "decimals",
                    "number",
                    "decimal places for number, currency, and percent presets",
                ),
                flag(
                    "--currency-symbol",
                    "currencySymbol",
                    "string",
                    "currency literal for the currency preset",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to format",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges set-style",
            "set-style <file>",
            "Apply font, fill, border, and alignment styling to a worksheet range.",
            &["sheet", "range", "style"],
            false,
            Some("direct CLI mutation; serve/MCP operation dispatch is not wired for this command"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--font-name", "fontName", "string", "font family name"),
                flag("--font-size", "fontSize", "number", "font size in points"),
                flag("--font-bold", "fontBold", "bool", "toggle bold text"),
                flag("--font-italic", "fontItalic", "bool", "toggle italic text"),
                flag(
                    "--font-underline",
                    "fontUnderline",
                    "bool",
                    "toggle underline text",
                ),
                flag(
                    "--font-color",
                    "fontColor",
                    "string",
                    "font color as hex RGB",
                ),
                flag(
                    "--fill-color",
                    "fillColor",
                    "string",
                    "cell fill color as hex RGB",
                ),
                flag(
                    "--border-style",
                    "borderStyle",
                    "string",
                    "border line style",
                ),
                flag(
                    "--border-color",
                    "borderColor",
                    "string",
                    "border color as hex RGB",
                ),
                flag("--border-top", "borderTop", "bool", "apply top border"),
                flag(
                    "--border-bottom",
                    "borderBottom",
                    "bool",
                    "apply bottom border",
                ),
                flag("--border-left", "borderLeft", "bool", "apply left border"),
                flag(
                    "--border-right",
                    "borderRight",
                    "bool",
                    "apply right border",
                ),
                flag(
                    "--alignment-horizontal",
                    "alignmentHorizontal",
                    "string",
                    "horizontal alignment",
                ),
                flag(
                    "--alignment-vertical",
                    "alignmentVertical",
                    "string",
                    "vertical alignment",
                ),
                flag(
                    "--alignment-wrap-text",
                    "alignmentWrapText",
                    "bool",
                    "toggle text wrapping",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to style",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cells extract",
            "extract <file>",
            "Extract decoded worksheet cells with stable cell selectors.",
            &["sheet", "range", "cell"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--max-rows", "maxRows", "number", "maximum rows to emit"),
                flag("--max-cells", "maxCells", "number", "maximum cells to emit"),
                flag(
                    "--include-empty",
                    "includeEmpty",
                    "bool",
                    "include empty cells inside output bounds",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cells set",
            "set <file>",
            "Set a worksheet cell value.",
            &["sheet", "cell"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path"),
                flag("--cell", "cell", "string", "A1 cell reference"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag("--formula", "formula", "string", "cell formula"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag(
                    "--out",
                    "out",
                    "string",
                    "output file path for direct CLI use",
                ),
                flag("--ref", "ref", "string", "A1 cell reference alias"),
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--type", "type", "string", "value type"),
                flag("--value", "value", "string", "cell value"),
            ],
        ),
        capability_command(
            "ooxml xlsx cells clear",
            "clear <file>",
            "Clear values and formulas from a worksheet cell or range.",
            &["sheet", "range", "cell"],
            false,
            Some("direct CLI mutation; serve/MCP operation dispatch is not wired for this command"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--ref", "ref", "string", "A1 cell reference"),
                flag(
                    "--readback-max-cells",
                    "readbackMaxCells",
                    "number",
                    "maximum cells in emitted destination readback",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cells set-batch",
            "set-batch <file>",
            "Set multiple worksheet cells from inline JSON or a JSON file.",
            &["sheet", "range", "cell"],
            false,
            Some("direct CLI mutation; serve/MCP operation dispatch is not wired for this command"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--cells", "cells", "string", "inline JSON cell assignments"),
                flag(
                    "--cells-file",
                    "cellsFile",
                    "string",
                    "path to JSON cell assignments, or - for stdin",
                ),
                flag(
                    "--details",
                    "details",
                    "bool",
                    "emit per-cell mutation details",
                ),
                flag(
                    "--readback-max-cells",
                    "readbackMaxCells",
                    "number",
                    "maximum cells in emitted destination readback",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
    ]
}
