use serde_json::Value;

use super::super::{capability_command, flag};

pub(super) fn commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml xlsx sheets list",
            "list <file>",
            "List workbook sheets and selectors.",
            &["sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![],
        ),
        capability_command(
            "ooxml xlsx sheets show",
            "show <file>",
            "Show worksheet metadata, used ranges, and generated readback commands.",
            &["sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
        ),
        capability_command(
            "ooxml xlsx sheets add",
            "add <file> --name <name>",
            "Add an empty worksheet and wire workbook.xml, workbook relationships, and content types.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--name", "name", "string", "new worksheet name"),
                flag(
                    "--after",
                    "after",
                    "string",
                    "insert after sheet selector; omitted appends",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx sheets rename",
            "rename <file> --sheet <sheet> --name <name>",
            "Rename a workbook worksheet by sheet selector.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--name", "name", "string", "new worksheet name"),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx sheets move",
            "move <file> --sheet <sheet> (--to <n>|--before <sheet>|--after <sheet>)",
            "Move a workbook sheet in tab order while preserving its part, sheetId, and relationship ID.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--to", "to", "int", "final 1-based workbook sheet position"),
                flag(
                    "--before",
                    "before",
                    "string",
                    "move before this sheet selector",
                ),
                flag(
                    "--after",
                    "after",
                    "string",
                    "move after this sheet selector",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx sheets delete",
            "delete <file> --sheet <sheet>",
            "Delete one worksheet and remove its workbook relationship, worksheet part, worksheet relationships, and calcChain.",
            &["sheet"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx colwidths show",
            "show <file> --sheet <sheet> --range <columns>",
            "Show resolved worksheet column widths for a column range.",
            &["sheet", "range"],
            false,
            Some("read-only command; direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "column span such as B or B:D"),
            ],
        ),
        capability_command(
            "ooxml xlsx colwidths set",
            "set <file> --sheet <sheet> --range <columns> --width <width>",
            "Set a uniform worksheet column width for a column range.",
            &["sheet", "range"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "column span such as B or B:D"),
                flag(
                    "--width",
                    "width",
                    "number",
                    "column width in character units (0-255)",
                ),
                flag(
                    "--expect-width",
                    "expectWidth",
                    "number",
                    "guard: require the first column to currently have this width",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx rowheights show",
            "show <file> --sheet <sheet> --range <rows>",
            "Show resolved worksheet row heights for a row range.",
            &["sheet", "range"],
            false,
            Some("read-only command; direct CLI parity only in the current Rust slice"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "row span such as 2 or 2:5"),
            ],
        ),
        capability_command(
            "ooxml xlsx rowheights set",
            "set <file> --sheet <sheet> --range <rows> --height <height>",
            "Set a uniform worksheet row height for a row range.",
            &["sheet", "range"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "row span such as 2 or 2:5"),
                flag(
                    "--height",
                    "height",
                    "number",
                    "row height in points (0-409)",
                ),
                flag(
                    "--expect-height",
                    "expectHeight",
                    "number",
                    "guard: require the first row to currently have this height",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx rows insert",
            "insert <file> --sheet <sheet> --at <row>",
            "Insert blank worksheet rows before a 1-based row position.",
            &["sheet", "range"],
            false,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--at",
                    "at",
                    "int",
                    "1-based row position for the inserted rows",
                ),
                flag("--count", "count", "int", "number of rows to insert"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx rows delete",
            "delete <file> --sheet <sheet> --row <row>",
            "Delete a band of worksheet rows.",
            &["sheet", "range"],
            false,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--row", "row", "int", "1-based first row to delete"),
                flag("--count", "count", "int", "number of rows to delete"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cols insert",
            "insert <file> --sheet <sheet> --at <column>",
            "Insert blank worksheet columns before a column position.",
            &["sheet", "range"],
            false,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag(
                    "--at",
                    "at",
                    "string",
                    "column position for the inserted columns",
                ),
                flag("--count", "count", "int", "number of columns to insert"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cols delete",
            "delete <file> --sheet <sheet> --col <column>",
            "Delete a band of worksheet columns.",
            &["sheet", "range"],
            false,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--col", "col", "string", "first column to delete"),
                flag("--count", "count", "int", "number of columns to delete"),
                flag("--out", "out", "string", "output file path"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
    ]
}
