use super::{ExecutionSupport, XlsxCommandId, flag, spec};

pub(super) const COMMAND_COUNT: usize = 12;
pub(super) const LEGACY_START: usize = 180;

pub(super) fn command_specs() -> Vec<super::CommandSpec> {
    vec![
        spec(
            XlsxCommandId::ChartsList,
            &["xlsx", "charts", "list"],
            "list <file>",
            "List workbook charts, stable selectors, source formulas, anchors, and chart style readback.",
            &["chart"],
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
            ExecutionSupport::DirectOnly {
                reason: Some(
                    "read-only command; generated show commands can read back individual charts",
                ),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsShow,
            &["xlsx", "charts", "show"],
            "show <file> [--chart <selector>]",
            "Show one workbook chart, including chart type, source formulas, cached previews, anchors, part metadata, and practical style.",
            &["chart"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("read-only command; generated by xlsx charts list"),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsCreate,
            &["xlsx", "charts", "create"],
            "create <file> --type <bar|line|area|pie|scatter> --range <A1:C5>",
            "Create an embedded worksheet chart from a range or table source.",
            &["chart"],
            vec![
                flag(
                    "--type",
                    "type",
                    "string",
                    "chart type: bar, line, area, pie, or scatter",
                ),
                flag("--sheet", "sheet", "string", "target/source sheet selector"),
                flag("--range", "range", "string", "source range"),
                flag("--table", "table", "string", "source table selector"),
                flag("--title", "title", "string", "chart title"),
                flag("--anchor", "anchor", "string", "chart anchor top-left cell"),
                flag(
                    "--expect-source-range",
                    "expectSourceRange",
                    "string",
                    "guard: resolved source range",
                ),
                flag("--max-cells", "maxCells", "int", "maximum source cells"),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            Some(serde_json::json!({
                "modeFlag": "--type",
                "modes": [
                    {
                        "required": [
                            "--type"
                        ],
                        "value": "bar"
                    },
                    {
                        "required": [
                            "--type"
                        ],
                        "value": "line"
                    },
                    {
                        "required": [
                            "--type"
                        ],
                        "value": "area"
                    },
                    {
                        "notes": [
                            "Pie charts use only the first series when the source has multiple series."
                        ],
                        "required": [
                            "--type"
                        ],
                        "value": "pie"
                    },
                    {
                        "required": [
                            "--type"
                        ],
                        "value": "scatter"
                    }
                ],
                "outputRequiredOneOf": [
                    "--out",
                    "--in-place",
                    "--dry-run"
                ],
                "rules": [
                    "--type is required and must be bar, line, area, pie, or scatter.",
                    "Specify exactly one source: --range or --table.",
                    "--sheet is required when using --range.",
                    "--expect-source-range guards the resolved source range after table/range resolution."
                ],
                "sourceModes": [
                    {
                        "conflictsWith": [
                            "--table"
                        ],
                        "name": "range",
                        "required": [
                            "--sheet",
                            "--range"
                        ]
                    },
                    {
                        "conflictsWith": [
                            "--range"
                        ],
                        "name": "table",
                        "optional": [
                            "--sheet"
                        ],
                        "required": [
                            "--table"
                        ]
                    }
                ]
            })),
        ),
        spec(
            XlsxCommandId::ChartsUpdateSource,
            &["xlsx", "charts", "update-source"],
            "update-source <file> --chart <selector> --series <n> --role <role>",
            "Retarget one existing worksheet chart series source and rewrite, clear, or keep the stored cache.",
            &["chart"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag("--series", "series", "int", "zero-based series index"),
                flag(
                    "--role",
                    "role",
                    "string",
                    "series role: name, categories, values, xValues, yValues, or bubbleSize",
                ),
                flag(
                    "--source-sheet",
                    "sourceSheet",
                    "string",
                    "source sheet name",
                ),
                flag("--source-range", "sourceRange", "string", "source range"),
                flag(
                    "--formula",
                    "formula",
                    "string",
                    "complete chart source formula",
                ),
                flag(
                    "--cache",
                    "cache",
                    "string",
                    "cache handling: auto, clear, or keep",
                ),
                flag(
                    "--expect-source-range",
                    "expectSourceRange",
                    "string",
                    "guard: current source range",
                ),
                flag(
                    "--expect-formula",
                    "expectFormula",
                    "string",
                    "guard: current source formula",
                ),
                flag("--max-cells", "maxCells", "int", "maximum source cells"),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsSetTitle,
            &["xlsx", "charts", "set-title"],
            "set-title <file> --title <text>",
            "Set a worksheet chart title and optional title font fields.",
            &["chart", "style"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag("--title", "title", "string", "new chart title text"),
                flag(
                    "--expect-title",
                    "expectTitle",
                    "string",
                    "guard: current title text",
                ),
                flag("--font-family", "fontFamily", "string", "title font family"),
                flag(
                    "--font-size",
                    "fontSize",
                    "float",
                    "title font size in points",
                ),
                flag("--font-color", "fontColor", "string", "title font color"),
                flag("--font-bold", "fontBold", "bool", "title font bold"),
                flag("--font-italic", "fontItalic", "bool", "title font italic"),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsSetLegend,
            &["xlsx", "charts", "set-legend"],
            "set-legend <file> --position <position>",
            "Set or remove a worksheet chart legend position and overlay flag.",
            &["chart", "style"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag(
                    "--position",
                    "position",
                    "string",
                    "right, left, top, bottom, or none",
                ),
                flag("--overlay", "overlay", "bool", "legend overlays plot area"),
                flag(
                    "--expect-position",
                    "expectPosition",
                    "string",
                    "guard: current legend position",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsSetChartAreaFill,
            &["xlsx", "charts", "set-chart-area-fill"],
            "set-chart-area-fill <file> --fill-color <#RRGGBB|none>",
            "Set or clear the worksheet chart-area fill.",
            &["chart", "style"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag(
                    "--fill-color",
                    "fillColor",
                    "string",
                    "fill color as #RRGGBB, or none",
                ),
                flag(
                    "--expect-fill",
                    "expectFill",
                    "string",
                    "guard: current fill color, scheme:<name>, or none",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsSetPlotAreaFill,
            &["xlsx", "charts", "set-plot-area-fill"],
            "set-plot-area-fill <file> --fill-color <#RRGGBB|none>",
            "Set or clear the worksheet plot-area fill.",
            &["chart", "style"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag(
                    "--fill-color",
                    "fillColor",
                    "string",
                    "fill color as #RRGGBB, or none",
                ),
                flag(
                    "--expect-fill",
                    "expectFill",
                    "string",
                    "guard: current fill color, scheme:<name>, or none",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsSetSeriesStyle,
            &["xlsx", "charts", "set-series-style"],
            "set-series-style <file> --series <n>",
            "Set fill, line, and marker style fields on a worksheet chart series.",
            &["chart", "style"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag("--series", "series", "int", "1-based series number"),
                flag("--fill-color", "fillColor", "string", "series fill color"),
                flag("--line-color", "lineColor", "string", "series line color"),
                flag(
                    "--line-width-pt",
                    "lineWidthPt",
                    "float",
                    "series line width in points",
                ),
                flag(
                    "--marker-symbol",
                    "markerSymbol",
                    "string",
                    "circle, square, diamond, triangle, or none",
                ),
                flag("--marker-size", "markerSize", "int", "marker size 2..72"),
                flag(
                    "--expect-series-count",
                    "expectSeriesCount",
                    "int",
                    "guard: current series count",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::ServeMutation { reason: None },
            None,
        ),
        spec(
            XlsxCommandId::ChartsConvertType,
            &["xlsx", "charts", "convert-type"],
            "convert-type <file> --to <type>",
            "Convert an existing worksheet chart to bar, column, line, area, pie, or scatter while preserving series source references and caches where possible.",
            &["chart"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag(
                    "--to",
                    "to",
                    "string",
                    "target type: bar, column, line, area, pie, or scatter",
                ),
                flag(
                    "--expect-type",
                    "expectType",
                    "string",
                    "guard: current chart type",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsCopyStyle,
            &["xlsx", "charts", "copy-style"],
            "copy-style <file> --from <template.xlsx>",
            "Copy practical chart style fields from a template worksheet chart without copying chart content or source data.",
            &["chart", "style"],
            vec![
                flag("--sheet", "sheet", "string", "target sheet selector"),
                flag("--chart", "chart", "string", "target chart selector"),
                flag(
                    "--to-chart",
                    "toChart",
                    "string",
                    "target chart selector alias",
                ),
                flag("--from", "from", "string", "template XLSX file"),
                flag(
                    "--from-chart",
                    "fromChart",
                    "string",
                    "template chart selector",
                ),
                flag(
                    "--expect-series-count",
                    "expectSeriesCount",
                    "int",
                    "guard: target series count",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            None,
        ),
        spec(
            XlsxCommandId::ChartsSetAxis,
            &["xlsx", "charts", "set-axis"],
            "set-axis <file> --axis <category|value>",
            "Set practical category/value axis properties such as title, visibility, scale, number format, gridlines, and label/title fonts.",
            &["chart", "style"],
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--chart", "chart", "string", "chart selector"),
                flag("--axis", "axis", "string", "category or value"),
                flag(
                    "--title",
                    "title",
                    "string",
                    "axis title text; empty clears",
                ),
                flag(
                    "--expect-axis-title",
                    "expectAxisTitle",
                    "string",
                    "guard: current axis title",
                ),
                flag("--hidden", "hidden", "bool", "hide or show the axis"),
                flag("--min", "min", "float", "axis scale minimum"),
                flag("--max", "max", "float", "axis scale maximum"),
                flag(
                    "--major-unit",
                    "majorUnit",
                    "float",
                    "value-axis major unit",
                ),
                flag(
                    "--number-format",
                    "numberFormat",
                    "string",
                    "axis number format code",
                ),
                flag(
                    "--major-gridlines",
                    "majorGridlines",
                    "bool",
                    "show major gridlines",
                ),
                flag(
                    "--minor-gridlines",
                    "minorGridlines",
                    "bool",
                    "show minor gridlines",
                ),
                flag(
                    "--tick-label-font-family",
                    "tickLabelFontFamily",
                    "string",
                    "tick label font family",
                ),
                flag(
                    "--tick-label-font-size",
                    "tickLabelFontSize",
                    "float",
                    "tick label font size in points",
                ),
                flag(
                    "--tick-label-font-color",
                    "tickLabelFontColor",
                    "string",
                    "tick label font color",
                ),
                flag(
                    "--tick-label-font-bold",
                    "tickLabelFontBold",
                    "bool",
                    "tick label bold",
                ),
                flag(
                    "--tick-label-font-italic",
                    "tickLabelFontItalic",
                    "bool",
                    "tick label italic",
                ),
                flag(
                    "--title-font-family",
                    "titleFontFamily",
                    "string",
                    "axis title font family",
                ),
                flag(
                    "--title-font-size",
                    "titleFontSize",
                    "float",
                    "axis title font size in points",
                ),
                flag(
                    "--title-font-color",
                    "titleFontColor",
                    "string",
                    "axis title font color",
                ),
                flag(
                    "--title-font-bold",
                    "titleFontBold",
                    "bool",
                    "axis title bold",
                ),
                flag(
                    "--title-font-italic",
                    "titleFontItalic",
                    "bool",
                    "axis title italic",
                ),
                flag(
                    "--expect-axis-count",
                    "expectAxisCount",
                    "int",
                    "guard: chart axis count",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "validate without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some("direct CLI mutation; serve/MCP op support is not wired yet"),
            },
            None,
        ),
    ]
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;
    use crate::command_manifest::{assert_segment_matches_legacy, capability_value};

    #[test]
    fn charts_segment_matches_fixed_legacy_slice() {
        let specs = command_specs();
        let legacy = crate::capabilities::capability_commands();
        assert_eq!(specs.len(), COMMAND_COUNT);
        assert_segment_matches_legacy(&specs, &legacy[LEGACY_START..LEGACY_START + COMMAND_COUNT]);
    }

    #[test]
    fn charts_ids_paths_builds_and_execution_inventory_are_stable() {
        let first = command_specs();
        let second = command_specs();
        assert_eq!(
            first
                .iter()
                .map(|spec| spec.id)
                .collect::<BTreeSet<_>>()
                .len(),
            COMMAND_COUNT
        );
        assert_eq!(
            first
                .iter()
                .map(|spec| spec.path)
                .collect::<BTreeSet<_>>()
                .len(),
            COMMAND_COUNT
        );
        assert_eq!(
            first.iter().map(capability_value).collect::<Vec<_>>(),
            second.iter().map(capability_value).collect::<Vec<_>>()
        );
        let inventory = first.iter().fold(
            (0, 0, 0, 0),
            |(groups, direct, inspect, mutation), spec| match &spec.execution {
                ExecutionSupport::GroupOnly { .. } => (groups + 1, direct, inspect, mutation),
                ExecutionSupport::DirectOnly { .. } => (groups, direct + 1, inspect, mutation),
                ExecutionSupport::ServeInspect { .. } => (groups, direct, inspect + 1, mutation),
                ExecutionSupport::ServeMutation { .. } => (groups, direct, inspect, mutation + 1),
            },
        );
        assert_eq!(inventory, (0, 11, 0, 1));
    }
}
