use super::{ExecutionSupport, XlsxCommandId, flag, spec};

pub(super) const COMMAND_COUNT: usize = 6;
pub(super) const LEGACY_START: usize = 219;

pub(super) fn command_specs() -> Vec<super::CommandSpec> {
    vec![
        spec(
            XlsxCommandId::NamesList,
            &["xlsx", "names", "list"],
            "list <file> [--scope-sheet <sheet>]",
            "List workbook and sheet-local defined names with selectors.",
            &["name", "sheet", "range"],
            vec![flag(
                "--scope-sheet",
                "scopeSheet",
                "string",
                "only list sheet-local names for this sheet selector",
            )],
            ExecutionSupport::ServeInspect {
                reason: Some("read-only command; call via inspect in serve/MCP"),
            },
            None,
        ),
        spec(
            XlsxCommandId::NamesShow,
            &["xlsx", "names", "show"],
            "show <file> --name <selector> [--scope-sheet <sheet>]",
            "Show one workbook defined name by name, selector, or handle.",
            &["name", "sheet", "range"],
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name, selector, or workbook-scoped handle",
                ),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
            ],
            ExecutionSupport::ServeInspect {
                reason: Some("read-only command; generated by xlsx names list"),
            },
            None,
        ),
        spec(
            XlsxCommandId::NamesAdd,
            &["xlsx", "names", "add"],
            "add <file> --name <name> (--ref <ref>|--sheet <sheet> --range <range>)",
            "Add a workbook or sheet-local defined name.",
            &["name", "sheet", "range"],
            vec![
                flag("--name", "name", "string", "defined name to add"),
                flag(
                    "--ref",
                    "ref",
                    "string",
                    "exact defined-name ref/formula text",
                ),
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet selector used with --range",
                ),
                flag("--range", "range", "string", "A1 range used with --sheet"),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "create a sheet-local name scoped to this sheet selector",
                ),
                flag("--hidden", "hidden", "bool", "mark the defined name hidden"),
                flag(
                    "--comment",
                    "comment",
                    "string",
                    "optional defined-name comment",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::ServeMutation { reason: None },
            None,
        ),
        spec(
            XlsxCommandId::NamesUpdate,
            &["xlsx", "names", "update"],
            "update <file> --name <selector> (--ref <ref>|--sheet <sheet> --range <range>)",
            "Update a workbook defined name reference.",
            &["name", "sheet", "range"],
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name or published selector",
                ),
                flag(
                    "--ref",
                    "ref",
                    "string",
                    "exact replacement ref/formula text",
                ),
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet selector used with --range",
                ),
                flag(
                    "--range",
                    "range",
                    "string",
                    "replacement A1 range used with --sheet",
                ),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
                flag(
                    "--expect-ref",
                    "expectRef",
                    "string",
                    "guard: expected current ref/formula text",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::ServeMutation { reason: None },
            None,
        ),
        spec(
            XlsxCommandId::NamesRename,
            &["xlsx", "names", "rename"],
            "rename <file> --name <selector> --new-name <name>",
            "Rename a workbook defined name while preserving its ref and scope.",
            &["name", "sheet", "range"],
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name or published selector",
                ),
                flag("--new-name", "newName", "string", "new defined name"),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
                flag(
                    "--expect-ref",
                    "expectRef",
                    "string",
                    "guard: expected current ref/formula text",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::ServeMutation { reason: None },
            None,
        ),
        spec(
            XlsxCommandId::NamesDelete,
            &["xlsx", "names", "delete"],
            "delete <file> --name <selector>",
            "Delete a workbook defined name.",
            &["name", "sheet", "range"],
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name or published selector",
                ),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
                flag(
                    "--expect-ref",
                    "expectRef",
                    "string",
                    "guard: expected current ref/formula text",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
            ],
            ExecutionSupport::ServeMutation { reason: None },
            None,
        ),
    ]
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;
    use crate::command_manifest::{
        assert_segment_matches_frozen_contract, capability_value, frozen_contract_commands,
    };

    #[test]
    fn names_segment_matches_frozen_contract_slice() {
        let specs = command_specs();
        let frozen = frozen_contract_commands();
        assert_eq!(specs.len(), COMMAND_COUNT);
        assert_segment_matches_frozen_contract(
            &specs,
            &frozen[LEGACY_START..LEGACY_START + COMMAND_COUNT],
        );
    }

    #[test]
    fn names_ids_paths_builds_and_execution_inventory_are_stable() {
        let first = command_specs();
        let second = command_specs();
        assert_eq!(
            first
                .iter()
                .map(|spec| spec.id)
                .collect::<BTreeSet<_>>()
                .len(),
            COMMAND_COUNT
        );
        assert_eq!(
            first
                .iter()
                .map(|spec| spec.path)
                .collect::<BTreeSet<_>>()
                .len(),
            COMMAND_COUNT
        );
        assert_eq!(
            first.iter().map(capability_value).collect::<Vec<_>>(),
            second.iter().map(capability_value).collect::<Vec<_>>()
        );
        let inventory = first.iter().fold(
            (0, 0, 0, 0),
            |(groups, direct, inspect, mutation), spec| match &spec.execution {
                ExecutionSupport::GroupOnly { .. } => (groups + 1, direct, inspect, mutation),
                ExecutionSupport::DirectOnly { .. } => (groups, direct + 1, inspect, mutation),
                ExecutionSupport::ServeInspect { .. } => (groups, direct, inspect + 1, mutation),
                ExecutionSupport::ServeMutation { .. } => (groups, direct, inspect, mutation + 1),
            },
        );
        assert_eq!(inventory, (0, 0, 2, 4));
    }
}
