use super::{ExecutionSupport, XlsxCommandId, flag, spec};

pub(super) const COMMAND_COUNT: usize = 7;
pub(super) const LEGACY_START: usize = 225;

pub(super) fn command_specs() -> Vec<super::CommandSpec> {
    vec![
        spec(
            XlsxCommandId::TablesList,
            &["xlsx", "tables", "list"],
            "list <file>",
            "List workbook tables",
            &["table", "range", "sheet"],
            vec![flag(
                "--sheet",
                "sheet",
                "string",
                "sheet number (1-based) or exact sheet name",
            )],
            ExecutionSupport::ServeInspect {
                reason: Some("read-only command; call via inspect in serve/MCP"),
            },
            None,
        ),
        spec(
            XlsxCommandId::TablesShow,
            &["xlsx", "tables", "show"],
            "show <file>",
            "Show table metadata",
            &["table", "range", "sheet"],
            vec![
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet number (1-based) or exact sheet name",
                ),
                flag(
                    "--table",
                    "table",
                    "string",
                    "table number, name, or displayName",
                ),
            ],
            ExecutionSupport::ServeInspect {
                reason: Some("read-only command; call via inspect in serve/MCP"),
            },
            None,
        ),
        spec(
            XlsxCommandId::TablesExport,
            &["xlsx", "tables", "export"],
            "export <file>",
            "Export a table as a rectangular JSON matrix.",
            &["table", "range", "sheet"],
            vec![
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet number (1-based) or exact sheet name",
                ),
                flag(
                    "--table",
                    "table",
                    "string",
                    "table number, name, or displayName",
                ),
                flag(
                    "--include-types",
                    "includeTypes",
                    "bool",
                    "include cell types",
                ),
                flag(
                    "--include-formulas",
                    "includeFormulas",
                    "bool",
                    "include formulas",
                ),
                flag(
                    "--data-out",
                    "dataOut",
                    "string",
                    "write JSON matrix data to this file",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to export",
                ),
            ],
            ExecutionSupport::ServeInspect {
                reason: Some("read-only command; generated by xlsx tables list/show"),
            },
            None,
        ),
        spec(
            XlsxCommandId::TablesCreate,
            &["xlsx", "tables", "create"],
            "create <file>",
            "Create a workbook table over an existing worksheet range.",
            &["table", "range", "sheet"],
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--range",
                    "range",
                    "string",
                    "table range including header row",
                ),
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet number (1-based), sheetId, handle, or exact sheet name",
                ),
                flag("--style", "style", "string", "table style name, or none"),
                flag("--table", "table", "string", "new table display name"),
            ],
            ExecutionSupport::ServeMutation { reason: None },
            None,
        ),
        spec(
            XlsxCommandId::TablesAppendRows,
            &["xlsx", "tables", "append-rows"],
            "append-rows <file>",
            "Append row matrices to an existing table.",
            &["table", "range", "sheet"],
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--data-format",
                    "dataFormat",
                    "string",
                    "matrix data format: json, csv, or tsv",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to append",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
                flag(
                    "--null-policy",
                    "nullPolicy",
                    "string",
                    "null handling: skip, clear, or empty-string",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--overwrite-formulas",
                    "overwriteFormulas",
                    "bool",
                    "allow writing formulas over existing formula cells",
                ),
                flag(
                    "--ragged",
                    "ragged",
                    "string",
                    "ragged row handling: reject or fill-empty",
                ),
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet number (1-based) or exact sheet name",
                ),
                flag(
                    "--table",
                    "table",
                    "string",
                    "table number, name, or displayName",
                ),
                flag(
                    "--values",
                    "values",
                    "string",
                    "inline JSON/CSV/TSV matrix data",
                ),
                flag(
                    "--values-file",
                    "valuesFile",
                    "string",
                    "path to JSON/CSV/TSV matrix data, or - for stdin",
                ),
            ],
            ExecutionSupport::ServeMutation { reason: None },
            None,
        ),
        spec(
            XlsxCommandId::TablesAppendRecords,
            &["xlsx", "tables", "append-records"],
            "append-records <file>",
            "Append JSON records to an existing table by column name.",
            &["table", "range", "sheet"],
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--expect-range",
                    "expectRange",
                    "string",
                    "expected current table range from xlsx tables show",
                ),
                flag(
                    "--ignore-extra-fields",
                    "ignoreExtraFields",
                    "bool",
                    "ignore record fields that do not match table columns",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to append",
                ),
                flag(
                    "--missing",
                    "missing",
                    "string",
                    "missing field handling: reject, skip, or empty-string",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
                flag(
                    "--null-policy",
                    "nullPolicy",
                    "string",
                    "null handling for explicit nulls and --missing skip",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--overwrite-formulas",
                    "overwriteFormulas",
                    "bool",
                    "allow writing formulas over existing formula cells",
                ),
                flag(
                    "--records",
                    "records",
                    "string",
                    "inline JSON record array or object with records",
                ),
                flag(
                    "--records-file",
                    "recordsFile",
                    "string",
                    "path to JSON records, or - for stdin",
                ),
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet number (1-based) or exact sheet name",
                ),
                flag(
                    "--table",
                    "table",
                    "string",
                    "table number, name, or displayName",
                ),
            ],
            ExecutionSupport::ServeMutation { reason: None },
            None,
        ),
        spec(
            XlsxCommandId::TablesSetColumnFormat,
            &["xlsx", "tables", "set-column-format"],
            "set-column-format <file>",
            "Apply a practical number format to a data column inside an existing table.",
            &["table", "range", "sheet", "style"],
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--column",
                    "column",
                    "string",
                    "table column name or 1-based column number",
                ),
                flag(
                    "--currency-symbol",
                    "currencySymbol",
                    "string",
                    "currency literal for the currency preset",
                ),
                flag(
                    "--decimals",
                    "decimals",
                    "number",
                    "decimal places for number, currency, and percent presets",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--expect-column",
                    "expectColumn",
                    "string",
                    "guard: require the resolved column name to match",
                ),
                flag(
                    "--format-code",
                    "formatCode",
                    "string",
                    "custom SpreadsheetML number format code",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "edit the workbook in place",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to format",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip strict validation",
                ),
                flag("--out", "out", "string", "write edited workbook"),
                flag(
                    "--preset",
                    "preset",
                    "string",
                    "format preset: integer, number, currency, percent, date, datetime, text, or general",
                ),
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet number (1-based) or exact sheet name",
                ),
                flag(
                    "--table",
                    "table",
                    "string",
                    "table number, name, or displayName",
                ),
            ],
            ExecutionSupport::DirectOnly {
                reason: Some(
                    "direct CLI mutation; serve/MCP operation dispatch is not wired for this command",
                ),
            },
            None,
        ),
    ]
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use super::*;
    use crate::command_manifest::{
        assert_segment_matches_frozen_contract, capability_value, frozen_contract_commands,
    };

    #[test]
    fn tables_segment_matches_frozen_contract_slice() {
        let specs = command_specs();
        let frozen = frozen_contract_commands();
        assert_eq!(specs.len(), COMMAND_COUNT);
        assert_segment_matches_frozen_contract(
            &specs,
            &frozen[LEGACY_START..LEGACY_START + COMMAND_COUNT],
        );
    }

    #[test]
    fn tables_ids_paths_builds_and_execution_inventory_are_stable() {
        let first = command_specs();
        let second = command_specs();
        assert_eq!(
            first
                .iter()
                .map(|spec| spec.id)
                .collect::<BTreeSet<_>>()
                .len(),
            COMMAND_COUNT
        );
        assert_eq!(
            first
                .iter()
                .map(|spec| spec.path)
                .collect::<BTreeSet<_>>()
                .len(),
            COMMAND_COUNT
        );
        assert_eq!(
            first.iter().map(capability_value).collect::<Vec<_>>(),
            second.iter().map(capability_value).collect::<Vec<_>>()
        );
        let inventory = first.iter().fold(
            (0, 0, 0, 0),
            |(groups, direct, inspect, mutation), spec| match &spec.execution {
                ExecutionSupport::GroupOnly { .. } => (groups + 1, direct, inspect, mutation),
                ExecutionSupport::DirectOnly { .. } => (groups, direct + 1, inspect, mutation),
                ExecutionSupport::ServeInspect { .. } => (groups, direct, inspect + 1, mutation),
                ExecutionSupport::ServeMutation { .. } => (groups, direct, inspect, mutation + 1),
            },
        );
        assert_eq!(inventory, (0, 1, 3, 3));
    }
}
