use serde_json::{Map, Value, json};

use crate::{
    CliResult, EXIT_FILE_NOT_FOUND, EXIT_INVALID_ARGS, EXIT_SUCCESS, EXIT_TARGET_NOT_FOUND,
    EXIT_UNEXPECTED, EXIT_UNSUPPORTED_TYPE, parse_string_flag,
};

pub(crate) fn capabilities(args: &[String]) -> CliResult<Value> {
    let filter = parse_string_flag(args, "--for")?.map(|value| value.to_ascii_lowercase());
    let mut commands = capability_commands();
    if let Some(filter) = filter.as_deref() {
        commands.retain(|command| capability_matches_filter(command, filter));
    }
    let mut notes = vec![
        "Rust port partial surface: only commands listed here are implemented in the Rust subject."
            .to_string(),
        "Use Go on codex/ooxml-go-reference as the oracle for the full command universe."
            .to_string(),
    ];
    if let Some(filter) = filter.as_deref() {
        notes.insert(
            0,
            format!("Filtered by Rust-supported command/object filter \"{filter}\"."),
        );
    }
    Ok(json!({
        "tool": "ooxml",
        "version": "0.0.1",
        "contractVersion": "ooxml-cli.agent-capabilities.v4",
        "packageTypes": ["pptx", "xlsx", "docx"],
        "outputModes": ["json via --json or --format json"],
        "globalFlags": [
            {"name": "--format", "argName": "format", "shorthand": "f", "type": "string", "default": "text", "description": "output format: \"text\" or \"json\""},
            {"name": "--json", "argName": "json", "type": "bool", "default": "false", "description": "emit JSON output"},
            {"name": "--strict", "argName": "strict", "type": "bool", "default": "false", "description": "enable strict validation mode"}
        ],
        "commands": commands,
        "objectKinds": ["package", "slide", "shape", "master", "layout", "placeholder", "sheet", "range", "cell", "table", "name", "block", "paragraph", "style", "comment", "field", "header", "footer", "image"],
        "objectKindsIndex": {
            "package": ["ooxml inspect", "ooxml validate", "ooxml verify", "ooxml docx text", "ooxml xlsx workbook metadata inspect", "ooxml xlsx workbook metadata update"],
            "slide": ["ooxml pptx slides list", "ooxml pptx slides selectors", "ooxml pptx slides show", "ooxml pptx shapes show", "ooxml pptx layouts list", "ooxml pptx layouts show", "ooxml pptx tables show", "ooxml pptx extract text", "ooxml pptx extract notes", "ooxml pptx notes show", "ooxml pptx comments list", "ooxml pptx replace text", "ooxml pptx render"],
            "shape": ["ooxml pptx slides list", "ooxml pptx slides selectors", "ooxml pptx slides show", "ooxml pptx shapes show", "ooxml pptx extract text", "ooxml pptx replace text"],
            "master": ["ooxml pptx masters list", "ooxml pptx masters show"],
            "layout": ["ooxml pptx layouts list", "ooxml pptx layouts show"],
            "placeholder": ["ooxml pptx masters show", "ooxml pptx layouts list", "ooxml pptx layouts show"],
            "sheet": ["ooxml xlsx sheets list", "ooxml xlsx sheets show", "ooxml xlsx ranges export", "ooxml xlsx ranges set", "ooxml xlsx ranges set-format", "ooxml xlsx cells extract", "ooxml xlsx cells set", "ooxml xlsx tables list", "ooxml xlsx tables show", "ooxml xlsx tables export", "ooxml xlsx names list", "ooxml xlsx names show"],
            "range": ["ooxml xlsx ranges export", "ooxml xlsx ranges set", "ooxml xlsx ranges set-format", "ooxml xlsx cells extract", "ooxml xlsx tables list", "ooxml xlsx tables show", "ooxml xlsx tables export", "ooxml xlsx names list", "ooxml xlsx names show"],
            "cell": ["ooxml xlsx ranges set", "ooxml xlsx cells set"],
            "table": ["ooxml pptx tables show", "ooxml xlsx tables list", "ooxml xlsx tables show", "ooxml xlsx tables export", "ooxml docx tables show", "ooxml docx tables set-cell", "ooxml docx tables clear-cell", "ooxml docx styles apply"],
            "name": ["ooxml xlsx names list", "ooxml xlsx names show"],
            "block": ["ooxml docx blocks", "ooxml docx blocks replace", "ooxml docx blocks delete", "ooxml docx blocks insert-after", "ooxml docx tables show"],
            "paragraph": ["ooxml docx text", "ooxml docx blocks", "ooxml docx blocks replace", "ooxml docx blocks delete", "ooxml docx blocks insert-after", "ooxml docx paragraphs append", "ooxml docx paragraphs insert", "ooxml docx paragraphs set", "ooxml docx paragraphs clear", "ooxml docx styles apply", "ooxml docx headers show", "ooxml docx headers set-text", "ooxml docx footers show", "ooxml docx footers set-text", "ooxml docx images list"],
            "style": ["ooxml xlsx ranges set-format", "ooxml docx styles list", "ooxml docx styles show", "ooxml docx styles apply"],
            "comment": ["ooxml pptx comments list", "ooxml docx comments list", "ooxml docx comments add", "ooxml docx comments edit", "ooxml docx comments remove"],
            "field": ["ooxml docx fields list", "ooxml docx fields insert", "ooxml docx fields set-result"],
            "header": ["ooxml docx headers list", "ooxml docx headers show", "ooxml docx headers set-text", "ooxml docx footers list"],
            "footer": ["ooxml docx footers list", "ooxml docx footers show", "ooxml docx footers set-text", "ooxml docx headers list"],
            "image": ["ooxml docx images list"]
        },
        "exitCodes": [
            {"code": EXIT_SUCCESS, "name": "success", "description": "command completed successfully"},
            {"code": EXIT_UNEXPECTED, "name": "unexpected", "description": "unexpected tool or package processing error"},
            {"code": EXIT_INVALID_ARGS, "name": "invalid_args", "description": "invalid command line arguments or incompatible options"},
            {"code": EXIT_FILE_NOT_FOUND, "name": "file_not_found", "description": "input file was not found"},
            {"code": EXIT_UNSUPPORTED_TYPE, "name": "unsupported_type", "description": "input package type is unsupported for the requested command"},
            {"code": EXIT_TARGET_NOT_FOUND, "name": "target_not_found", "description": "requested slide, sheet, table, shape, or macro part was not found"}
        ],
        "workflows": [
            {
                "name": "pptx inspect then edit",
                "commands": [
                    "ooxml --json inspect deck.pptx",
                    "ooxml --json pptx slides list deck.pptx",
                    "ooxml --json pptx slides selectors deck.pptx --slide 1",
                    "ooxml --json pptx slides show deck.pptx --slide 1 --include-text",
                    "ooxml --json pptx shapes show deck.pptx --slide 1 --include-text --include-bounds",
                    "ooxml --json pptx replace text deck.pptx --slide 1 --target title --text NEW --out edited.pptx",
                    "ooxml validate --strict edited.pptx"
                ]
            },
            {
                "name": "xlsx inspect then edit",
                "commands": [
                    "ooxml --json xlsx sheets list workbook.xlsx",
                    "ooxml --json xlsx ranges export workbook.xlsx --sheet sheetId:1 --range A1 --include-types",
                    "ooxml --json xlsx ranges set workbook.xlsx --sheet sheetId:1 --range A1:B2 --values '[[\"A\",\"B\"],[1,2]]' --out edited.xlsx",
                    "ooxml --json xlsx ranges set-format workbook.xlsx --sheet Sheet1 --range B2:B20 --preset currency --out edited.xlsx",
                    "serve op commands: xlsx cells set, xlsx ranges set, xlsx ranges set-format"
                ]
            }
        ],
        "conventions": [
            "stdout is data; diagnostics and errors go to stderr",
            "serve/MCP operation commands use op vocabulary without the leading ooxml",
            "mutations should be validated before handing files to users"
        ],
        "notes": notes,
    }))
}

fn capability_matches_filter(command: &Value, filter: &str) -> bool {
    let path = command
        .get("path")
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_ascii_lowercase();
    if path.contains(&format!(" {filter} ")) || path.ends_with(&format!(" {filter}")) {
        return true;
    }
    command
        .get("targetObjectKinds")
        .and_then(Value::as_array)
        .map(|kinds| kinds.iter().any(|kind| kind.as_str() == Some(filter)))
        .unwrap_or(false)
}

pub(crate) fn capability_commands() -> Vec<Value> {
    vec![
        capability_command(
            "ooxml version",
            "version",
            "Print the version of ooxml.",
            &[],
            false,
            Some("read-only metadata command"),
            vec![],
        ),
        capability_command(
            "ooxml capabilities",
            "capabilities [--for <filter>]",
            "Emit the Rust-supported machine-readable command and object inventory.",
            &[],
            false,
            Some("read-only self-description command"),
            vec![flag(
                "--for",
                "for",
                "string",
                "filter commands by supported command family or object kind",
            )],
        ),
        capability_command(
            "ooxml serve",
            "serve",
            "Run the JSON-RPC 2.0 stdio session server for web and agent workflows.",
            &[],
            false,
            Some("stdio session server; use JSON-RPC methods instead of op argv"),
            vec![],
        ),
        capability_command(
            "ooxml mcp",
            "mcp",
            "Run the MCP stdio server backed by the same Rust session engine.",
            &[],
            false,
            Some("MCP stdio server; use MCP tools/resources instead of op argv"),
            vec![],
        ),
        capability_command(
            "ooxml inspect",
            "inspect <file>",
            "Inspect a supported OOXML package.",
            &["package"],
            false,
            Some("read-only command; use inspect_current_with_ooxml through serve"),
            vec![],
        ),
        capability_command(
            "ooxml validate",
            "validate <file>",
            "Validate an OOXML package.",
            &["package"],
            false,
            Some("read-only validation command"),
            vec![],
        ),
        capability_command(
            "ooxml verify",
            "verify <file>",
            "Validate and compare a package against a baseline where supported.",
            &["package"],
            false,
            Some("read-only verification command"),
            vec![flag(
                "--baseline",
                "baseline",
                "string",
                "baseline file to compare against",
            )],
        ),
        capability_command(
            "ooxml pptx slides list",
            "list <file>",
            "List slides and stable slide selectors.",
            &["slide", "shape"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![],
        ),
        capability_command(
            "ooxml pptx slides selectors",
            "selectors <file> --slide <n>",
            "List targetable selectors for a slide.",
            &["slide", "shape"],
            false,
            Some("read-only command; generated by slides list/show"),
            vec![flag("--slide", "slide", "int", "1-based slide number")],
        ),
        capability_command(
            "ooxml pptx slides show",
            "show <file>",
            "Show slide text and stable selectors.",
            &["slide", "shape"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--include-text",
                    "includeText",
                    "bool",
                    "include visible text",
                ),
                flag(
                    "--include-bounds",
                    "includeBounds",
                    "bool",
                    "include shape bounds when available",
                ),
            ],
        ),
        capability_command(
            "ooxml pptx shapes show",
            "show <file> --slide <n>",
            "Show targetable shapes on a slide.",
            &["slide", "shape"],
            false,
            Some("read-only command; generated by slides list/show"),
            vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--include-text",
                    "includeText",
                    "bool",
                    "include text preview/content where available",
                ),
                flag(
                    "--include-bounds",
                    "includeBounds",
                    "bool",
                    "include explicit shape bounds where available",
                ),
            ],
        ),
        capability_command(
            "ooxml pptx masters list",
            "list <file>",
            "List slide masters with stable selectors, layout counts, and theme links.",
            &["master", "layout"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![],
        ),
        capability_command(
            "ooxml pptx masters show",
            "show <file> --master <n>",
            "Show one slide master, linked layouts, placeholders, theme, and text style summaries.",
            &["master", "layout", "placeholder"],
            false,
            Some("read-only command; generated by masters list"),
            vec![flag(
                "--master",
                "master",
                "int",
                "1-based master number; default 1",
            )],
        ),
        capability_command(
            "ooxml pptx layouts list",
            "list <file>",
            "List slide layouts with stable selectors and placeholder summaries.",
            &["layout", "placeholder"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag(
                "--master",
                "master",
                "int",
                "optional 1-based master number to filter layouts",
            )],
        ),
        capability_command(
            "ooxml pptx layouts show",
            "show <file> --layout <selector>",
            "Show one slide layout, placeholders, and theme/default text style context.",
            &["layout", "placeholder"],
            false,
            Some("read-only command; generated by slides list/show"),
            vec![flag(
                "--layout",
                "layout",
                "string",
                "layout number or exact layout name from layouts list",
            )],
        ),
        capability_command(
            "ooxml pptx tables show",
            "show <file> --slide <n>",
            "Show table graphic frames and cell text for one slide.",
            &["slide", "table"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--table-id",
                    "tableId",
                    "int",
                    "optional table shape ID to show",
                ),
                flag(
                    "--target",
                    "target",
                    "string",
                    "optional table selector such as table:1, shape:2, or ~Table 1",
                ),
                flag(
                    "--details",
                    "details",
                    "bool",
                    "include enriched row, column, cell, and span details",
                ),
            ],
        ),
        capability_command(
            "ooxml pptx extract text",
            "text <file>",
            "Extract slide text grouped by shape.",
            &["slide", "shape"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag(
                "--slide",
                "slide",
                "int",
                "1-based slide number; repeatable",
            )],
        ),
        capability_command(
            "ooxml pptx extract notes",
            "notes <file>",
            "Extract speaker notes from slides.",
            &["slide"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag(
                "--slide",
                "slide",
                "int",
                "1-based slide number; repeatable",
            )],
        ),
        capability_command(
            "ooxml pptx notes show",
            "show <file> --slide <n>",
            "Show speaker notes for one slide.",
            &["slide"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag("--slide", "slide", "int", "1-based slide number")],
        ),
        capability_command(
            "ooxml pptx comments list",
            "list <file> [--slide <n>] [--comment-id <id>]",
            "List PPTX slide comments with stable selectors, authors, dates, text, and hashes.",
            &["slide", "comment"],
            false,
            Some("read-only command; generated handles can be used by comment mutation commands"),
            vec![
                flag("--slide", "slide", "int", "optional 1-based slide number"),
                flag(
                    "--comment-id",
                    "commentId",
                    "int",
                    "show only this comment id; requires --slide",
                ),
            ],
        ),
        capability_command(
            "ooxml pptx replace text",
            "text <file>",
            "Replace text in the supported slide target.",
            &["slide", "shape"],
            true,
            None,
            vec![
                flag("--slide", "slide", "int", "1-based slide number"),
                flag(
                    "--target",
                    "target",
                    "string",
                    "shape selector, title for the frozen slice",
                ),
                flag("--text", "text", "string", "replacement text"),
                flag(
                    "--out",
                    "out",
                    "string",
                    "output file path for direct CLI use",
                ),
            ],
        ),
        capability_command(
            "ooxml pptx render",
            "render <file>",
            "Render a PPTX to PDF/thumbnails when local tools are installed.",
            &["slide"],
            false,
            Some("render command is not a mutation op"),
            vec![
                flag("--out", "out", "string", "render output directory"),
                flag("--slides", "slides", "string", "comma-separated slide list"),
                flag("--format", "format", "string", "json"),
            ],
        ),
        capability_command(
            "ooxml xlsx sheets list",
            "list <file>",
            "List workbook sheets and selectors.",
            &["sheet"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![],
        ),
        capability_command(
            "ooxml xlsx sheets show",
            "show <file>",
            "Show worksheet metadata, used ranges, and generated readback commands.",
            &["sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag("--sheet", "sheet", "string", "sheet selector")],
        ),
        capability_command(
            "ooxml xlsx names list",
            "list <file> [--scope-sheet <sheet>]",
            "List workbook and sheet-local defined names with selectors.",
            &["name", "sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag(
                "--scope-sheet",
                "scopeSheet",
                "string",
                "only list sheet-local names for this sheet selector",
            )],
        ),
        capability_command(
            "ooxml xlsx names show",
            "show <file> --name <selector> [--scope-sheet <sheet>]",
            "Show one workbook defined name by name, selector, or handle.",
            &["name", "sheet", "range"],
            false,
            Some("read-only command; generated by xlsx names list"),
            vec![
                flag(
                    "--name",
                    "name",
                    "string",
                    "defined name, selector, or workbook-scoped handle",
                ),
                flag(
                    "--scope-sheet",
                    "scopeSheet",
                    "string",
                    "sheet selector for sheet-local names",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx tables list",
            "list <file>",
            "List workbook tables",
            &["table", "range", "sheet"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![flag(
                "--sheet",
                "sheet",
                "string",
                "sheet number (1-based) or exact sheet name",
            )],
        ),
        capability_command(
            "ooxml xlsx tables show",
            "show <file>",
            "Show table metadata",
            &["table", "range", "sheet"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet number (1-based) or exact sheet name",
                ),
                flag(
                    "--table",
                    "table",
                    "string",
                    "table number, name, or displayName",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx tables export",
            "export <file>",
            "Export a table as a rectangular JSON matrix.",
            &["table", "range", "sheet"],
            false,
            Some("read-only command; generated by xlsx tables list/show"),
            vec![
                flag(
                    "--sheet",
                    "sheet",
                    "string",
                    "sheet number (1-based) or exact sheet name",
                ),
                flag(
                    "--table",
                    "table",
                    "string",
                    "table number, name, or displayName",
                ),
                flag(
                    "--include-types",
                    "includeTypes",
                    "bool",
                    "include cell types",
                ),
                flag(
                    "--include-formulas",
                    "includeFormulas",
                    "bool",
                    "include formulas",
                ),
                flag(
                    "--data-out",
                    "dataOut",
                    "string",
                    "write JSON matrix data to this file",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to export",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx workbook metadata inspect",
            "inspect <file>",
            "Inspect workbook core/app properties and calc settings.",
            &["package"],
            false,
            Some("it does not accept the mutation output flags injected by the op engine"),
            vec![],
        ),
        capability_command(
            "ooxml xlsx workbook metadata update",
            "update <file>",
            "Update workbook metadata fields and calc settings.",
            &["package"],
            true,
            None,
            vec![
                flag(
                    "--backup",
                    "backup",
                    "string",
                    "backup file path for --in-place",
                ),
                flag(
                    "--calc-mode",
                    "calcMode",
                    "string",
                    "set workbook calcMode (auto|manual|autoNoTable)",
                ),
                flag(
                    "--category",
                    "category",
                    "string",
                    "set core property category",
                ),
                flag("--company", "company", "string", "set app property Company"),
                flag(
                    "--creator",
                    "creator",
                    "string",
                    "set core property dc:creator",
                ),
                flag(
                    "--description",
                    "description",
                    "string",
                    "set core property dc:description",
                ),
                flag(
                    "--dry-run",
                    "dryRun",
                    "bool",
                    "validate mutation without writing",
                ),
                flag(
                    "--expect-category",
                    "expectCategory",
                    "string",
                    "guard: require current category to equal this value",
                ),
                flag(
                    "--expect-company",
                    "expectCompany",
                    "string",
                    "guard: require current company to equal this value",
                ),
                flag(
                    "--expect-creator",
                    "expectCreator",
                    "string",
                    "guard: require current creator to equal this value",
                ),
                flag(
                    "--expect-description",
                    "expectDescription",
                    "string",
                    "guard: require current description to equal this value",
                ),
                flag(
                    "--expect-keywords",
                    "expectKeywords",
                    "string",
                    "guard: require current keywords to equal this value",
                ),
                flag(
                    "--expect-last-modified-by",
                    "expectLastModifiedBy",
                    "string",
                    "guard: require current lastModifiedBy to equal this value",
                ),
                flag(
                    "--expect-manager",
                    "expectManager",
                    "string",
                    "guard: require current manager to equal this value",
                ),
                flag(
                    "--expect-subject",
                    "expectSubject",
                    "string",
                    "guard: require current subject to equal this value",
                ),
                flag(
                    "--expect-title",
                    "expectTitle",
                    "string",
                    "guard: require current title to equal this value",
                ),
                flag(
                    "--full-calc-on-load",
                    "fullCalcOnLoad",
                    "bool",
                    "set fullCalcOnLoad and forceFullCalc so Excel recalculates on open",
                ),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag(
                    "--keywords",
                    "keywords",
                    "string",
                    "set core property keywords",
                ),
                flag(
                    "--last-modified-by",
                    "lastModifiedBy",
                    "string",
                    "set core property lastModifiedBy",
                ),
                flag("--manager", "manager", "string", "set app property Manager"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip validation after mutation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--subject",
                    "subject",
                    "string",
                    "set core property dc:subject",
                ),
                flag("--title", "title", "string", "set core property dc:title"),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges export",
            "export <file>",
            "Export decoded worksheet cells from a range.",
            &["sheet", "range"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag(
                    "--include-types",
                    "includeTypes",
                    "bool",
                    "include cell types",
                ),
                flag(
                    "--include-formulas",
                    "includeFormulas",
                    "bool",
                    "include formulas",
                ),
                flag(
                    "--include-formats",
                    "includeFormats",
                    "bool",
                    "include style and number-format matrices",
                ),
                flag(
                    "--data-out",
                    "dataOut",
                    "string",
                    "write JSON matrix data to this file",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to export",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges set",
            "set <file>",
            "Set a worksheet range from a rectangular JSON, CSV, or TSV matrix.",
            &["sheet", "range", "cell"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--anchor", "anchor", "string", "top-left A1 cell"),
                flag("--values", "values", "string", "inline matrix data"),
                flag(
                    "--values-file",
                    "valuesFile",
                    "string",
                    "path to matrix data, or - for stdin",
                ),
                flag(
                    "--data-format",
                    "dataFormat",
                    "string",
                    "matrix data format: json, csv, or tsv",
                ),
                flag(
                    "--null-policy",
                    "nullPolicy",
                    "string",
                    "null handling: skip, clear, or empty-string",
                ),
                flag(
                    "--ragged",
                    "ragged",
                    "string",
                    "ragged handling: reject or fill-empty",
                ),
                flag("--max-cells", "maxCells", "number", "maximum cells to set"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--overwrite-formulas",
                    "overwriteFormulas",
                    "bool",
                    "allow replacing existing formula cells",
                ),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx ranges set-format",
            "set-format <file>",
            "Apply a practical number format to a worksheet range.",
            &["sheet", "range", "style"],
            true,
            None,
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag(
                    "--preset",
                    "preset",
                    "string",
                    "format preset: integer, number, currency, percent, date, datetime, text, or general",
                ),
                flag(
                    "--format-code",
                    "formatCode",
                    "string",
                    "custom SpreadsheetML number format code",
                ),
                flag(
                    "--decimals",
                    "decimals",
                    "number",
                    "decimal places for number, currency, and percent presets",
                ),
                flag(
                    "--currency-symbol",
                    "currencySymbol",
                    "string",
                    "currency literal for the currency preset",
                ),
                flag(
                    "--max-cells",
                    "maxCells",
                    "number",
                    "maximum cells to format",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "accepted for CLI compatibility",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cells extract",
            "extract <file>",
            "Extract decoded worksheet cells with stable cell selectors.",
            &["sheet", "range", "cell"],
            false,
            Some("read-only command; call via inspect in serve/MCP"),
            vec![
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--range", "range", "string", "A1 range"),
                flag("--max-rows", "maxRows", "number", "maximum rows to emit"),
                flag("--max-cells", "maxCells", "number", "maximum cells to emit"),
                flag(
                    "--include-empty",
                    "includeEmpty",
                    "bool",
                    "include empty cells inside output bounds",
                ),
            ],
        ),
        capability_command(
            "ooxml xlsx cells set",
            "set <file>",
            "Set a worksheet cell value.",
            &["sheet", "cell"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path"),
                flag("--cell", "cell", "string", "A1 cell reference"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag("--formula", "formula", "string", "cell formula"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag(
                    "--out",
                    "out",
                    "string",
                    "output file path for direct CLI use",
                ),
                flag("--ref", "ref", "string", "A1 cell reference alias"),
                flag("--sheet", "sheet", "string", "sheet selector"),
                flag("--type", "type", "string", "value type"),
                flag("--value", "value", "string", "cell value"),
            ],
        ),
        capability_command(
            "ooxml docx text",
            "text <file>",
            "Extract DOCX paragraph text.",
            &["package"],
            false,
            Some("read-only command"),
            vec![],
        ),
        capability_command(
            "ooxml docx blocks",
            "blocks <file>",
            "Show stable DOCX body blocks with hashes, selectors, paragraph metadata, table cells, and optional runs.",
            &[],
            false,
            Some("read-only command; block hashes and selectors feed hash-guarded DOCX mutations"),
            vec![
                flag(
                    "--block",
                    "block",
                    "int",
                    "1-based body block index to show",
                ),
                flag(
                    "--include-runs",
                    "includeRuns",
                    "bool",
                    "include paragraph run text and basic run properties",
                ),
            ],
        ),
        capability_command(
            "ooxml docx blocks replace",
            "replace <file>",
            "Replace a hash-guarded DOCX body block with a paragraph.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--block",
                    "block",
                    "int",
                    "1-based body block index from docx blocks",
                ),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: content hash from docx blocks",
                ),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--style",
                    "style",
                    "string",
                    "optional paragraph style ID; default preserves paragraph style when replacing a paragraph",
                ),
                flag("--text", "text", "string", "replacement paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to replacement paragraph text",
                ),
            ],
        ),
        capability_command(
            "ooxml docx blocks delete",
            "delete <file>",
            "Delete a hash-guarded DOCX body block.",
            &["paragraph", "table"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--block",
                    "block",
                    "int",
                    "1-based body block index from docx blocks",
                ),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: content hash from docx blocks",
                ),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag("--out", "out", "string", "output file path"),
            ],
        ),
        capability_command(
            "ooxml docx blocks insert-after",
            "insert-after <file>",
            "Insert a paragraph after a hash-guarded DOCX body block.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag(
                    "--block",
                    "block",
                    "int",
                    "1-based body block index from docx blocks; 0 inserts before the first block",
                ),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: content hash from docx blocks when --block is greater than 0",
                ),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--style", "style", "string", "optional paragraph style ID"),
                flag("--text", "text", "string", "paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to paragraph text",
                ),
            ],
        ),
        capability_command(
            "ooxml docx paragraphs append",
            "append <file>",
            "Append a main document body paragraph, preserving trailing section properties.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--text", "text", "string", "paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to paragraph text",
                ),
                flag("--style", "style", "string", "optional paragraph style ID"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx paragraphs insert",
            "insert <file>",
            "Insert a main document body paragraph after a body block index.",
            &["paragraph"],
            true,
            None,
            vec![
                flag(
                    "--insert-after",
                    "insertAfter",
                    "int",
                    "0 to prepend, or a 1-based body block index",
                ),
                flag("--text", "text", "string", "paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to paragraph text",
                ),
                flag("--style", "style", "string", "optional paragraph style ID"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx paragraphs set",
            "set <file>",
            "Replace one main document body paragraph's plain text.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--index", "index", "int", "1-based body block index"),
                flag(
                    "--handle",
                    "handle",
                    "string",
                    "stable DOCX paragraph handle",
                ),
                flag("--text", "text", "string", "replacement paragraph text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to replacement paragraph text",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx paragraphs clear",
            "clear <file>",
            "Clear one main document body paragraph's text while retaining paragraph metadata.",
            &["paragraph"],
            true,
            None,
            vec![
                flag("--index", "index", "int", "1-based body block index"),
                flag(
                    "--handle",
                    "handle",
                    "string",
                    "stable DOCX paragraph handle",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx styles list",
            "list <file>",
            "List DOCX paragraph, character, table, and numbering styles.",
            &["style"],
            false,
            Some("read-only command; generated style handles can be used by mutation commands"),
            vec![flag(
                "--type",
                "type",
                "string",
                "filter by style type: paragraph, character, table, or numbering",
            )],
        ),
        capability_command(
            "ooxml docx styles show",
            "show <file>",
            "Show detailed info for one DOCX style by styleId.",
            &["style"],
            false,
            Some("read-only command; generated style handles can be used by mutation commands"),
            vec![flag("--style", "style", "string", "styleId to show")],
        ),
        capability_command(
            "ooxml docx styles apply",
            "apply <file>",
            "Apply a paragraph, run, or table style to DOCX body content.",
            &["style", "paragraph", "table"],
            true,
            None,
            vec![
                flag(
                    "--index",
                    "index",
                    "int",
                    "1-based body block index for paragraph/run, or 1-based table number for table",
                ),
                flag(
                    "--handle",
                    "handle",
                    "string",
                    "stable DOCX paragraph handle for paragraph/run targets",
                ),
                flag(
                    "--target",
                    "target",
                    "string",
                    "style target: paragraph, run, or table",
                ),
                flag(
                    "--style",
                    "style",
                    "string",
                    "styleId or H:docx/pt:styles/style:n:<styleId> handle",
                ),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "optional sha256 block hash guard from docx blocks",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip style existence/type validation and post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx comments list",
            "list <file>",
            "List DOCX comments with stable selectors, hashes, and anchor blocks.",
            &["comment"],
            false,
            Some("read-only command; generated comment handles can be used by mutation commands"),
            vec![flag(
                "--comment-id",
                "commentId",
                "int",
                "show only the comment with this numeric w:id",
            )],
        ),
        capability_command(
            "ooxml docx comments add",
            "add <file>",
            "Add a DOCX comment anchored to a body paragraph.",
            &["comment"],
            true,
            None,
            vec![
                flag(
                    "--anchor-block",
                    "anchorBlock",
                    "int",
                    "1-based body block index to anchor to (default: first block)",
                ),
                flag("--author", "author", "string", "comment author name"),
                flag(
                    "--initials",
                    "initials",
                    "string",
                    "optional comment author initials",
                ),
                flag(
                    "--date",
                    "date",
                    "string",
                    "RFC3339 timestamp (default: now)",
                ),
                flag("--text", "text", "string", "comment text"),
                flag("--text-file", "textFile", "string", "path to comment text"),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx comments edit",
            "edit <file>",
            "Edit an existing DOCX comment by id or stable handle.",
            &["comment"],
            true,
            None,
            vec![
                flag(
                    "--comment-id",
                    "commentId",
                    "int",
                    "comment id from comments list",
                ),
                flag("--handle", "handle", "string", "stable DOCX comment handle"),
                flag("--text", "text", "string", "new comment text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to new comment text",
                ),
                flag("--author", "author", "string", "new author"),
                flag("--date", "date", "string", "new RFC3339 timestamp"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256 content hash from comments list",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx comments remove",
            "remove <file>",
            "Remove an existing DOCX comment and its range/reference markers.",
            &["comment"],
            true,
            None,
            vec![
                flag(
                    "--comment-id",
                    "commentId",
                    "int",
                    "comment id from comments list",
                ),
                flag("--handle", "handle", "string", "stable DOCX comment handle"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256 content hash from comments list",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx fields list",
            "list <file>",
            "List all simple/complex fields in document body + headers/footers.",
            &["field"],
            false,
            Some(
                "read-only command; cached field results are stale until Word recalculates fields",
            ),
            vec![flag(
                "--type",
                "type",
                "string",
                "show only fields whose leading instruction keyword matches",
            )],
        ),
        capability_command(
            "ooxml docx fields insert",
            "insert <file>",
            "Insert a simple DOCX field into a body, header, or footer paragraph.",
            &["field", "paragraph"],
            true,
            None,
            vec![
                flag(
                    "--location",
                    "location",
                    "string",
                    "target part:block location, e.g. body:2 or header1:1",
                ),
                flag(
                    "--field-code",
                    "fieldCode",
                    "string",
                    "field instruction, e.g. PAGE",
                ),
                flag("--result", "result", "string", "initial cached result text"),
                flag("--out", "out", "string", "output file path"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx fields set-result",
            "set-result <file>",
            "Set the cached result text of a simple or complex DOCX field.",
            &["field", "paragraph"],
            true,
            None,
            vec![
                flag(
                    "--selector",
                    "selector",
                    "string",
                    "field selector part:block:field, e.g. body:1:0",
                ),
                flag("--result", "result", "string", "new cached result text"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256 of instruction plus cached result",
                ),
                flag("--out", "out", "string", "output file path"),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag("--in-place", "inPlace", "bool", "write in place"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx headers list",
            "list <file>",
            "List headers and footers defined per section.",
            &["header", "footer"],
            false,
            Some(
                "read-only command; generated header/footer selectors can be pasted into show or set-text",
            ),
            vec![],
        ),
        capability_command(
            "ooxml docx headers show",
            "show <file>",
            "Show header content by type, section, or relationship id.",
            &["header", "paragraph"],
            false,
            Some("read-only command; accepts selectors from docx headers list"),
            vec![
                flag(
                    "--id",
                    "id",
                    "string",
                    "relationship id to resolve directly",
                ),
                flag(
                    "--section",
                    "section",
                    "int",
                    "1-based section index; 0 means the last section",
                ),
                flag(
                    "--selector",
                    "selector",
                    "string",
                    "selector from headers/footers list",
                ),
                flag("--type", "type", "string", "default, first, or even"),
            ],
        ),
        capability_command(
            "ooxml docx headers set-text",
            "set-text <file>",
            "Set header paragraph text by index.",
            &["header", "paragraph"],
            true,
            None,
            docx_header_footer_set_text_flags(),
        ),
        capability_command(
            "ooxml docx footers list",
            "list <file>",
            "List headers and footers defined per section.",
            &["footer", "header"],
            false,
            Some(
                "read-only command; generated header/footer selectors can be pasted into show or set-text",
            ),
            vec![],
        ),
        capability_command(
            "ooxml docx footers show",
            "show <file>",
            "Show footer content by type, section, or relationship id.",
            &["footer", "paragraph"],
            false,
            Some("read-only command; accepts selectors from docx footers list"),
            vec![
                flag(
                    "--id",
                    "id",
                    "string",
                    "relationship id to resolve directly",
                ),
                flag(
                    "--section",
                    "section",
                    "int",
                    "1-based section index; 0 means the last section",
                ),
                flag(
                    "--selector",
                    "selector",
                    "string",
                    "selector from headers/footers list",
                ),
                flag("--type", "type", "string", "default, first, or even"),
            ],
        ),
        capability_command(
            "ooxml docx footers set-text",
            "set-text <file>",
            "Set footer paragraph text by index.",
            &["footer", "paragraph"],
            true,
            None,
            docx_header_footer_set_text_flags(),
        ),
        capability_command(
            "ooxml docx images list",
            "list <file>",
            "List inline images in a DOCX document.",
            &["image", "paragraph"],
            false,
            Some(
                "read-only command; image records include relationship ids, media parts, dimensions, and block anchors",
            ),
            vec![],
        ),
        capability_command(
            "ooxml docx tables show",
            "show <file>",
            "Show DOCX tables by table index, body block index, dimensions, merged-cell flag, and cell text.",
            &[],
            false,
            Some(
                "read-only command; call via inspect in serve/MCP; generated table hashes feed hash-guarded DOCX table mutations",
            ),
            vec![
                flag(
                    "--details",
                    "details",
                    "bool",
                    "include detailed table object in JSON output",
                ),
                flag(
                    "--table",
                    "table",
                    "int",
                    "1-based table number; omitted shows all tables",
                ),
            ],
        ),
        capability_command(
            "ooxml docx tables set-cell",
            "set-cell <file>",
            "Set one main-document DOCX table cell's plain text.",
            &["table"],
            true,
            None,
            vec![
                flag("--table", "table", "int", "1-based table number"),
                flag("--row", "row", "int", "1-based table row"),
                flag("--col", "col", "int", "1-based table column"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: table block hash from docx tables show or docx blocks",
                ),
                flag("--text", "text", "string", "replacement cell text"),
                flag(
                    "--text-file",
                    "textFile",
                    "string",
                    "path to replacement cell text",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
        capability_command(
            "ooxml docx tables clear-cell",
            "clear-cell <file>",
            "Clear one main-document DOCX table cell's text.",
            &["table"],
            true,
            None,
            vec![
                flag("--table", "table", "int", "1-based table number"),
                flag("--row", "row", "int", "1-based table row"),
                flag("--col", "col", "int", "1-based table column"),
                flag(
                    "--expect-hash",
                    "expectHash",
                    "string",
                    "expected sha256: table block hash from docx tables show or docx blocks",
                ),
                flag("--out", "out", "string", "output file path"),
                flag(
                    "--in-place",
                    "inPlace",
                    "bool",
                    "write the input file in place",
                ),
                flag("--backup", "backup", "string", "backup path for --in-place"),
                flag("--dry-run", "dryRun", "bool", "plan without writing"),
                flag(
                    "--no-validate",
                    "noValidate",
                    "bool",
                    "skip post-write validation",
                ),
            ],
        ),
    ]
}

fn capability_command(
    path: &str,
    use_text: &str,
    short: &str,
    target_kinds: &[&str],
    op_compatible: bool,
    op_ineligible_reason: Option<&str>,
    local_flags: Vec<Value>,
) -> Value {
    let mut object = Map::new();
    object.insert("path".to_string(), json!(path));
    object.insert("use".to_string(), json!(use_text));
    object.insert("short".to_string(), json!(short));
    object.insert("targetObjectKinds".to_string(), json!(target_kinds));
    object.insert("localFlags".to_string(), Value::Array(local_flags));
    object.insert("opCompatible".to_string(), json!(op_compatible));
    if let Some(reason) = op_ineligible_reason {
        object.insert("opIneligibleReason".to_string(), json!(reason));
    }
    Value::Object(object)
}

fn docx_header_footer_set_text_flags() -> Vec<Value> {
    vec![
        flag(
            "--id",
            "id",
            "string",
            "relationship id to resolve directly",
        ),
        flag("--type", "type", "string", "default, first, or even"),
        flag(
            "--section",
            "section",
            "int",
            "1-based section index; 0 means the last section",
        ),
        flag(
            "--index",
            "index",
            "int",
            "1-based paragraph index within the part",
        ),
        flag(
            "--selector",
            "selector",
            "string",
            "selector from headers/footers list",
        ),
        flag("--text", "text", "string", "replacement text"),
        flag(
            "--text-file",
            "textFile",
            "string",
            "path to replacement text",
        ),
        flag("--out", "out", "string", "output file path"),
        flag(
            "--in-place",
            "inPlace",
            "bool",
            "write the input file in place",
        ),
        flag("--backup", "backup", "string", "backup path for --in-place"),
        flag("--dry-run", "dryRun", "bool", "plan without writing"),
        flag(
            "--no-validate",
            "noValidate",
            "bool",
            "skip post-write validation",
        ),
    ]
}

fn flag(name: &str, arg_name: &str, flag_type: &str, description: &str) -> Value {
    json!({
        "name": name,
        "argName": arg_name,
        "type": flag_type,
        "description": description,
    })
}
